### ISSUE TITLE
Duda Taller

### ISSUE THREAD

**Issue by sebamusea** [IIC2413/Syllabus-2024-1#1]
Tengo una consulta con respecto a el formato de los talleres evaluados de cátedra. No me queda claro que es lo que hay que hacer, como es el formato de la evaluación (que tipo de preguntas son). Busqué en el programa de curso pero no hay mucha información con respecto al Taller, excepto de cuando son y que su contenido. 
Muchas gracias de antemano

**Comment by cattpuccino** [comment]
Los talleres serán evaluados en papel y lapiz, por lo que no se tendrá acceso a apuntes o material externo.

**Comment by bea-or** [comment]
Hola, tengo una duda también respecto a los talleres. En el pdf que se subió a Canvas, dice que los talleres evaluados son parte de la nota de presentación pero en el github no lo toma en cuenta. ¿Cual es la formula correcta?

**Comment by ypne** [comment]
a qué te refieres con Github no lo toma en cuenta?

**Comment by bea-or** [comment]
Me refiero a que en la fórmula para calcular la nota que esta en github, no esta la parte de talleres.
Esto es lo que esta en github:
<img width="476" alt="Screenshot 2024-03-26 at 18 38 04" src="https://github.com/IIC2413/Syllabus-2024-1/assets/141878469/6c1e745b-7536-403e-93d2-eef263ca35b1">
Y esto es lo que esta en el programa y el ppt de la clase 1:
<img width="343" alt="Screenshot 2024-03-26 at 18 40 21" src="https://github.com/IIC2413/Syllabus-2024-1/assets/141878469/3b2c9575-6837-4500-a849-05d6d7f18698">
¿Cuál es la correcta?

**Comment by elbosco** [comment]
El oficial es el del programa, el del Github es el del anterior semestre.
