### ISSUE TITLE
Atributo disponibilidad de "Plato"

### ISSUE THREAD

**Issue by 3rdPix** [IIC2413/Syllabus-2024-1#10]
El atributo **disponibilidad** de plato... qué es? ¿es un número que refiere a la cantidad de estos platos que hay disponibles; y si es este el caso, esto es independiente del restaurant que lo ofrece? ¿ó se trata de un booleano, que en realidad está asociado a un restaurant e indica si tal plato está o no disponible en ese restaurant?

**Comment by RaiEscalona** [comment]
Disponibilidad del plato podría ser si es que esta se encuentra disponible en algún restaurante de la aplicación, ya que en esta aplicación buscas el plato y te muestra los restaurantes que los tiene. Por ejemplo, digamos que sacaron platos disponibles de una base de datos mundial y entre ellos está un pez exótico, pero no se encuentra en los restaurantes de Chile, entonces el plato no estaría disponible y no se mostraría en la aplicación.
