### ISSUE TITLE
consulta sobre subida de datos con caracteres especiales

### ISSUE THREAD

**Issue by TomasRiquelme** [IIC2413/Syllabus-2024-1#100]
buenas tardes!
estaba haciendo la subida de datos de "platos", que tiene caracteres como acento y ñ.
Estaba haciendo unas pruebas de "insert", ajustando parametros y cosas así, y accidentalmente se insertaron todos los datos.

Sé como eliminarlos de ser necesario, pero sucedió que los elementos con caracteres especiales fueron insertados de buena manera, sin problemas. Me imagino que es porque no especifique cómo codificarlos (utf-8 y esas cosas)
¿Hay un problema con esto? Se que los otros datos tienen caracteres más conflictivos, asi que si planeamos procesarlos como se debe

**Comment by ypne** [comment]
no hay problemas mientras no uses join

**Comment by TomasRiquelme** [comment]
bacaaaaaan, muchas gracias!
