### ISSUE TITLE
Importacion de datos pedidos.csv

### ISSUE THREAD

**Issue by LMD18** [IIC2413/Syllabus-2024-1#101]
Estaba intentando importar los datos de pedidos.csv en una tabla con el siguiente comando:

\COPY pedidos  from '/home/grupo76/Entrega2/CSV/pedidos.csv' DELIMITER ';' CSV HEADER

Pero me muestra el siguiente este error:
ERROR:  invalid byte sequence for encoding "UTF8": 0x97 

A que se debe esto?, alguien le ha pasado lo mismo y lo ha podido solucionar?

**Comment by ypne** [comment]
Lo más probable es que en los datos haya un caracter inválido y su cargador lo está detectando. Este tipo de problema es muy común en la vida real y la primera parte del proyecto se refiere a construir cargadores automáticos que entreguen este tipo de error para que posteriormente se pase a la etapa de limpieza de datos (actividad común en todo proyecto real de creación o migración de una base de datos). El problema del COPY es que no es un cargador sino que (según veo en la pregunta) están cargando los datos a una tabla sin normalizar. Cómo van a cargar esos datos al modelo normalizado automáticamente? La idea es que construyan un cargador que lea todos los datos del archivos.csv detecte todos los problemas y no solamente el primero para después corregirlos en conjunto (e indicarlo en el informe).

**Comment by Mikson16** [comment]
@ypne Para los cargadores, cuando lean los datos se puede usar la libreria csv ? El manejo de los datos y la carga se realiza con psycopg pero la lectura puede ser utilizando herramientas como csv?

**Comment by ypne** [comment]
Como lean los archivos lo eligen ustedes lo que importa es que el manejo de datos sea usando cursores. OJO que deben capturar todos las violaciones a las restricciones de integridad en la carga
