### ISSUE TITLE
Atributo Sucursal en pedidos.csv

### ISSUE THREAD

**Issue by DonMarto** [IIC2413/Syllabus-2024-1#102]
Hola, revisando los archivos para desarrollar tanto el esquema, como para crear las tablas, nos preguntamos a qué corresponde la sucursal en el archivo 'pedidos.csv'. En un inicio, asumimos que corresponde a la sucursal correspondiente al restaurant de donde proviene el pedido. 

Sin embargo, esto tiene un gran problema; un pedido puede (y ocurre en los datos) provenir de más de un único restaurant, y, a priori, no deben por qué tener una sucursal en común (o coincidir con aquella descrita en la tabla de pedidos). Un ejemplo de esto es el pedido con id=7, en donde el plato 1, por ejemplo, proviene de Burger Queen, que no tiene sucursal en Maintención. O tal vez, un ejemplo más crítico, es el pedido con id=93. Este pedido tiene como único plato aquel con id=37, el cual proviene del restaurant DCCRestaurant. Sin embargo, este restaurant tiene como única sucursal "Las Parcelas", mientras que la sucursal en la tabla de pedido refiere a la sucursal "Apoquindo". Por ende nos preguntamos, ¿a qué refiere el atributo sucursal en el archivo pedidos.csv?

No podemos simplemente eliminar todos los datos donde ocurre este problema, ya que ocurre, de alguna u otra manera, en la gran mayoría de los datos.

Nos resulta importante esto, ya que es la única forma para recuperar el restaurant, a partir de un pedido (pensando en las querys que tenemos que hacer).

¡Gracias de antemano!

**Comment by ypne** [comment]
Hola, muy buena acotación. Efectivamente los datos contienen una sucursal y puede que el restaurant no tenga esa sucursal, en la realidad se van a encontrar este tipo de problemas y debe corregirse. Sin embargo en este caso si lo que quieres es recuperar el restaurant, hay una dependencia entre el plato y el restaurant y lo puedes sacar de ahí.

**Comment by cron53** [comment]
Sin embargo hay 2 problemas:
1. Según el enunciado entrega 1, un pedido puede provenir de varios restaurantes.
2. Hay demasiadas tuplas inválidas, porque lo platos que tiene no son de ningún restaurant de la sucursal de esa tupla.

Acá claramente hay una contradicción y es el punto 1. que dije anteriormente: según enunciado, un pedido puede tener platos de varios restaurantes. ### "_En un pedido se puede solicitar comida de distintos restaurantes y el despacho será realizado por una sola empresa pero con un servicio despachador por restaurant._" De acuerdo a eso, un pedido de la tabla de pedidos ¿Es sólo el "sub-pedido" de un restaurant específico? Esto, ya que nos dan también delivery y despachador. En ese caso, además, es imposible saber el pedido completo. 

Gracias de antemano

**Comment by ypne** [comment]
elimina la columna sucursal, asume que el pedido viene de la comuna de la dirección

**Comment by c4ebt** [comment]
@ypne "La comuna de la dirección" vendría siendo la comuna del cliente. Sin embargo, el cliente puede tener múltiples direcciones. Consideremos el siguiente ejemplo:

Un pedido P realizado por el cliente C tiene plato A de restaurant A', y otro plato B de restaurant B'. El cliente C tiene una dirección en la comuna U y otra en la comuna V. El restaurant A' tiene una sucursal en la comuna U y no en la comuna V, y el restaurant B' tiene una sucursal en la comuna V y no en la comuna U.

¿Qué ocurre en este caso? No es posible asumir que el pedido viene "de la comuna de la dirección", ya que el cliente tiene dos direcciones, y una sirve para un restoran y la otra para el otro. Si eligiésemos una dirección arbitraria entre las que tiene el cliente, puede que esa dirección no cumpla con los requisitos de área de despacho de los restaurants, pero que otra sí cumpla.

Por otra parte, "la sucursal más cercana" no tiene nada de significado, no tenemos ninguna herramienta para determinar cuál es la más cercana (a excepción de la dirección, caso en el que aplica lo anterior).

¿Cómo se resuelve esta situación?

**Comment by ypne** [comment]
La dirección del cliente corresponde a la dirección de despacho. Las aplicaciones de delivery guardan todas las direcciones a las cuales es posible despachar. Si quiero una Pizza la puedo pedir a mi casa, o al airbnb que arrendé en otra ciudad o a la dirección del que sacó la casa para la junta. El dato que viene en la base es la dirección a la cual se despachó en el momento del pedido.

**Comment by chichitaocss** [comment]
Entonces, sabiendo que la columna Sucursal de la tabla Pedidos no nos sirve, la eliminamos. ¿Ahora como sabemos a que sucursal/es están pidiendo los platos? ¿Y hay una forma de saber a cuál de las direcciones del cliente hay que enviar el pedido?

**Comment by ypne** [comment]
Asume cualquiera de las sucursales del restaurant

**Comment by c4ebt** [comment]
Si podemos tomar cualquier sucursal, ¿entonces no es necesario que la sucursal esté en la misma comuna que el cliente (y por ende, que la dirección del cliente esté en su área de despacho)? ¿La sucursal puede estar en cualquier comuna?

**Comment by ypne** [comment]
Solo para efectos de la E2, en la siguiente parte del proyecto deberán hacer pedidos y ahí asignar la sucursal que esté en el área de despacho

**Comment by linfantek** [comment]
Hola, tengo las mismas preocupaciones ya mencionadas. 
Los platos de un mismo pedido pueden ser de distintos restaurantes, por lo que tener el dato de la sucursal no es útil (ya mencionaron que había que eliminarlo). Entonces, no tenemos como saber a que sucursal se pidieron los platos. 
Tampoco sabemos a que dirección del usuario fue entregado el delivery.
Además (pero no estoy segura), tengo entendido que los restaurantes solo pueden vender platos dentro de su comuna. Si ese fuese el caso, todo se solucionaría si en los datos del pedido se agregase la dirección de entrega, ya que así podríamos encontrar las sucursales de todos los restaurantes de los pedidos. Puede ser que falta esta información?

**Comment by ypne** [comment]
Hola
Tal como vimos en clase podemos tener información incompleta y como les dije antes pueden asumir cualquier sucursal. Su idea de poner la dirección de despacho en el pedido es buena, pueden agregarla para el modelo pero no poblarla por el momento
