### ISSUE TITLE
Encriptación en el esquema

### ISSUE THREAD

**Issue by c4ebt** [IIC2413/Syllabus-2024-1#104]
¿Es necesario que el hecho de que un atributo esté encriptado se exprese en el esquema relacional de alguna manera, por ejemplo, con una keyword "ENCRYPTED"? Más generalmente, ¿es necesario que expresemos en alguna parte del proyecto que las contraseñas se cargan encriptadas a la BDD, además de implementarlo en el código mismo?

**Comment by ypne** [comment]
no es necesario
