### ISSUE TITLE
Duda con Diagrama Pauta E1

### ISSUE THREAD

**Issue by Monti7475** [IIC2413/Syllabus-2024-1#105]
Según entiendo, tenemos que usar la pauta en caso de que nuestra E1 no esté buena. Pero a este le faltan cosas como subrayar las llaves y no sabemos si esten bien las flechas (e.g no hay flechas gruesas) por lo que no sabemos si seguir o no la pauta.

**Comment by Monti7475** [comment]
También está la entidad despachador dos veces

**Comment by ypne** [comment]
Hola
No hay que usar la pauta de la E1, esa es una solución posible aplicable al modelo. Sin embargo la E2 tiene más reglas de negocio y cambiaron los atributos. La idea es que extiendan su modelo (o pueden extender el de la pauta) para adecuarse a los requerimientos de E2
Con respacto a que despachador esté 2 veces es debido a que el dataset no está normalizado, lo que es parte del trabajo
