### ISSUE TITLE
Nuevos requerimientos del diagrama E/R

### ISSUE THREAD

**Issue by AleSierra26** [IIC2413/Syllabus-2024-1#107]
Mi duda es, en que parte del enunciado se encuentran las modificaciones que debemos realizar a nuestro diagrama? Es lo de regla de negocios? Porque hay ciertas cosas que consideramos que no tienen que ver con la modificación del diagrama sino que mas bien con la programaciones de restricción que vamos a crear en python.

**Comment by ypne** [comment]
Hola, así es parte de las reglas de negocio requieren un cambio del modelo y otras refieren a otros temas como el que indican
