### ISSUE TITLE
Diferencia entre archivos

### ISSUE THREAD

**Issue by plourido** [IIC2413/Syllabus-2024-1#108]
Hola qué tal? Espero que estén bien. Tengo una duda de porque hay archivos csv con _2? Esos son los que debemos ocupar o ocupamos los otros? Que he visto que se han actualizado mas de una vez, entonces para asegurarme
Muchas gracias

**Comment by ypne** [comment]
Hola los archivos  2 son los dataset en un formato diferente porque no estaban igual que los otros
en el caso de pedidos se sacaron 2 columnas porque estaban inconsistentes y no son necesarias

**Comment by Mikson16** [comment]
Volviendo a la pregunta anterior de @plourido, ¿debemos utilizar los archivos csv 2?  ¿O queda a nuestro completo criterio que archivo csv entre el original y el 2 debemos ocupar?

**Comment by ypne** [comment]
los datos son iguales, solo cambió el formato
