### ISSUE TITLE
Conectar base de datos con Django

### ISSUE THREAD

**Issue by NicoPuc** [IIC2413/Syllabus-2024-1#109]
Hola! estoy intentando conectar la base de datos que nos entregaron con mi aplicación en Django, pero nose como hacerlo... creo que falta información con guías para que se haga mas sencillo el creación de la app y en servidor... feliz si me ayudan o me dicen como conectar la web con la DB.
Gracias

**Comment by ypne** [comment]
Django no es necesario para el trabajo

**Comment by NicoPuc** [comment]
Y como me recomiendas que desarrolle la aplicación?

**Comment by ypne** [comment]
con psycopg, sobre todo si no saben usar  Django

**Comment by Mikson16** [comment]
Creo que la pregunta va más dirigida a como desarrollar la plataforma web de manera de poder conectar la base de datos, la cual estamos manejando con psycopg, a una aplicación desarrollada en Django, ya que es una herramienta que nos están permitiendo utilizar precisamente para el desarrollo de la parte web de la aplicación y no del manejo de la base de datos precisamente. Entonces, ¿de qué manera podemos conectar nuestra base de datos (que manejamos con psycopg) a nuestra aplicación web (que está desarrollada en Django)?

**Comment by ypne** [comment]
El uso de Django es opcional y no se ve en clases. Se supone que si lo están usando es porque saben previamente su uso.
