### ISSUE TITLE
Atributos propios o atributos de restaurant "Plato"

### ISSUE THREAD

**Issue by 3rdPix** [IIC2413/Syllabus-2024-1#11]
Algunos atributos son ambiguos en el sentido de a quienes están asociados los valores; por ejemplo, el atributo `tamaño` de un plato, ¿es algo característico del plato o está asociado al restaurant que lo ofrece? Lo mismo con "para cuántas personas es la porción ofrecida" ¿es algo propio de un plato, o qué tan grande sea la porción dependerá del restaurant?

**Comment by RaiEscalona** [comment]
Dentro de esos atributos, podrían cambiar para cada restaurante o podrían ser un rango como "pequeño", "mediano", "grande" y cada una de esas descripciones va hacia cada uno de los platos. También puede ser que cada plato es guardado por restaurante y las porciones que sugieren ellos y muchas otras formas de guardarlo. Ahora mismo no tienen datos con los que trabajar, pero estos se darán en otra entrega. Ahora tienen que modelas tablas de datos que hagan sentido, que estén bien hechas y que puedan contener la información que es necesaria. Les recomiendo que cada decisión la escriban dentro del pdf para evitar ambigüedades, que la corrección sea más fácil y los ayudantes no tener que adivinar sus supuestos, ya que esto podría afectar la forma en la que son evaluados.
