### ISSUE TITLE
Tipo de atributo de restricción de Platos

### ISSUE THREAD

**Issue by martina-abello** [IIC2413/Syllabus-2024-1#111]
Según el enunciado, la restricción debería ser int, pero procede a dar ejemplos de strings:
![imagen](https://github.com/IIC2413/Syllabus-2024-1/assets/128489585/2bf9b944-358f-42c4-aa9d-c42c3d75ca3c)

¿Eso es que hay que asignarle un int a cada tipo de restricción, o es un error del enunciado?

Gracias de antemano.

**Comment by ypne** [comment]
lo pueden modelar como estimen conveniente
