### ISSUE TITLE
Instalación de modulos en el server

### ISSUE THREAD

**Issue by 1982739** [IIC2413/Syllabus-2024-1#112]
Al ingresar mi proyecto en el SSH y tratar de instalar el modulo de flask y pycopg2 no me deja, ¿se podría habilitar el pip para instalar esos modulos?

**Comment by 1982739** [comment]
Por lo que entendí del enunciado, lo que se evaluará es lo que está dentro del server. Por lo que lo veo necesario.

**Comment by ypne** [comment]
1982739 tiene razón todo en el server
solicitaré al dcc instalar flask

**Comment by 1982739** [comment]
Con visual studio y WSL se puede entrar al SSH, porfavor que este Flask y psycopg2 para poder avanzar en el proyecto, muchas gracias!!!

**Comment by ypne** [comment]
Flask lo estamos haciendo andar (ya está instalado) aunque no es necesario para el proyecto. Psycopg está instalado

**Comment by ypne** [comment]
no es necesario, en caso de usar flask deben crear un ambiente diferente

**Comment by ypne** [comment]
La opción de usar Flask o Django es solo para los que saben hacerlo, en el curso hacemos el enfoque en bases de datos y para eso está instalado python, psicopg, apache y postgresql
