### ISSUE TITLE
Error en las tablas restaurantes2 y comuna2

### ISSUE THREAD

**Issue by eayaach** [IIC2413/Syllabus-2024-1#113]
cuando se generaron los cambios a las tablas ahora ñuñoa primero no se esta procesando bien debe ser un error de encoding. Y lo otro es que en la tabla restaurantes1 aparece "   Ñuñoa" con espacio pero en restaurante2 no tiene espacio aparece ',,u-oa'  a diferencia de todos los demás areas en la tabla.

**Comment by ypne** [comment]
Hola
el cargador debe detectar la falla, lo reparan, lo informan y vuelven a cargar la tuplas con errores de encoding. Ojo Machalí tambien tiene error
