### ISSUE TITLE
Solicitud instalar modulos servidor 

### ISSUE THREAD

**Issue by plourido** [IIC2413/Syllabus-2024-1#115]
Estimados, espero que se encuentren bien. Les escribo ya que necesito que en el servidor se me habilite la instalación de pip, para instalar las siguientes librerías:
- pandas
-datetime
- psycopg2
- numpy
- flask
Muchas gracias

**Comment by ypne** [comment]
Hola
psycopg2 está instalado
flask lo estamos haciendo ya que necesita un ambiente particular por grupo
pandas y numpy no se instalarán

**Comment by c4ebt** [comment]
Hola!

Podrían instalar Django también @ypne? Muchas gracias de antemano!

**Comment by ypne** [comment]
Estamos en eso

**Comment by ypne** [comment]
listo
