### ISSUE TITLE
Página para la entrega 2

### ISSUE THREAD

**Issue by vichoassadi** [IIC2413/Syllabus-2024-1#116]
Hola!
Entendemos que necesitamos crear una página en html para realizar las consultas del proyecto. Sin embargo, no logramos entender (como grupo) cómo implementamos esta página en el servidor que nos entregaron, ¿subimos el HTML y asociamos las consultas por detrás? ¿o tenemos que implementarlo mediante django o flask o alguna aplicación similar? Y, ¿cómo van a abrir la página desde el servidor? Siento que no está bien explicado en el enunciado, como en el Syllabus. Si es así, ¿podrían indicarme donde hay más explicaciones?
Muchas gracias

**Comment by ypne** [comment]
¿subimos el HTML y asociamos las consultas por detrás? SI
¿o tenemos que implementarlo mediante django o flask o alguna aplicación similar?  NO
¿cómo van a abrir la página desde el servidor?  http://pavlov.ing.puc.cl/home/grupoxx/index.html
