### ISSUE TITLE
Problema con psql

### ISSUE THREAD

**Issue by individuocomunycorriente** [IIC2413/Syllabus-2024-1#118]
Tenemos problemas para ingresar a la base de datos, al momento de ingresar la contraseña tenemos el siguiente error.

"psql: error: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: FATAL:  password authentication failed for user 'grupoXX'"

Intentamos con la contraseña predeterminada "grupoXX", la cambiamos y seguimos teniendo el mismo problema ;-;

**Comment by ypne** [comment]
XX es el número de su grupo

**Comment by individuocomunycorriente** [comment]
> XX es el número de su grupo

Así es, lo dejé así en la issue por un tema de privacidad, pero si intentamos con el número del grupo en cuestión.

**Comment by ypne** [comment]
cual es?

**Comment by individuocomunycorriente** [comment]
> cual es?

El 6

**Comment by Amandaasg** [comment]
Holaa, tenemos el mismo problema, somos el grupo 5

**Comment by ypne** [comment]
Listos grupo 5 y 6

**Comment by Amandaasg** [comment]
@ypne muchas gracias, pero tenemos otro problema. Luego de ingresar a psql, al intentar contectarnos a nuestra base de datos (con el comando \c grupoXXe2), la consola indica el error: "User does not have CONNECT privilege."

**Comment by ypne** [comment]
envíame un screenshot

**Comment by individuocomunycorriente** [comment]
> @ypne muchas gracias, pero tenemos otro problema. Luego de ingresar a psql, al intentar contectarnos a nuestra base de datos (con el comando \c grupoXXe2), la consola indica el error: "User does not have CONNECT privilege."

tenemos ese mismo problema en el grupo 6
![base de datos error](https://github.com/IIC2413/Syllabus-2024-1/assets/141957736/98249202-6faa-4e88-b076-67bcb8ae187f)

adjunto screenshot

**Comment by ypne** [comment]
Hola
ya están conectado a la base grupo6
trabajen ahí

**Comment by individuocomunycorriente** [comment]
> Hola
> ya están conectado a la base grupo6
> trabajen ahí

Okey, muchas gracias profe.
