### ISSUE TITLE
Pedido con restaurante

### ISSUE THREAD

**Issue by HaliaxWRYY** [IIC2413/Syllabus-2024-1#119]
Ahora que no tenemos una sucursal por cada pedido, como sabemos de donde el plato es enviado? Porque no tenemos ninguna asociación o dependencia en las tablas que nos ayude a saber de que restaurante es el plato del pedido.
Por eso no se podría cumplir con el enunciado "Cada Despachador solo puede atender máximo 2 pedidos del mismo Restaurant a la misma comuna." ya que no sabría de cual restaurante viene el pedido. 
¿Como hacemos la asociación ahora?

**Comment by ypne** [comment]
Si se sabe el restaurant, pueden asumir la sucursal mas cercana a la direccion
