### ISSUE TITLE
Llaves de las entidades

### ISSUE THREAD

**Issue by vmunozgarachena** [IIC2413/Syllabus-2024-1#12]
Hola! Se pueden usar _surrogate_ _keys_ para entregarle identificadores a las distintas entidades o es necesario que las llaves de estas estén basadas solo en la información del enunciado? 
Gracias!

**Comment by MartyMolina** [comment]
Sisi, esta correcto que utilices las surrogate keys

**Comment by vmunozgarachena** [comment]
Gracias!
