### ISSUE TITLE
Duda consulta inestructurada SELECT

### ISSUE THREAD

**Issue by c4ebt** [IIC2413/Syllabus-2024-1#122]
La tercera funcionalidad a implementar es la de hacer una consulta inestructurada `SELECT A FROM T WHERE C`.
Para esta consulta, al momento de evaluar, ¿se considerarán solo las tablas y atributos presentes en el esquema relacional propuesto?
Me preocupa, por ejemplo, que si en mi grupo decidimos trabajar todas las comunas en su forma de string, al momento de evaluar se quiera hacer un `SELECT cut FROM Comunas WHERE comuna = 'Macul'` y esto no se pueda hacer dado el esquema que planteamos nosotros. ¿Se respetarán las características del modelo propuesto en este respecto?

**Comment by ypne** [comment]
si es así la consulta debe dar un error
