### ISSUE TITLE
Inconsistencia entre tabla comuna y restaurantes

### ISSUE THREAD

**Issue by GonzaloMatus** [IIC2413/Syllabus-2024-1#123]
En el atributo "Area" de la tabla de restaurantes se menciona a la comuna de Santiago como "Santiago Centro", mientras que en el atributo "nombre" de la tabla de comunas se refiere a esta simplemente como "Santiago". ¿Es esto una inconsistencia que nosotros deberíamos manejar o es un error en la tabla de restaurantes?

**Comment by c4ebt** [comment]
En el caso de que nosotros debamos manejarla, ¿podemos elegir entre arreglar el atributo para insertarlo, o simplemente no insertar la fila?
Si se requiere que siempre tengamos que arreglar el atributo para insertarlo, esto significa que tendremos que revisar todos los atributos inconsistentes en los datos dados a mano para plantear soluciones caso a caso de manera correcta. Me imagino que esto no es lo que se busca, ya que tendríamos que leer todos los datos en búsqueda de estas inconsistencias.
