### ISSUE TITLE
Restricciones de largo en Diccionario de datos

### ISSUE THREAD

**Issue by c4ebt** [IIC2413/Syllabus-2024-1#124]
En el diccionario de datos del enunciado la mayoría de las strings están restringidas a 30 caracteres.
Sin embargo, una gran parte de estos atributos claramente sobrepasan los 30 caracteres en los datos.

Por ejemplo, algunos clientes tienen emails de largo mayor a 30; por otra parte, prácticamente el 100% de las descripciones de platos tienen más de 30 caracteres, sin embargo, en el enunciado este atributo está restringido a 30 caracteres.

¿Podemos asumir que estas restricciones de largo del enunciado pueden ser modificadas a nuestro criterio? En otro caso, se debería corregir el enunciado, ya que ningún plato sería válido si lo seguimos rigurosamente.

**Comment by AlonsoPlaza** [comment]
@ypne por favor responda profe

**Comment by ypne** [comment]
Sorry crei que había respondido. mala mia
Cuando inserten el dato les debería indicar una violación a las restricciones de integridad entonces ustedes deben elegir la mejor solución. En este caso tal como ustedes notaron la mejor solución es agrandar el campo. Solo deben hacerlo y documentarlo
