### ISSUE TITLE
Sobre normalización en diagrama E/R y datos en calificacion.csv

### ISSUE THREAD

**Issue by Coder-Mushroom** [IIC2413/Syllabus-2024-1#125]
Hola!! :cat:
Un par de consultas:

- ¿Es necesario que, una vez normalizado el modelo relacional, esta normalización también esté en el modelo E/R? Por ejemplo, si debemos separar una tabla en dos, ¿Habría que cambiar diagrama E/R agregando una nueva entidad?

- En el archivo calificacion.csv, ¿La columna "resdel" es la calificación del cliente al pedido y "cliente" la del despachador al cliente, o es al revés?

Muchas gracias de antemano. (^^)

**Comment by ypne** [comment]
Si creas entidades nuevas si debes cam,biar el modelo, al igual si cambias los atributos.

resdel es la calificación del pedido, el cual se aplica al delivery y despachador. y cliente es la calificación que hace el despachador  hacia el cliente

**Comment by Coder-Mushroom** [comment]
Muchas gracias por la respuesta! :smile_cat:, aunque no nos quedó del todo claro la primera, y quizá nos expliquemos mejor con un ejemplo: Supongamos que en el diagrama E/R hay una entidad X que tiene los atributos a, b y c. Esto en el esquema se vería como X(a, b, c). Luego, al normalizar nos damos cuenta de que es necesario dividir esta tabla en 2, quedando X1(a, b) y X2(a, c), pero la entidad sigue siendo la misma X. ¿Sería necesario que en el diagrama E/R la entidad X sea dividida en X1 y X2 o simplemente la dejamos como está?

**Comment by Mikson16** [comment]
Una consulta, en el mismo csv, pedido a que corresponde, si resdel es la calificacion del pedido y cliente la calificacion que hace el despachador, pedido corresponde al identificador del pedido?

**Comment by ypne** [comment]
@Coder-Mushroom Eso es parte de la materia, mientras esté en BCNF o 3NF estará bien
@Mikson16 resdel es la calificación del pedido y client la del cliente. Ambas calificaciones se hacen en el pedido
