### ISSUE TITLE
Problema formato teléfono Restaurant

### ISSUE THREAD

**Issue by c4ebt** [IIC2413/Syllabus-2024-1#126]
En el diccionario de datos se detalla el formato del teléfono de una sucursal:
![image](https://github.com/IIC2413/Syllabus-2024-1/assets/50504998/663392b8-953d-49c1-b37c-fa1a0598cfa6)
Asumo que +PP hace referencia al código de país, en nuestro caso +56. En los datos de teléfonos de `restaurantes2.csv` hay muchos teléfonos fijos, es decir, que empiezan con +562, y luego tienen el número de teléfono de 9 dígitos:
![image](https://github.com/IIC2413/Syllabus-2024-1/assets/50504998/02f88bca-e432-4ea0-a25c-30d65f985784)
(hay más que solo los de la foto)

Esto hace que el número quede un caracter más largo de lo que se espera según el formato del diccionario rompiendo la restricción/caracterización planteada en el enunciado. ¿Se arreglará esto en los datos? ¿O debemos ignorar los teléfonos de este largo y no insertarlos? ¿O debemos permitir teléfonos de largo variable?

**Comment by mariapazmunoz** [comment]
Tengo la misma duda!

**Comment by AlonsoPlaza** [comment]
@ypne muchas gracias por contestar la issue anterior, puede revisar esta también por favor

**Comment by ypne** [comment]
Github está raro, yo había respondido esto.
1.- Los teléfonos son ingresados por los usuarios por lo cual deben tener errores. En particular es muy usual en chile que las personas no ingresen el 9 antes del teléfono celular. Si este es el caso en todos los de 8 cifras pueden anteponer el 9.
2.- para el caso de los numeros mas cortos o mas largos no hay nada para corregir. Pueden poner en la tabla:
Telefono: INT o string(11) default: 0 o ´00000000000´
