### ISSUE TITLE
Sobre la creacion de las tablas

### ISSUE THREAD

**Issue by dvillas28** [IIC2413/Syllabus-2024-1#127]
¿Esta debe hacerse directamente en psql? o se tiene hacer desde pyhton?. Me hace sentido desde psql ya que solo tenemos que crearla una sola vez

Saludos 🤠

**Comment by ypne** [comment]
Buena pregunta, ustedes deciden pero puede ser  directo en la BD con psql, o en cos cargadores, sin embargo en esta segunda opción debieran manejar mas excepciones. Yo iría por psql
