### ISSUE TITLE
Normalización de clientes.csv [E2]

### ISSUE THREAD

**Issue by Ariimaw** [IIC2413/Syllabus-2024-1#128]
Hola! :3 tengo las siguientes dudas:

1. Dentro de lo que yo observe en clientes.csv, el email (único por cliente) y la dirección son suficiente para determinar todas las líneas de información del archivo, pero esto es bajo la suposición de que la dirección determina a la comuna. A puro ctrl-f esto es cierto dentro del archivo actual (Av. Colon siempre esta en Antofagasta, Av. Alemania siempre está en Temuco, etc), pero de todas formas quiero preguntar si podemos considerar esto como verdadero dentro de todo el contexto de la tarea. Ya que en el caso que testeen nuestro loader con archivos.csv distintos a los que están subidos actualmente, asumir que un atributo es no primo cuando lo es realmente nos dejaría con una normalización errónea. (Obviando las anomalías y errores)

2. También sobre las direcciones, podemos confiar en que el formato calle número, comuna, (y a veces provincia), se va a mantener cuando testeen nuestro loader? Pregunto especificamente porque fue una corrección en nuestra entrega anterior que debimos agregar atributos a dirección y hacer a esta una entidad más detallada, por lo que nos gustaría poder extraer la calle y su número especificamente pero esto depende al 100% de que el formato en que están escritas las direcciones se mantenga (Obviando el caso cuando los datos están mal ingresados o son anómalos, que ahí tenemos que decidir que hacer como grupo).

TLDR: ¿Son las calles siempre de una sola comuna? ¿El formato de las direcciones se mantendrá como calle número, comuna?

**Comment by ypne** [comment]
1.- las direcciones no determinan al cliente ya que ésta se refiere a la dirección de despacho, es decir un cliente tiene muchas direcciones y muchos clientes pueden tener la misma dirección. Lo que si se indica es que el email es único pór cliente.
2.- Ustedes deben incluir estas instrucciones.  En general por 1NF la dirección se debe tratar entera y no descompóner.
3.- la calles NO son de una sola comuna, casi todas los centros de las comunas tienen una calle Prat y una OHiggins

**Comment by Ariimaw** [comment]
Hola! :3 @ypne 
1.- No nos referíamos a eso, nunca pensamos que la dirección determine al cliente. Pero sí que con el email del cliente y la dirección se pueden diferenciar todas las líneas del archivo, queremos saber cuales son los "atributos primos" para luego normalizar basado en dependencias parciales o transitivas.

2.- OK! :3 Pero esto nos genera otra duda, si se espera que no separemos la dirección y que se trate como string, se espera el mismo trato con ingredientes en el archivo platos.csv?

3.- Eso también lo sabemos (soy de conce y las calles se repiten con stgo), por eso mismo hicimos la pregunta. Entonces trataremos las calles como corresponde, gracias! ^^

**Comment by ypne** [comment]
1.- La relación cliente dirección es 1:n
2.- Si quieren pueden separar la dirección. En la realidad es muy dificil hacer esto ya que al ser strings las pesonas ingresan las direcciones de muchas formas.  Para este proyecto pueden separarlo.
3.- Y yo de Pto Montt donde también se repiten las calles 😀

**Comment by tremendapithon** [comment]
Hola, al momento de separar los datos, debo crear un ID para identificar los datos en las otras tablas??? Tipo los datos de los clientes no estan en ningun xNF, pero para llegar a 3NF o BCNF debo separar las tablas por ID, el id puede ser con `id SERIAL PRIMARY KEY` o debo generar un id unico por tabla??

Saludos

**Comment by ypne** [comment]
Un tema de nomenclatura:
Los archivos entregados son datos no tablas por lo que si la pregunta se refiera a que hay que separar los datasets como si fueran tablas la respuesta es no.
Lo que hay que hacer es crear las tablas normalizadas y poblarlas con los datos de los csv
