### ISSUE TITLE
Suscripcion monto ultimo pago en diccionario de datos

### ISSUE THREAD

**Issue by ManuelV03** [IIC2413/Syllabus-2024-1#129]
Hola, revisando el diccionario de datos, aparece: "Suscripción monto ultimo pago: int (debe corresponder a uno de los valores definidos anteriormente)"
Asumo que esos "valores definidos anteriormente" son los precios de suscripción mensual o anual de cada delivery. Sin embargo, viendo todos los datos es posible darse cuenta de que en ninguna de las filas de suscripciones.csv se cumple esto. 
Es decir, ningún pago de suscripción concuerda con el valor mensual o anual del delivery correspondiente.
¿Que deberíamos hacer al respecto? Porque con la información que tenemos lo único que seguiría las restricciones sería eliminar todas las suscripciones.

**Comment by ypne** [comment]
estos pueden ser datos anteriores de pago a otro precio. En rigor el precio siempre depende de una fecha pero esto no lo incluimos en el modelo para simplificarlo. lo que si es importante en este caso es la fecha de último pago ya que eso, en conjunto con el ciclo determinan si la suscripción está activa. Por ejemplo si el útimo pago fue el 2023 la suscripción mensual está inactiva (al igual que en los streaming como netflix) aunque no diga cancelada, no así si el ciclo es anual y el último pago es en junio del 2023. Y por otra parte si la suscripción está cancelada pero el último pago del ciclo mensual es mayo 2024 o anual posterior a mayo 2023 el servicio sigue vigente solo que no se renovará.

**Comment by vichoassadi** [comment]
Entonces no nos fijamos en el monto del último pago, ni en su restricción de que tiene que pertenecer? Porque, sino, no entraría ninguna fila a nuestra base de datos. Podremos saltarnos directamente este atributo, o esta restricción?

**Comment by c4ebt** [comment]
@ypne Casi todos los últimos pagos tienen fecha en 2023. Eso haría que el 98% de las suscripciones mensuales no estén válidas, por lo que no me hace mucho sentido esto. Además, ¿por qué se incluye un atributo $estado \in (vigente, cancelada)$ en los datos si estos no influyen en si una suscripción está vigente o no? ¿debemos ignorarlo y seguir lo anterior, dejando al 98% de las suscripciones mensuales como no vigentes?

**Comment by ypne** [comment]
1.- Si los pagos son de ciclo mensual y del 2023 no están vigentes, si el ciclo es anual si podrían.
2.- si la suscripción no está vigente se cobra el despacho a precio unitario
3.-una suscripción está vigente en 2  si la fecha del último pago en menor a 1 mes en caso de ciclo mensual o menor a 1 año en ciclo anual. Independiente del estado
4.- el estado solo indica la intención del cliente de no efectuar la renovación de la suscripción
