### ISSUE TITLE
Duda Materia Llaves Foráneas y Entidades débiles

### ISSUE THREAD

**Issue by plourido** [IIC2413/Syllabus-2024-1#13]
Hola que tal, espero que se encuentren bien. Si todas las entidades que necesitan llaves foráneas, si o si son entidades débiles?
Muchas gracias

**Comment by elbosco** [comment]
Hola, solo las entidades que esas llaves foráneas también están incluidas en la llave primaria o la "tupla llave primaria" de esa misma entidad.
