### ISSUE TITLE
Duda sobre llaves y datos entregados

### ISSUE THREAD

**Issue by masoto22** [IIC2413/Syllabus-2024-1#130]
Hola, espero que estén muy bien, escribo porque nos surgió la siguiente duda: se tienen que cambiar las llaves según los datos entregados o podemos mantener el id y se le asigna uno al momento de cargar los datos desde los .csv?

Quedo pendiente
Saludos!

**Comment by ypne** [comment]
Si hay un id, pueden mantenerlo, si quieren inventar surrogate keys, háganlo según necesidad
