### ISSUE TITLE
Duda sobre poblar las tablas

### ISSUE THREAD

**Issue by Curi2164** [IIC2413/Syllabus-2024-1#131]
Hola, al querer llenar las tablas acorde a los archivos csv me surgió una duda respecto a la revisión, ¿al revisar la entrega 2 simplemente basta con que nuestra bdd tengan los mismos datos de los archivos csv bien organizados en las tablas y sin inconsistencias o van a revisar nuestra entrega con otros sets de datos, es decir otros archivos csv? Me surge la pregunta ya que de ser la segunda opción entonces se debería dejar una funcion de python en el servidor que se encargue de poblar todas las tablas? Pregunto ya que algunas tablas como por ejemplo la de calificacion solo basta con crearlas en consola a través de psql. Espero me puedan orientar un poco respecto a esa parte de la entrega porque estoy un poco confundido en ese aspecto. 

Saludos :)

**Comment by ypne** [comment]
Para revisión agregaremos un nuevo set  de datos a la base de datos que ya tienen cargada y realizaremos las consultas con él. No borraremos los datos anteriores. Por eso es importante que los cargadores manejen bien las restricciones de integridad.
