### ISSUE TITLE
Duda evaluación en consulta 9

### ISSUE THREAD

**Issue by c4ebt** [IIC2413/Syllabus-2024-1#132]
En la consulta 9 hay que mostrar todas las "evaluaciones" que cumplen con un criterio:
![image](https://github.com/IIC2413/Syllabus-2024-1/assets/50504998/8f3b171f-cfe7-417c-a5bf-114e54f9fc87)

En primer lugar, ¿qué es una evaluación exactamente? ¿es la tupla (resdel, cliente) de la calificación?
Por otra parte, ¿qué se requiere que sea mayor o igual al número ingresado? ¿Cada elemento de la tupla (AND)? ¿O al menos un elemento de la tupla (OR)?

**Comment by ypne** [comment]
1.- una evaluación es la nota que un cliente hace del pedido  resdel (que se aplica al delivery y al despachador) y que el despachador hace del cliente.
2.-  si es >=
3.- Son consultas por separadas o sea Clientes >=n, Delivery >= n y Despachador >=n o sea Todos los clientes, todos los despachadores y Todos los Delivery. Claro que como Despachador y Delivery son iguales serían las mismas.
