### ISSUE TITLE
Duda output de consultas

### ISSUE THREAD

**Issue by c4ebt** [IIC2413/Syllabus-2024-1#133]
Cuando en las consultas se dice "muestre los platos" que cumplen con cierto criterio, ¿lo que se busca es que se muestren los nombres de los platos, o los ids?

Me entra la duda porque, por ejemplo en la consulta 10, como los platos pueden tener distintos ingredientes en distintos restaurants, es posible que por ejemplo la DCCHamburguer del restaurant A tenga el alergeno pero no la del restaurant B, sin embargo, si selecciono el plato se mostrará DCCHamburguer y no se podrá saber si tiene el alergeno en todos los restaurants o solo en algunos. Esto se solucionaría seleccionando el id, sin embargo, es poco interpretable una consulta que solo retorna el id. Una mejor solución podría ser selecccionar el id y el nombre, pero a eso va la pregunta. ¿Qué se quiere que retornemos?

**Comment by ypne** [comment]
Los platos son únicos y determinan los Restaurantes por lo que lo lo lógico es que muestren el plato y el restaurant al menos. El id solo no tiene mucho sentido para el que hace la consulta si este es humano.

**Comment by c4ebt** [comment]
¿Entonces podemos tomarnos libertades en cuánto al output, mientras estas sean sensibles?

**Comment by ypne** [comment]
si mientras sea inteligible, está bien
