### ISSUE TITLE
Forma de Presentar los Resultados SQL

### ISSUE THREAD

**Issue by flcarvallo** [IIC2413/Syllabus-2024-1#134]
En la consulta SQL número 10 a implementar, se pide que, "dado una un alergeno ingresado por el usuario (string), muestre todos los platos que lo contengan en sus ingredientes (Ejemplo: manı́)", pero no queda claro si hay que agruparlos de cierta forma. Entonces, podemos mostrar el resultado de esta consulta mostrando tuplas del tipo (alergeno, nombre_plato, ingredientes), o hay que hacerlo de una forma específica, como por ejemplo (alergeno, lista_de_platos)? La diferencia es que en la primera consulta, se muestran todas las tuplas con solo un nombre de plato por tupla, mientras que en la segunda se agrupan todos los nombres de los platos que contienen alergenos en una misma tupla. Lo mismo va para las otras consultas que presentan ambigüedades de este tipo, es correcto decidir la mejor forma de implementarlo por nosotros mismos o hay alguna restricción en la forma de presentar la información?

**Comment by ypne** [comment]
tienen libertad de presentar el output con tal que sea inteligible y cumpla el objetivo
