### ISSUE TITLE
Servicios despachadores por pedido

### ISSUE THREAD

**Issue by vichoassadi** [IIC2413/Syllabus-2024-1#135]
En la entrega 1 se señaló lo siguiente:

> En un pedido se puede solicitar comida de distintos restaurantes y el despacho será realizado por una sola empresa pero con un servicio despachador por restaurant

Sin embargo, en los `.csv` que se nos pasaron para esta entrega, específicamente en el archivo `pedidos2.csv`, se pueden señalar muchos platos para un pedido (probablemente proviniendo de distintos restaurantes, por lo tanto, pudiesen tener más de un servicio despachador por pedido), pero solo un despachador por pedido. Esto está totalmente en contra de lo que se nos señaló en la primera entrega.

Por ejemplo, una línea de este archivo, junto con los encabezados, es la siguiente:

```csv
id;cliente;delivery;despachador;plato;fecha;hora;estado
7;Nicolas.Zambrano@bbdduc.utopia;Balloon;Eli Howard;1  19  56  6;23-09-23;9:18:36;entregado a cliente
```

Se ve claramente que tiene varios platos, y comparando, ya el plato 1 y el 19 vienen de diferentes restaurantes, por lo que debiese haber más de un despachador para este pedido y, sin embargo, solamente la tabla permite 1.

¿Qué hacemos en este caso? ¿Asumimos ahora que es solamente un despachador para todo el pedido y dejamos de lado lo que se nos dijo en la entrega 1?

**Comment by ypne** [comment]
Puedes levantar la restricción y asumir que la hace 1 solo. Sin embargo el modelo debe soportar multiples despachadores por pedido.
