### ISSUE TITLE
Normalización de platos.csv [E2]

### ISSUE THREAD

**Issue by Ariimaw** [IIC2413/Syllabus-2024-1#136]
Hola! :3 Las siguientes cosas no me quedan del todo claras:

TLDR: ¿Si una dependencia se cumple en el archivo actual, esto se mantendrá al corregir? ¿La restricción indica el grupo de gente que puede o que no puede comer el plato? ¿Y es relevante la restricción para consultar por alérgenos o solo usamos los ingredientes que están explícitos?

1. Se sabe por enunciado que "Los platos que se llaman igual pueden ser diferentes en cada Restaurante". Sin embargo, me gustaría saber más precisamente qué puede llegar a diferir aparte de lo que es observable en el archivo. Específicamente la descripción, estilo, restricción e ingredientes, pueden llegar a ser diferentes en platos con el mismo nombre? Pregunto porque como no nos son facilitadas las dependencias, sólo podemos normalizar al ojo y reconociendo patrones.

2. ¿Debemos tener en cuenta la restricción mencionada en un plato cuando se hace la consulta sobre alérgenos por la página web? Si bien ser vegetariano, vegano, celíaco, etc, no son alergias, si un celíaco no puede comer un plato es por que este debe contener gluten (aunque no se indique en los ingredientes?) y si se busca el ingrediente gluten en la página se espera que tengamos esto en consideración? 

3. Si la respuesta a lo anterior es sí, no nos queda claro si debemos interpretar la restricción como el grupo de gente que puede comer el plato o los que no pueden comer el plato. 
![image](https://github.com/IIC2413/Syllabus-2024-1/assets/73919101/220a3006-7e66-45a6-838d-32a9143401ab)
Como ejemplo las líneas de aquí son conflictivas. La hamburguesa tiene pan sin gluten pero igual indica a los celíacos en restricción, el carpaccio de salmón menciona a los pescetarianos aunque ellos si comen pescado, y luego está el pollo que claramente un vegetariano no puede comerlo, pero de los casos anteriores uno supondría que sí.

**Comment by ypne** [comment]
¿Si una dependencia se cumple en el archivo actual, esto se mantendrá al corregir?
R: no me queda la pregunta
¿La restricción indica el grupo de gente que puede o que no puede comer el plato? 
R: cual restricción? la del plato? No hay grupos de personas en la base, solo clientes y no se indica si tiene restricciones
¿Y es relevante la restricción para consultar por alérgenos o solo usamos los ingredientes que están explícitos?
R: son solo los ingredientes

1.- Difieren en descrip´ción, ingredientes, etc.
2.- Solo se busca por ingredientes
3.- se responde por el anterior

**Comment by chichitaocss** [comment]
¿Entonces no sirve de nada la columna restricción? ¿Además de mostrarla en la consulta 5?

**Comment by ypne** [comment]
Para esta entrega, debido a los cambios de fecha se trasladaron algunos requerimientos a la E2, si se fijan en el programa antes decía Queries y transacciones, pero son solo queries. Esa parte se usará en la E3.

**Comment by linfantek** [comment]
Hola, tengo la misma pregunta respecto a el punto 1. No me di cuenta y profundizo un poco más la duda en el issue #149, pero de todas maneras lo repito acá. 

En el enunciado sale que los platos que se llaman igual pueden ser distintos en cada restaurante. ¿Esta diferencia aplica para todos los atributos de los platos? Pregunto esto porque estamos analizando la dependencia de los atributos.
Al observar los datos se puede notar que para un plato con el mismo nombre, la descripción siempre es la misma, independiente de que estas sean de diferentes restaurantes. ¿Esto es coincidencia, o podemos asumir que la descripción es determinada por el nombre del plato y no por el nombre del plato y el restaurante? Esta duda se extiende a los atributos estilo, restricción, ingredientes y porciones. 
Por ejemplo, para la pizza margarita se puede notar que la descripción, el estilo, la restricción, los ingredientes y las porciones son iguales independiente del restaurante.

**Comment by ypne** [comment]
En el caso de la pizza margarita es esperable que la descripción e ingredientes sean los mismos pero no es obligación. Si lo quieres en lenguaje de BD el nombre no determina la descripción y los ingredientes
