### ISSUE TITLE
Sobre los Delivery que tiene los Restaurantes

### ISSUE THREAD

**Issue by vickyvd** [IIC2413/Syllabus-2024-1#137]
Hola!
Tengo una duda. Por lo que entiendo del enunciado, los Restaurantes/Sucursal pueden tener solo algunos Delivery, pero no estoy segura donde se refleja esta información en los datos de los csv (información que se necesita mostrar en las consultas de sql 4 y 6).
En el csv de Pedidos salen los platos (con los que se pueden obtener los restaurantes) y la empresa de delivery, por lo tanto, es correcto asumir que todas las relaciones existentes entre un restaurente y las empresas de delivery con las que cuentan vienen de estos datos? o puede un restaurante tener además relación con otras empresas? si es así, de donde puedo obtener esa información?
Muchas gracias!

**Comment by ypne** [comment]
Cada vez que haya una tupla conteniendo restaurat, delivery existe esa relación, pueden haber mas pero si no hay datos no pueden asumir cuales son.
