### ISSUE TITLE
Entidad Delivery (propio) y .csv

### ISSUE THREAD

**Issue by chichitaocss** [IIC2413/Syllabus-2024-1#139]
Una regla del negocio dice "Los Restaurantes/Sucursal pueden tener Delivery propio." Con esto me surgen dos dudas:

1. ¿Es válido asignar los delivery solo a las sucursales si las sucursales están asociadas a los Restaurantes? O hay que seguir la frase anterior al pie de la letra, aunque no sea necesario. Por que pueden ocurrir los siguientes casos; todas las sucursales de un restaurant tienen delivery propio, por lo que podría asignar el delivery al restaurant, no a las sucursales. O bien puede pasar que solo algunas sucursales de un restaurant tengan delivery propio por lo que hay que asociar el delivery propio a las sucursales directamente.

3. ¿Que significa la columna vigente de restaurantes.csv?

5. En ninguno de los .csv se puede observar a un pedido con delivery propio, y si lo hay, ¿cómo se identifica? Creo que lo más intuitivo es que en la columna delivery de la tabla pedidos.csv aparezca el nombre del delivery y si no aparece, i.e. null, que sea propio.

En el caso de que se implemente esto, agradecería facilitaran un .csv que sí sirva para poblar toda nuestra base de datos, contemplando todas las reglas del negocio solicitadas.

**Comment by ypne** [comment]
1.- Si puede ser, sin embargo se puede asignar el despachador a la sucursal. Por otra parte todo pedido se hace en las sucursales, si el restaurant tiene solo una dirección, esa es la casa matriz y se modela como sucursal única.
2.- Si el restaurant está funcionando en estos momentos
3.- No hay, pero deben modelarlo.
