### ISSUE TITLE
Servicio despachador vs Empresa despachadora

### ISSUE THREAD

**Issue by Fopazov** [IIC2413/Syllabus-2024-1#14]
Hola cómo están? Sé que ya lo preguntaron, pero no me quedó clara la relación servicio despachador y empresa despachadora.
* Primero se dice que "los clientes deben seleccionar que servicio de despacho quieren usar, mostrando el costo de cada uno de los servicios de despacho disponibles... ". De aquí desprendo que al realizar un pedido el cliente tiene que escoger un servicio, como ubereats, pedidosya....
Sin embargo, luego se menciona lo siguiente:
* "en un pedido se puede solicitar comida de distintos restaurants y el despacho será realizado por una sola empresa pero con un SERVICIO DESPACHADOR POR RESTAURANT"
* ⁠Primero se dice que el cliente escoge un solo servicio de despacho, pero luego que una empresa tendrá un servicio despachador por restaurant.
* Entonces, ¿Cual es la diferencia entre servicio despachador y empresa despachadora?
* ⁠¿En un pedido una persona escoge 1 o varias empresas despachadoras (o servicio, no lo tengo claro) (ubereats, pedidosya,...)?
* gracias de antemano

**Comment by RaiEscalona** [comment]
Un servicio de despachos es el servicio que brinda la empresa despachadora al cliente para poder buscar su comida. 
En cuanto al pedido, el usuario debería poder elegir si es que quiere que solo una empresa haga el retiro de sus productos a todos los restaurantes o locales o si quiere un servicio de despacho por cada restaurante. 
Por ejemplo, digamos que pediste comida en 3 restaurantes y quieres que la comida te llegue apenas fue hecha, entonces pedirías un delivery para cada local, de esta forma no esperas buscar todos los productos a la vez. Pero si quieres tener todo al mismo tiempo, pides solo 1 delivery.

**Comment by JorgeBravo98** [comment]
Una vez que el cliente escoge una empresa despachadora para su pedido, decide arbitrariamente la cantidad de servicios de despacho (cantidad de repartidores). Por ejemplo, una persona pide comida de 3 restaurantes diferentes y escoge como empresa uber eats, podría definir que 2 personas realicen el delivery o solo están las opciones de 1 o 3?

**Comment by RaiEscalona** [comment]
Eso es más libre o puedes modelarlo ustedes. Te recomiendo que la decisión que tomen y cómo lo modelan lo dejen escrito y bien definido en el pdf.

**Comment by martina-abello** [comment]
> Un servicio de despachos es el servicio que brinda la empresa despachadora al cliente para poder buscar su comida. En cuanto al pedido, el usuario debería poder elegir si es que quiere que solo una empresa haga el retiro de sus productos a todos los restaurantes o locales o si quiere un servicio de despacho por cada restaurante. Por ejemplo, digamos que pediste comida en 3 restaurantes y quieres que la comida te llegue apenas fue hecha, entonces pedirías un delivery para cada local, de esta forma no esperas buscar todos los productos a la vez. Pero si quieres tener todo al mismo tiempo, pides solo 1 delivery.

Pero entonces el despacho sí puede hacerse con un único servicio despachador para los 3 restaurantes, ¿no? Siendo que el enunciado dice que tiene que ser 1 servicio para cada restaurante.
Y sigo sin entender la diferencia entre empresa y servicio despachador.

**Comment by bea-or** [comment]
> Un servicio de despachos es el servicio que brinda la empresa despachadora al cliente para poder buscar su comida. En cuanto al pedido, el usuario debería poder elegir si es que quiere que solo una empresa haga el retiro de sus productos a todos los restaurantes o locales o si quiere un servicio de despacho por cada restaurante. Por ejemplo, digamos que pediste comida en 3 restaurantes y quieres que la comida te llegue apenas fue hecha, entonces pedirías un delivery para cada local, de esta forma no esperas buscar todos los productos a la vez. Pero si quieres tener todo al mismo tiempo, pides solo 1 delivery.

Cuando dices "En cuanto al pedido, el usuario debería poder elegir si es que quiere que solo una empresa haga el retiro de sus productos a todos los restaurantes o locales o si quiere un servicio de despacho por cada restaurante," no estas diferenciando entre empresa despachadora y servicio despachador. No entiendo cual es la relación entre estas dos entidades, si es que el cliente tiene que elegir la empresa o el servicio, si es que cada restaurante tiene solo una empresa despachadora asociada o si tiene varias o si es que un restaurant tiene uno o varios servicios despachadores asociados?
