### ISSUE TITLE
Duda sobre la consulta 2

### ISSUE THREAD

**Issue by vickyvd** [IIC2413/Syllabus-2024-1#140]
Hola!
Tengo un pregunta con respecto a la consulta 2. Esta dice 'Muestre todos los pedidos de un usuario específico ingresado (email string) y su gasto mensual (solo los pedidos concretados)', el gasto mensual se refiere al monto total de todos los pedidos concretados en un mes ignorando las suscripciones que puede tener el usuario? o hay que considerar las suscripciones? si es esto último, en el caso de una suscripción anual, el gasto mensual lo consideramos como el monto anual dividido en 12?
muchas gracias :)

**Comment by ypne** [comment]
Buena pregunta, en caso de suscripción anual usa el pago/12
