### ISSUE TITLE
Dividir csv en más de una tabla

### ISSUE THREAD

**Issue by Afibla** [IIC2413/Syllabus-2024-1#141]
Hola no me quedó claro esta parte de la duda #94
"Bajo lo anterior, ¿qué ocurre si en cierto .csv encontramos tuplas que contienen datos que según nuestro modelo deberían ir en tablas distintas? pregunto esto pensando específicamente en las dependencias y en las tablas que representan relaciones entre entidades en nuestro modelo E/R ¿Que se hace en esos casos?"
_Originally posted by @dvillas28 in https://github.com/IIC2413/Syllabus-2024-1/issues/94#issuecomment-2116395710_
Entiendo que se utilizan los códigos de la ayudantía, pero no me queda claro cómo especificar que atributo del csv va a cierta tabla si queremos dividir los datos en más de una tabla.
Saludos

**Comment by ypne** [comment]
Los datos de los archivos no son tablas son datasets ustedes deben crear las tablas según su modelo y luego leer estos datos y poblarlas.

**Comment by flcarvallo** [comment]
Solo para confirmar, ¿sería valido crear otro dataset limpio y ocupar ese para poblar las tablas?

**Comment by ypne** [comment]
no, los csv se usan como están

**Comment by JpOlivares08** [comment]
Pero, por ejemplo, si quiero usar datos de dos .csv distintos para armar una tabla.
1. ¿Es posible abrir los archivos .csv en un archivo python y decidir qué datos arman una tupla?
2. Los .csv que van a usar para corregir esta entrega, ¿van a tener el mismo formato que los que nos dieron de ejemplo?
3. ¿Puede que los archivos con los que nos van a corregir tengan tantas inconsistencia como los datos actuales?

**Comment by ypne** [comment]
1.- si
2.- si
3.- si, para probar la IC
