### ISSUE TITLE
Duda crear relaciones

### ISSUE THREAD

**Issue by clemente-arrieta** [IIC2413/Syllabus-2024-1#144]
Hola, con mi grupo teniamos una duda acerca de si las relaciones (o tablas) que creamos deben ser iguales a los archivos dados, o si pueden ser a nuestro criterio. No sabemos si esto cuenta como pre-procesar los datos antes de subirlos, por eso queríamos confirmar.

Gracias

**Comment by vichoassadi** [comment]
Estamos en la misma... 

Entiendo que tenemos que hacer las tablas en base a nuestro modelo ER y adaptar los datos de los csv, pero dicen que no se pueden pre-procesar los datos, entonces no entendemos por acá si es posible, por ejemplo, agarrar datos de 2 csv distintos y solo algunos atributos de estos para armar una base de datos según nuestro esquema

**Comment by Ariimaw** [comment]
Hola! @ypne :3 

Tenemos entendido que no puede haber pérdida desde los datasets a nuestro modelo, y nos gustaría saber si tampoco está permitido que agreguemos información para ajustar los datasets de forma más sencilla a nuestras tablas. ¿Está esto permitido? También nos preguntamos qué diferencia real hay entre las siguientes formas de abordar el proyecto:

- Normalizar nuestro modelo antiguo para que cumpla BCNF/3NF junto con modificarlo para que calce con los datasets.
- Tratar los datasets como tablas y normalizarlas directamente.

Ya que al no poder perder información, (y posiblemente tampoco agregar), no se llegaría realmente a las mismas tablas/entidades con ambos caminos? ¡Gracias de antemano!

**Comment by ypne** [comment]
Si se puede tener información faltante (tema visto en clases) no pueden inventar datos pero si completar partes que estén incompletas como teléfonos de 8 cifras que pueden asumir que es celular y anteponer el 9
