### ISSUE TITLE
Duda Carga de Datos

### ISSUE THREAD

**Issue by espeescobar** [IIC2413/Syllabus-2024-1#146]
Hola, no me queda muy claro el enunciado acerca de la carga de los datos a al servidor. Cargué los archivos al servidor siguiendo las instrucciones de la Wiki y entré al postgres. Entiendo que el enunciado dice que los datos deben cargarse automaticamente desde pyhton, pero se deben cargar a postgres? Las consultas deben hacerse desde el script de python tambien?
Además, el enunciado dice "los datos deben ser cargados automáticamente, desde los archivos, sin pre-procesamiento previo", pero, tambien se indica que "en la carga inicial de datos se deberá chequear la integridad de los mismos y cuando haya falla tomar la acción más idonea (corregir o eliminar)" y que "para la carga inicial de datos se deberán encriptarlos". Corregir, eliminar e encriptar los datos no cuenta como pre-procesamiento?

muchas gracias :)

**Comment by ypne** [comment]
Esto está respondido en varios issues antes
1.- crear modelo E/R 
2.- crear esquema normalizado a partir del esquema 
3.- crear las tablas
4.- crear scripts en python para cargar los datos directamente de los csv y capturar los errores
5.- corregir los errores e indicar en el informe como se hizo
6.- cargar los datos corregidos usando los cargadores

**Comment by Osiries1111** [comment]
Hola!
Tenía una duda super parecida,
Entiendo que al final tenemos que capturar los errores, pero no podemos hacer como una "pre-verificación" de los datos antes de cargarlos, para evitar la mayor cantidad de errores de integridad posibles? es decir, revisar por ejemplo, antes de subir los datos, que cumplan con las restricciones de integridad, como puede ser que cumpla con que el largo sea a lo más de 30 caracteres, y luego cargarlos a la tabla?

**Comment by ypne** [comment]
no

**Comment by Osiries1111** [comment]
Entonces, necesariamente hay que subir los datos como estén y luego ver uno a uno los errores?

**Comment by ypne** [comment]
si, se ven de caso a caso pero en el informa todos los errores iguales con igual corrección se reportan solo una vez. Por ejemplo:
- el 90% de las direcciones tiene mas de 30 caracteres. Para no perder datos la solución aplicada es  .........
- Existen xx registros con caracteres inválidos a ingresar a la tabla T. Para corregir se .........
- Los siguientes registros no cumplen con la restricciones de FK y los registros fueron .......
