### ISSUE TITLE
Procesamiento durante carga de datos

### ISSUE THREAD

**Issue by endlessloop2** [IIC2413/Syllabus-2024-1#148]
Hola,
Mi pregunta es si se puede usar alguna librería previa a la carga con `psycopg` para seleccionar columnas, o encargarse de errores como campos de string que exceden el largo requerido.
He considerado `pandas`, imagino que no se puede. Se podría usar `csv`? Considerando que `csv` es una librería de la standard library de Python?

Saludos.

**Comment by ypne** [comment]
solo se permite psycopg para manipular datos

**Comment by endlessloop2** [comment]
> solo se permite psycopg para manipular datos
@ypne 
Me queda claro. En todo caso me queda la duda de que se considera manipular. Es decir, si uso `csv` para **seleccionar** columnas del CSV, también se considera manipular? Esto facilita ocupar un INSERT vs un comando copy de postgres.

**Comment by ypne** [comment]
Solo se permite la lectura de los datos del CSV
