### ISSUE TITLE
Sobre atributos en el enunciado

### ISSUE THREAD

**Issue by masoto22** [IIC2413/Syllabus-2024-1#15]
Hola

Tenemos una duda respecto al enunciado de la entrega. 

Queríamos consultar si los atributos indicados en el enunciado son restringidos y solo deben ser esos, o es un mínimo y en el caso de querer agregar atributos para hacer las relaciones se podría sin problemas?

Por ejemplo, para cliente aparece nombre, correo electrónico, clave, direcciones de entrega, número de teléfono. Pero para administradores no se mencionan atributos y en despachadores incluyen "otros datos personales" sin especificar cuáles serían aparte de nombre y número de teléfono.

Quedo pendiente
Gracias!

**Comment by RaiEscalona** [comment]
Si, pueden agregar atributos para que hagan más sentidos los datos. En el enunciado se les dice lo que deben modelar, pero si sienten que hay más cosas que agregar, las pueden agregar, pero pónganlo dentro del pdf para poder facilitar la corrección. 
Por último, esos atributos deberían tener sentido y no complicar la lectura de la información.

**Comment by Mikson16** [comment]
Hola, sobre este mismo punto si se desea hacer algo como, asumir que los correos son únicos para cada entidad que los tenga ( es decir es una Key primaria), ¿Esta permitido? En ese caso se debe especificar en el documento adjunto porque se hicieron las suposiciones y la argumentación ¿verdad?
