### ISSUE TITLE
Duda otros clientes 

### ISSUE THREAD

**Issue by tremendapithon** [IIC2413/Syllabus-2024-1#151]
Hola buenas, tengo una duda con los clientes que estan en las otras tablas, ya que poseen la misma información de un cliente normal, por ende, estos los debo agregar también a la tabla de los clientes?? O por defecto eliminarlos si no estan??

Saludos

**Comment by ypne** [comment]
Deben agregarlos

**Comment by tremendapithon** [comment]
y si no tienen dirección?

**Comment by ypne** [comment]
No importa ya que quedará como un campo nulo o vacío el que se llenará en el próximo pedido. Vimos en clase que las bases pueden tener datos incompletos

**Comment by tremendapithon** [comment]
Si, pero en el diccionario de los datos sale que es no nulo. Entonces para esos casos debo asignarles como, no direccion o algo por el estilo?

**Comment by ypne** [comment]
Si
