### ISSUE TITLE
Duda al momento de normalizar

### ISSUE THREAD

**Issue by tremendapithon** [IIC2413/Syllabus-2024-1#152]
Hola, resulta que estoy normalizando la tabla de los clientes, y me genero duda de que hacer con los id de cada tabla que genera el proceso de normalizacion, ya que al tener datos repetidos voy a atomizar los datos, pero para lo anterior creo una tabla con nombres, correos, teléfonos, etc. Separados, pero que voy a tener cada tabla con sus id, pero al crear los id con sql utilizo serial, pero esto siento que no es lo más óptimo, que debo hacer en ese caso.

**Comment by ypne** [comment]
Deben evaluarlo
Para delivery clientes platos despachadores si se puede usar serial

**Comment by ypne** [comment]
Si el id es de la tupa y es consistente con el resto de la base está bien.
