### ISSUE TITLE
Delivery propio vs delivery no exclusivo

### ISSUE THREAD

**Issue by masoto22** [IIC2413/Syllabus-2024-1#153]
Hola

Espero que estén bien. Escribo porque modelando las nuevas reglas del negocio, nos surgió la duda si las sucursales pueden tener delivery propio y además delivery no exclusivo? También, es necesario asignar un despachador a las sucursales cuando estas ya tienen un delivery que cuenta con despachadores? Lo digo por la respuesta a [esta issue](https://github.com/IIC2413/Syllabus-2024-1/issues/139)

Gracias!

**Comment by ypne** [comment]
Hola, solo los restaurantes tienen delivery y estos tienen despachadores. Las sucursales no tienen

**Comment by chichitaocss** [comment]
@ypne en [esta respuesta](https://github.com/IIC2413/Syllabus-2024-1/issues/139#issuecomment-2120560972) se dijo que las sucursales pueden tener despachadores asociados. Quedé confundida. De antemano gracias por la alcaración.

**Comment by ypne** [comment]
No tienen despachadores asociados. Lo que los relaciona es el área de despacho de la sucursal y el despachador
