### ISSUE TITLE
Duda llave primaria y foránea

### ISSUE THREAD

**Issue by Fopazov** [IIC2413/Syllabus-2024-1#154]
Esperando que estén bien, les quería preguntar algo específico. ¿Una llave primaria puede ser foránea a la vez?
Ejemplo: Tienes una tabla con muchos atributos y uno de ellos es identificador, pero este hace referencia a otra tabla. 
Gracias de antemano

**Comment by ypne** [comment]
Es materia de clases

**Comment by Fopazov** [comment]
Gracias

**Comment by JorgeBravo98** [comment]
Hola buenas, tenia la misma duda pero no he encontrado nada en clases al respecto ¿Es posible comentar la idea detrás de eso por acá?

**Comment by ypne** [comment]
CREATE TABLE orders (
  order_id INT NOT NULL,
  customer_id INT NOT NULL,
  order_date DATE NOT NULL,
  total_amount DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (order_id, customer_id),
  FOREIGN KEY (customer_id) REFERENCES customers(customer_id)
);
