### ISSUE TITLE
Tablas con IDs

### ISSUE THREAD

**Issue by endlessloop2** [IIC2413/Syllabus-2024-1#155]
Hola,
Según he visto, varios CSV incluyen `id`. 
En estos casos lo esperado es mantener estos IDs siempre, o en algunos casos se espera que se modifiquen y se dejen, sólo por dar un ejemplo, los platos definidos con 2 keys? (su nombre + el nombre del restaurant al que pertenece _FK_).
Entiendo que ambas opciones funcionan y son válidas, pero por temas de normalización, correctitud y de lo que se espera de nosotros en este trabajo me queda la duda.

Saludos.

**Comment by ypne** [comment]
En algunos casos los id son las PK pero en otras como en las comunas el CUt corresponde a un FK. El PK pueden cambiarlo (consistentemente) por otra surrogate key que les parezca más apropiada. En el Plato el id se usa en pedidos por lo que no es conveniente cambiarlo.
