### ISSUE TITLE
Lo que representa Cldeldes

### ISSUE THREAD

**Issue by Fopazov** [IIC2413/Syllabus-2024-1#157]
No nos queda claro lo que representa este archivo csv de la entrega 2. Manejándolo en python nos dimos cuenta que clientenombre tiene la misma cantidad de valores únicos que la cantidad de filas, pudiendo ser una superllave. Por otro lado, tenemos que hay una menor cantidad de despachadores. Es decir, cada cliente tiene un solo despachador, y un despachador puede atender a varios clientes. ¿Este archivo representa por quienes son "atendidos" los clientes? Es decir, al hacer pedidos, cada cliente solo tiene un despachador asociado?

**Comment by Fopazov** [comment]
Estamos teniendo problemas para definir la llave primaria de la tabla "grande" que representaría a los datos del archivo. ¿Eventualmente se podría repetir valores de "clientenombre"?

**Comment by Fopazov** [comment]
Si la idea es relacionar el archivo cldeldes con el de pedidos, como lo podemos hacer? No hay un conjunto de atributos que permitan hacer esta conexión.

**Comment by linfantek** [comment]
Por nuestra parte también tenemos varias dudas con este csv, identificamos tres subgrupos de información. 
Información sobre cliente (nombre, mail teléfono, clave) que es idéntica a la ya revisada en el csv de clientes
Información sobre la empresa de delivery (nombre, vigente, número, tiempo, precio unitario, mensual y anual)
Información sobre despachador (nombre, teléfono)

Notamos que no hay clientes repetidos, entonces **no entendemos que relación tiene cada cliente con los delivery o los despachadores** que se indican al lado, especialmente dado que si hay repeticiones de despachadores o deliverys. No tiene sentido que esté relacionado con las suscripciones porque hay un csv excucivo para esto. 

Además, este es el único archivo en el que se entrega información sobre los despachadores. **Indica entonces para que deliverys trabaja cada despachador?**

**Comment by ypne** [comment]
ese archivo contiene una relaciuón de cliuentes con delivery y despachadores. sobre el comentario "No tiene sentido que esté relacionado con las suscripciones porque hay un csv excucivo para esto." No aplica que haya otro archivo para ello ya que los archivos son un dataset y no un esquema normalizado por lo que los datos pueden estar distribuidos en varios archivos.

**Comment by Fopazov** [comment]
Claro, ¿pero cuál seria la relación entre clientes y despachadores en ese archivo? ¿Este archivo representa cada delivery mas no pedido?
