### ISSUE TITLE
Cómo conectar Psycopg2 con el servidor?

### ISSUE THREAD

**Issue by GitCross135** [IIC2413/Syllabus-2024-1#159]
Psycopg2 admite los siguientes argumentos al conectar con un servidor:

host, user, password, database, port

Tengo entendido que los datos deberían ser los siguientes según el servidor:

host = "pavlov.ing.puc.cl"
user = "grupo<XX>"
password = "<la contraseña>"
database = "postgres"
port = "22"

Si es que los datos que acabo de mencionar son correctos, por qué no me logra conectar al servidor? Y en caso de que estén incorrectos, cuáles deberían ser?

Gracias de antemano.

**Comment by GitCross135** [comment]
Adjunto el error que me entrega:

![image](https://github.com/IIC2413/Syllabus-2024-1/assets/130419134/ebba948f-5692-4394-bb41-16b3a869435d)

**Comment by ypne** [comment]
Lo que veo es que estas usando flask y dentro psycopg. Por otra parte si los datos de conexión son exactamente los que muestras no están correctos.
host = "pavlov.ing.puc.cl"
user = "grupo"<numero de grupo>
password = "<la contraseña>"
database = "grupo"<numero de grupo>
port = "22"

Por otra parte si estas usando Flask debes usar el puerto 8000+<numero de grupo>
