### ISSUE TITLE
contenidos i1

### ISSUE THREAD

**Issue by santiago3c** [IIC2413/Syllabus-2024-1#16]
Hola a todos, soy un alumno de iic2413. Les quería preguntar si es que en la I1 van a entrar preguntas de SQL mezcladas con python.

**Comment by MartyMolina** [comment]
Exacto. Los contenidos de la i1 corresponden a Álgebra Relacional, Modelo Entidad-Relación y SQL hasta valores nulos. La parte de Python, al venir después de valores nulos, no se evaluará en esta interrogación
