### ISSUE TITLE
Duda rápida Diagrama E/R💫

### ISSUE THREAD

**Issue by SrGarZito** [IIC2413/Syllabus-2024-1#160]
Buenas tardes, realizo esta **Issue** con el fin de preguntar algo:

**¿Se puede realizar un Diagrama E/R **nuevo** a partir de lo que consideremos correcto?**

Porque en el enunciado se dictamina que debemos adaptar el Diagrama E/R de la E1 a la E2, pero aquí ando abarcando el caso de si queremos realizarlo de 0 a partir del E2 + cosas pequeñas que teníamos de la E1, como relaciones y cardinalidades. Ya que algunas cosas quedaron obsoletas y haciéndolo de 0 nos permitió visualizar mejor las cosas.

♠️♥️ **Espero atentamente su respuesta.** ♣️♦️

**Comment by ypne** [comment]
Respuesta rápida: si

**Comment by SrGarZito** [comment]
Excelente, gracias!

**Comment by flcarvallo** [comment]
> Respuesta rápida: si

Será necesario añadir en el informe los cambios que se hicieron en el diagrama con respecto a la entrega 1? o podemos saltarnos esa parte y simplemente describir cómo el diagrama se acopla a los requerimientos en esta etapa del proyecto.
