### ISSUE TITLE
Entrega 2 : Uso de tablas csv  con caracteres especiales

### ISSUE THREAD

**Issue by Osiries1111** [IIC2413/Syllabus-2024-1#161]
Hola!

Tenía una pregunta, pasa que con la nueva subida de las tablas .csv hay muchos datos con caracteres especiales, los cuales no logro encontrar el encoding utilizado en estos, y resultará complejo operar y comparar, con estos datos con estos caracteres.

Entonces quería saber si es que podemos hacer uso para el proyecto, de las tablas que no posean los caracteres especiales.

**Comment by ypne** [comment]
que tablas específicamente ya que para los datos se incluyeron errores de encoding para probar las restricciones de integridad

**Comment by Osiries1111** [comment]
Hablo de las tablas restaurantes2.csv y comuna2.csv

**Comment by GSegov1a** [comment]
Personalmente tengo la misma duda con comunas2.csv
Ya que hay muchos caracteres especiales y al leerlos e insertarlos en la base de datos se reemplazan con �. No se si debo eliminarlos, debo dejarlos así o tengo que hacer algo en especial.

**Comment by ypne** [comment]
si, tal como está en una issue anterior ambas contienen los mismos datos.
