### ISSUE TITLE
[Entrega 2] Consulta entrega final

### ISSUE THREAD

**Issue by plourido** [IIC2413/Syllabus-2024-1#165]
Estimados, junto con saludarlos y desearle un buen dia miercoles, les escribo ya que tengo una duda de como se debe entregar esta entrega, ya se que los archivos deben estar en el servidor, pero mi duda es si el ayudante corrector se va a meter a mi server vía ssh y ahi ejecutar app.py, que monta el servidor flask y crea una conexión en localhost en el puerto 800x, donde x es el grupo.
Muchas gracias 
Quedo atento

**Comment by ypne** [comment]
Ustedes indican en el informe como se ejecuta
