### ISSUE TITLE
Web sin Flask ni Django

### ISSUE THREAD

**Issue by Pablo-Gonzalez-Calderon** [IIC2413/Syllabus-2024-1#166]
Buenas tardes

Se supone que, en teoría, se debería poder elaborar la app sin usar Flask ni Django. Sin embargo, no encuentro forma de poder ejecutar scripts de python sin estas apps al hacer formularios.

Varias webs recomendaban usar cgi u otros módulos, pero siempre al final termino visualizando el archivo *.py en el navegador luego de hacer submit del form:
![image](https://github.com/IIC2413/Syllabus-2024-1/assets/30756770/1edc6918-9755-4e93-ba4c-76e8f44173c6)

Entonces, quería saber si efectivamente existe un modo, porque en verdad ya no entiendo qué puedo hacer

Gracias

**Comment by bea-or** [comment]
Hola, tengo el mismo problema. Siempre me muestra el código de python. Incluso probé con el ejemplo que dan en la ayudantía y me pasa lo mismo. Que otra forma hay de hacer la página web?

**Comment by ypne** [comment]
python3 -m http.server <puerto>

el puerto que deben usar es 8000+numero de grupo

**Comment by bea-or** [comment]
Hola profesor, no entiendo como relacionar el servidor que nos dan con conectarse a ese puerto. Debemos correr esa linea de código en la terminal cuando ya estamos conectados al servidor?

**Comment by ypne** [comment]
A qué te refieres con conectados al servidor? SSH grupoxx@pavlov.ing.puc.cl?
O a conectarse externamente con https://pavlov.ing.puc.cl/home/grupoxx/index.html ?

Esa línea debe estar corriendo cuando hagan las consultas

**Comment by bea-or** [comment]
> A qué te refieres con conectados al servidor? SSH grupoxx@pavlov.ing.puc.cl?
> O a conectarse externamente con https://pavlov.ing.puc.cl/home/grupoxx/index.html ?
> 
> Esa línea debe estar corriendo cuando hagan las consultas

O sea que tenemos que acceder a la página web del servidor y al mismo tiempo en la terminal estar corriendo esa linea?

Y en la terminal, es cuando ya hicimos el login al servidor verdad?

**Comment by bea-or** [comment]
Profesor, acabo de probar lo que señaló más arriba (o por lo menos lo que entendí) e igual me sigue abriendo el archivo como codigo de python.
Esto es lo que hice en el servidor:
<img width="441" alt="Screenshot 2024-05-22 at 22 06 20" src="https://github.com/IIC2413/Syllabus-2024-1/assets/141878469/f1b4f202-a773-4b2b-8142-7af2b034426b">
Y esto es lo que me aparece si ingreso a la web:
![WhatsApp Image 2024-05-22 at 22 08 05](https://github.com/IIC2413/Syllabus-2024-1/assets/141878469/2e250ede-3e01-4fe2-ad0d-747e9466e967)

**Comment by ypne** [comment]
es pavlov.ing.puc.cl no 0.0.0.0

**Comment by bea-or** [comment]
Hola, me meti por http://pavlov.ing.puc.cl:8058 e igual me sigue apareciendo el archivo como código de python.
<img width="639" alt="Screenshot 2024-05-23 at 15 05 19" src="https://github.com/IIC2413/Syllabus-2024-1/assets/141878469/9969cb15-e8c8-40df-967a-aa60692f9a11">
(Eso es un archivo de prueba que hice)

**Comment by calvarezl-cl** [comment]
Por favor me pueden compartir el código, para poder entender lo que están haciendo y quieren que se vea como un sitio web.

**Comment by bea-or** [comment]
> Por favor me pueden compartir el código, para poder entender lo que están haciendo y quieren que se vea como un sitio web.

Hola, por donde te puedo mandar el código?

**Comment by calvarezl-cl** [comment]
Finalmente pude ejecutar un archivo python como script siguiendo los pasos encontrados en google.

1. Deben generar un archivo python con la estructura del archivo ejemplo.py
[ejemplo.zip](https://github.com/IIC2413/Syllabus-2024-1/files/15422803/ejemplo.zip)

2. Dentro de la carpeta donde está el sitio web, deben crear una carpeta llamada cgi-bin
3. En la carpeta cgi-bin deben copiar el archivo ejemplo.py
4. Deben otorgarle permisos de ejecución al archivo ejemplo.py (chmod a+x ejemplo.py)
5. El servidor se debe iniciar con el siguiente comando python3 -m http.server --cgi 8XXX
6. Luego visitar la url del sitio http://pavlov.ing.puc.cl:8XXX/

![ejemplo](https://github.com/IIC2413/Syllabus-2024-1/assets/55099390/8f533697-c355-465b-90c5-3ec257b0f830)

**Comment by bea-or** [comment]
Hola, segui tus pasos y todavía no me resulta. 

> El servidor se debe iniciar con el siguiente comando python3 -m http.server --cgi 8XXX

Eso hay que hacerlo en la terminal una vez que ya ingresamos al servidor? Y en que carpeta?

**Comment by bea-or** [comment]
Probe corriendo `python3 -m http.server --cgi 8058` en Sites, cgi-bin y en la carpeta que contiene todo y en todos me sigue mostrando el código.
<img width="619" alt="Screenshot 2024-05-23 at 17 48 47" src="https://github.com/IIC2413/Syllabus-2024-1/assets/141878469/679ff8f7-a5c1-4106-97ae-d0b2756744a0">

**Comment by calvarezl-cl** [comment]
> Hola, segui tus pasos y todavía no me resulta.
> 
> > El servidor se debe iniciar con el siguiente comando python3 -m http.server --cgi 8XXX
> 
> Eso hay que hacerlo en la terminal una vez que ya ingresamos al servidor? Y en que carpeta?

Tienes que hacerlo en el terminal, en la carpeta superior a la carpeta cgi-bin (paso 3)

**Comment by calvarezl-cl** [comment]
> Probe corriendo `python3 -m http.server --cgi 8058` en Sites, cgi-bin y en la carpeta que contiene todo y en todos me sigue mostrando el código. <img alt="Screenshot 2024-05-23 at 17 48 47" width="619" src="https://private-user-images.githubusercontent.com/141878469/333352939-679ff8f7-a5c1-4106-97ae-d0b2756744a0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1MDU0OTEsIm5iZiI6MTcxNjUwNTE5MSwicGF0aCI6Ii8xNDE4Nzg0NjkvMzMzMzUyOTM5LTY3OWZmOGY3LWE1YzEtNDEwNi05N2FlLWQwYjI3NTY3NDRhMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyM1QyMjU5NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZmZjM2Q1ZjRhMDJhZmFmN2FhYTc4Mjg1MDc5YjlmMDZmYjNkOWZmZTA2ZTEwYWE1MTI0YmQ4M2JlMWU3MmEwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Vu9mioKW9Bv1HBP9eSgpYrnuFdpKx-jL-7_hpKQ0QSE">

En la imagen enviada, en la url no aparece la carpeta cgi-bin. Compara con la imagen enviada mostrando que se ejecutó correctamente.

**Comment by Ariimaw** [comment]
@calvarezl-cl Entonces nuestro archivo con la estructura de ejemplo.py es el mismo archivo que debe recibir los datos del form de nuestra pagina html, verdad? No puede ser ningun otro en ninguna otra carpeta mas que cgi-bin?

**Comment by bea-or** [comment]
> > Probe corriendo `python3 -m http.server --cgi 8058` en Sites, cgi-bin y en la carpeta que contiene todo y en todos me sigue mostrando el código. <img alt="Screenshot 2024-05-23 at 17 48 47" width="619" src="https://private-user-images.githubusercontent.com/141878469/333352939-679ff8f7-a5c1-4106-97ae-d0b2756744a0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1MDU0OTEsIm5iZiI6MTcxNjUwNTE5MSwicGF0aCI6Ii8xNDE4Nzg0NjkvMzMzMzUyOTM5LTY3OWZmOGY3LWE1YzEtNDEwNi05N2FlLWQwYjI3NTY3NDRhMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyM1QyMjU5NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZmZjM2Q1ZjRhMDJhZmFmN2FhYTc4Mjg1MDc5YjlmMDZmYjNkOWZmZTA2ZTEwYWE1MTI0YmQ4M2JlMWU3MmEwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Vu9mioKW9Bv1HBP9eSgpYrnuFdpKx-jL-7_hpKQ0QSE">
> 
> En la imagen enviada, en la url no aparece la carpeta cgi-bin. Compara con la imagen enviada mostrando que se ejecutó correctamente.

<img width="727" alt="Screenshot 2024-05-23 at 19 49 59" src="https://github.com/IIC2413/Syllabus-2024-1/assets/141878469/e8d6ab60-cb8a-4553-9917-a11a863fb2d8">
Es que si lo hacía para que saliera el cgi-bin antes, me tiraba este error y no me dejaba entrar a los archivos. Y si es que buscaba el archivo haciendo /ejemplo.py me decia que no existía.

**Comment by calvarezl-cl** [comment]
> > > Probe corriendo `python3 -m http.server --cgi 8058` en Sites, cgi-bin y en la carpeta que contiene todo y en todos me sigue mostrando el código. <img alt="Screenshot 2024-05-23 at 17 48 47" width="619" src="https://private-user-images.githubusercontent.com/141878469/333352939-679ff8f7-a5c1-4106-97ae-d0b2756744a0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1MDU0OTEsIm5iZiI6MTcxNjUwNTE5MSwicGF0aCI6Ii8xNDE4Nzg0NjkvMzMzMzUyOTM5LTY3OWZmOGY3LWE1YzEtNDEwNi05N2FlLWQwYjI3NTY3NDRhMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyM1QyMjU5NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZmZjM2Q1ZjRhMDJhZmFmN2FhYTc4Mjg1MDc5YjlmMDZmYjNkOWZmZTA2ZTEwYWE1MTI0YmQ4M2JlMWU3MmEwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Vu9mioKW9Bv1HBP9eSgpYrnuFdpKx-jL-7_hpKQ0QSE">
> > 
> > 
> > En la imagen enviada, en la url no aparece la carpeta cgi-bin. Compara con la imagen enviada mostrando que se ejecutó correctamente.
> 
> <img alt="Screenshot 2024-05-23 at 19 49 59" width="727" src="https://private-user-images.githubusercontent.com/141878469/333372278-e8d6ab60-cb8a-4553-9917-a11a863fb2d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1MTA3MjksIm5iZiI6MTcxNjUxMDQyOSwicGF0aCI6Ii8xNDE4Nzg0NjkvMzMzMzcyMjc4LWU4ZDZhYjYwLWNiOGEtNDU1My05OTE3LWExMWE4NjNmYjJkOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNFQwMDI3MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YmJhOGMxODk4N2I3MjY4NDdkYTRhYzBkZWU2ZjUwYjM3YzU5ODdjNWQzZDFmZWE4MjJjYzA2NDhhN2VlZTc4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.zwOl0R_VPamkB3t0jndNQtxC9w5mIS3HQgdTh-T1YtQ"> Es que si lo hacía para que saliera el cgi-bin antes, me tiraba este error y no me dejaba entrar a los archivos. Y si es que buscaba el archivo haciendo /ejemplo.py me decia que no existía.

No puedes navegar por la carpeta cgi-bin y ver los archivos que están ahí. En la URL debe ingresarse
 la ruta completa, incluyendo el archivo http://pavlov.ing.puc.cl:8058/cgi-bin/ejemplo.py

**Comment by bea-or** [comment]
Ahi me funcionó, gracias! :)
Es posible que habiliten que reconozca los archivos .css?

**Comment by ypne** [comment]
installed cssutils-2.11.0
