### ISSUE TITLE
Error Eduroam

### ISSUE THREAD

**Issue by Curi2164** [IIC2413/Syllabus-2024-1#168]
Tal y como le comenté en clases, tengo un extraño error en donde al usar Flask para ver mi aplicación, esta no funciona al querer conectarla a través de Eduroam, pero usando mi conexión de internet personal si se puede lograr ver. Probablemente Eduroam tengo algún problema al querer usar el puerto que me tocó (port 8105)
![Captura de pantalla 2024-05-22 150051](https://github.com/IIC2413/Syllabus-2024-1/assets/106034041/feeae7a0-a7aa-41ba-9569-f1a8c2354a2a)

**Comment by ypne** [comment]
se solicita a la administración central abrir los puertos
