### ISSUE TITLE
Dirección de correo y telefono único

### ISSUE THREAD

**Issue by alejandrosaba** [IIC2413/Syllabus-2024-1#169]
Hola que tal? Una consulta, en un punto de las reglas del negocio dice "El Cliente tiene una dirección de correo única y un teléfono único pero varias direcciones". Me parece intuitivo pensar que pasa lo mismo para los los despachadores pero prefiero asegurarme de que esto si sucede. 

Gracias

**Comment by ypne** [comment]
puedes asumirlo
