### ISSUE TITLE
Duda Contenidos Llave compuesta

### ISSUE THREAD

**Issue by plourido** [IIC2413/Syllabus-2024-1#17]
Holaaa que tallll? Espero que se encuentren muy bien. Les escribo ya que no tengo claro cuando me solicitan entidades con llaves compuestas? Segun lo que investigué una llave compuesta es un conjunto ordenado de dos o más columnas de la misma tabla. El orden de las columnas no está restringido por su orden real dentro de la tabla. Esto quiere decir que una entidad es compuesta cuando tiene en el conjunto de llaves primarias mas de un elemento?
Muchas gracias 
:)

**Comment by elbosco** [comment]
Hola,
Sí, es exactamente eso. Un ejemplo de entidades que usan llaves compuestas son las entidades débiles. En general, también usamos llave compuesta cuando con una sola columna no basta para hacer única y diferente a las filas. Es decir, si tenemos una tabla de autos disponible en una tienda con columnas: (marca_auto, modelo, año, color, stock), queremos hacer que la llave primaria sea el conjunto de columnas (marca_auto, modelo, año), ya que, si por ejemplo, hacemos a marca_auto solamente llave primaria, entonces solo va a poder haber una fila por marca de auto, y lo mismo si hacemos solamente (marca_auto, modelo) llave primaria, entonces solo va a poder haber una fila por modelo de una marca determinada de auto.
Saludos,

**Comment by elbosco** [comment]
También, te puede ayudar ver la issue #13.
