### ISSUE TITLE
Maximo 2 pedidos del mismo Restaurant

### ISSUE THREAD

**Issue by alejandrosaba** [IIC2413/Syllabus-2024-1#170]
Hola que tal? Queria preguntar si en las reglas del negocio, el punto que dice "Cada Despachador solo puede atender máximo 2 pedidos del mismo Restaurant a la misma comuna." Se tiene que reflejar en el esquema, diagrama de E/R o dominio, porque no sabemos como hacerlo. Entendemos que si se puede hacer en la parte del SQL. 

Gracias.

**Comment by ypne** [comment]
no es necesario hacerlo en esta ocasión
