### ISSUE TITLE
Valor total en consulta 3

### ISSUE THREAD

**Issue by c4ebt** [IIC2413/Syllabus-2024-1#171]
La consulta 3 pide "Muestre todos pedidos concretados y cancelados y el valor total de ellos".
Este valor total hace referencia a la suma de los precios de platos, ¿cierto?
En otro caso, si hubiera que incorporar los costos de despacho, sería imposible determinar como incorporar los precios de delivery con suscripción, ya que no se sabe cuantos pedidos hace cada usuario en un periodo de tiempo no dado.

**Comment by ypne** [comment]
debe considerar los valores de despacho

**Comment by c4ebt** [comment]
Pero se considera solo si no tiene suscripción, cierto?

Porque si tiene suscripción, el valor de despacho es 0, y el último pago de la suscripción tiene un monto dado que puede ser con ciclo anual o mensual. Pero como incorporamos ese valor en el costo total de un pedido si no sabemos cuantos pedidos se han hecho o se harán en el periodo de la suscripción?

**Comment by ypne** [comment]
si no tiene está claro, se suma por cada pedido cierto?
Si tiene suscripción vigente se asigna una vez por ciclo o puedes agregarle 1/numero de pedidos en el ciclo
El caso mixto no lo consideren (o sea si la suscripción está no vigente hasta un plazo y despues sin suscripción)

**Comment by c4ebt** [comment]
Cuando dice "el valor total de ellos", se refiere a sumar el valor de todos los pedidos, y retornar un solo valor?
En ese caso si se puede hacer la suma de todas las suscripciones sin mucho problema. Quizá entendí mal, pero pensaba que con "valor total de ellos" se refería al valor de cada pedido por separado.
