### ISSUE TITLE
Duda sobre tablas

### ISSUE THREAD

**Issue by masoto22** [IIC2413/Syllabus-2024-1#172]
Hola

Espero que estén bien, escribo porque me surgió una duda con la instrucción 2 de la tarea. Dice "traspasar el modelo Entidad/ Relación al modelo relacional especificando tanto el esquema, el tipo y dominio de cada atributo, incluyendo llaves primarias y foráneas así como restricciones de integridad". Es necesario hacer esto en un programa como dbdiagram por ejemplo? O basta con hacerlo con texto de la forma NombreTabla(atributo1: tipo, atributo2: tipo, etc.) 

Gracias

**Comment by ypne** [comment]
sono se especifica en el informe
