### ISSUE TITLE
Duda encriptación de claves

### ISSUE THREAD

**Issue by sebamusea** [IIC2413/Syllabus-2024-1#173]
Hola, tengo una duda con la encriptación mencionada en el punto 4 de la Descripción del trabajo a entregar. A que claves se refiere? A las de los clientes.csv? Además, nosotros decidimos como encriptar la clave o hay alguna forma predeterminada de hacerlo?
Muchas gracias

**Comment by ypne** [comment]
a la clave de los clientes y si ustedes especifican como encriptar
