### ISSUE TITLE
Problemas con clave Postgresql

### ISSUE THREAD

**Issue by andry-19** [IIC2413/Syllabus-2024-1#174]
Hola! Con mi grupo llevamos atrapadas en la preparación del servidor desde que se abrió la entrega. Intentando seguir los pasos de la ayudantía quedamos atascadas en el ingreso a Postgresql. Al momento de hacer el comando 'psql', se nos solicita la clave y al ingresar la que debería ser ('grupoXX', con XX siendo el número de grupo) nos dice que la contraseña es incorrecta.

¿Que podemos hacer? La verdad ya no sabemos a quien pedirle ayuda, nos sentimos super abandonadas.

**Comment by ypne** [comment]
grupo?

**Comment by andry-19** [comment]
Grupo 5 🥺

**Comment by ypne** [comment]
Está listo prueba por favor

**Comment by andry-19** [comment]
Muchisimas gracias! Nos salvaste

**Comment by ypne** [comment]
Tienen plazo hasta el martes para entregar

**Comment by Amandaasg** [comment]
@ypne disculpe, pero seguimos sin poder conectarnos a la base de datos, solo se lo resolvió al grupo 6 en la otra issue que cerró, es el mismo pantallazo pero se lo mando de todos modos: 
![imagen_2024-05-24_173116581](https://github.com/IIC2413/Syllabus-2024-1/assets/103213615/f22654b7-2c64-463e-a049-ce8dd3db3e42)

**Comment by ypne** [comment]
ya estan conectados, ese es el prompt
