### ISSUE TITLE
Sobre el tratamiento de restricciones

### ISSUE THREAD

**Issue by dvillas28** [IIC2413/Syllabus-2024-1#176]
Cuando se insertan datos y se encuentran violaciones de integridad, y elegimos (por ejemplo) agrandar un campo, ¿se supone que el cargador debería cambiar la restricción y recargar los datos nuevamente, o debemos cambiar la restricción manualmente, y correr el cargador nuevamente?

Es una duda que no me quedo clara del anuncio de esta mañana

Saludos 🤠

**Comment by ypne** [comment]
si van a cambiar el campo debiera ser suficiente con un ALTER TABLE y no cambiar el cargador
