### ISSUE TITLE
Lectura de Datos Modificada

### ISSUE THREAD

**Issue by DonMarto** [IIC2413/Syllabus-2024-1#177]
Hola, en la lectura de los datos del archivo pedidos.csv tenemos problemas con el atributo platos. Esto es porque, según entendemos, corresponde a los id de los platos correspondientes al pedido. Sin embargo, estos serían subidos como un string, y luego no sería trivial, a partir de ellos, identificar los id de manera particular. Para ello, ¿sería posible utilizar métodos como str.split() de python, para separar los platos para cada pedido? 

Similar al caso anterior, para el caso de platos.csv, cuando los ingredientes tienen un paréntesis (e.g. salsas o condimentos), estos están separados por coma, por lo que complica la carga de los datos. Para ello, tenemos dos consultas: ¿sería válido definir ingrediente como su propia entidad, asignándole así una llave propia? Y, ¿podríamos usar métodos para identificar los paréntesis (e.g. str.split()) para cargar los datos de manera diferente?

Gracias de antemano :D

**Comment by ypne** [comment]
¿sería posible utilizar métodos como str.split() de python, para separar los platos para cada pedido?
R: están proponiendo crear la entidad carrito de compras con id pedido, plato? si es así si se puede
¿podríamos usar métodos para identificar los paréntesis (e.g. str.split()) para cargar los datos de manera diferente?
R: están proponiendo crear la entidad ingredientes con id plato, ingrediente? si es así si se puede. 
con respecto a str.split no me pronuncio ya que es muy específico, sin embargo si esto les entrega el resultado que necesitan está OK

**Comment by DonMarto** [comment]
Perfecto, muchas gracias profesor!
