### ISSUE TITLE
Duda consultas monótonas

### ISSUE THREAD

**Issue by Pablo-Gonzalez-Calderon** [IIC2413/Syllabus-2024-1#18]
Buenas noches 🍀

Estaba viendo la materia de Álgebra Relacional, y leyendo la información sobre Consultas Monótonas, aún no logro comprender a cabalidad a qué corresponden. No sé si podrían dar algún ejemplo o definición más "informal", porque en el PPT salía bastante "formal" su definición

**Comment by Amegonzale** [comment]
Buenas noches!

Una definicion más informal de consulta monótona seria pensar en que: Si yo añado mas tuplas, el resultado de mi consulta va a quedarse igual o va a aumentar, jamas disminuir. 

Por ejemplo, imagina que yo tengo una tabla con nombres de gatitos y los colores que tienen. Si yo añado uno nuevo llamado pablito de color narajo, al seleccionar los gatitos de color naranjo entonces obtendre a los que ya tenia + pablito. Por ende el operador select monotono. 

Espero que haya quedado claro n.n

**Comment by Pablo-Gonzalez-Calderon** [comment]
Siiii ✨

Ahí me quedó más claro. Muchas gracias Ame 🫶
