### ISSUE TITLE
Hora consultas

### ISSUE THREAD

**Issue by linfantek** [IIC2413/Syllabus-2024-1#180]
Hola! Leímos en el anuncio que se pueden realizar consultas con el profesor Eduardo Bustos durante hoy y mañana. Podríamos reunirnos el viernes a las 14:00? 
Muchas gracias!

**Comment by ypne** [comment]
envíenme sus emails y los agendo

**Comment by linfantek** [comment]
perfecto gracias!
linfantek@uc.cl
jos.infante@uc.cl
mdegoyenechet@uc.cl

**Comment by ypne** [comment]
agendado
