### ISSUE TITLE
Descripción Platos

### ISSUE THREAD

**Issue by GitCross135** [IIC2413/Syllabus-2024-1#181]
En el enunciado dice lo siguiente:

![image](https://github.com/IIC2413/Syllabus-2024-1/assets/130419134/37a63e72-a339-4357-bdd8-68763e44ed20)

Sin embargo, en absolutamente todos los platos, tienen descripciones mayores a 40 caracteres incluso. Trabajamos Descripción Plato como TEXT NOT NULL mejor en vez de VARCHAR(30) NOT NULL?

**Comment by ypne** [comment]
esta issue les va a servir https://github.com/IIC2413/Syllabus-2024-1/issues/124
igual solución
