### ISSUE TITLE
Consultas vía zoom

### ISSUE THREAD

**Issue by Fopazov** [IIC2413/Syllabus-2024-1#183]
Esperando que estén bien, como grupo nos gustaría coordinar una reunión de zoom con el profe Eduardo Bustos para hoy.

**Comment by ypne** [comment]
envíen los mail y propuesta de hora

**Comment by antoniasoto** [comment]
Hola a nosotros como grupo también nos gustaría para mañana al rededor de las 12pm. Los mails son Antonia.soto@uc.cl, gustavo.morn@uc.cl y biolcay@uc.cl

**Comment by AlvaroSotomayor** [comment]
Hola a nosotros como grupo también nos gustaría para mañana de ser posible 14:00. Los mails son [alvaro.sotomayor@uc.cl](mailto:alvaro.sotomayor@uc.cl), [fernando.fajardo@uc.cl](mailto:fernando.fajardo@uc.cl) y [p.j.altamirano.p@uc.cl](mailto:p.j.altamirano.p@uc.cl)

**Comment by ypne** [comment]
tengo disponibilidad a ls 13:00 y a las 15:45

**Comment by antoniasoto** [comment]
Hola, nos interesa a las 13:00


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by mramos15** [comment]
Hola, como grupo nos gustaria tener una reunion a las 15:45 mañana. mramosw@uc.cl, clemente.rabat@uc.cl, felipe.arnolds@uc.cl

**Comment by AlvaroSotomayor** [comment]
Hola a nosotros como grupo también nos gustaría para mañana de ser posible tener una reunión de consultas despues del grupo de las 15:45. Los mails son [alvaro.sotomayor@uc.cl](mailto:alvaro.sotomayor@uc.cl), [fernando.fajardo@uc.cl](mailto:fernando.fajardo@uc.cl) y [p.j.altamirano.p@uc.cl](mailto:p.j.altamirano.p@uc.cl)

**Comment by TMaiza** [comment]
Hola! Como grupo también nos gustaría para mañana, a ma hora que sea posible.
Somos el grupo 39.
Tmaiza@uc.cl
Tlehuede@uc.cl
Cmacevedo1@uc.cl

**Comment by gasparbenavente2** [comment]
Hola! Como grupo también nos gustaría una reunión mañana, cualquier horario. Gracias!
gaspar.benavente@uc.cl
martingatica@uc.cl
dgarciadelah@uc.cl

**Comment by AlinnaVidal** [comment]
Hola, nos gustaría tener una reunión hoy si es posible a las 3/4 pm
alinna.vidal@uc.cl
fschiappacasse@uc.cl
javier.verastegui@uc.cl
