### ISSUE TITLE
Dudas E2: Despachadores y Delivery

### ISSUE THREAD

**Issue by Washaaaan** [IIC2413/Syllabus-2024-1#184]
Buenas! Me surgieron unas dudas respecto a los despachadores:
1. ¿La misma entidad despachadores hecha en la entrega anterior es la que entrega los pedidos del delivery propio?
2. en caso de que si, la cardinalidad de despachador a servicio despachador debe cambiar o no? digo esto ya que el despachador debe pertenecer mínimo a un servicio despachador, y si ahora forma parte de delivery, significa que no es parte del servicio despachador supongo yo.
3. Al relacionar despachador con la entidad Delivery, significa que deberíamos quitar la restricción de que despachador debe ser parte si o si de al menos un servicio despachador ya que ahora podría formar parte de delivery verdad?
4. Por último, cómo funcionan las áreas de despacho? se menciona muy poco en el pdf y no me queda claro.

**Comment by ypne** [comment]
1.- ¿La misma entidad despachadores hecha en la entrega anterior es la que entrega los pedidos del delivery propio?
R: si, está en el enunciado
2.- P: que diferencia haces entre servicio y despachador?
3.- P: idem anterior
4.- Cuando se hace un despacho se deberán elegir despachadores del área

**Comment by Washaaaan** [comment]
> 1.- ¿La misma entidad despachadores hecha en la entrega anterior es la que entrega los pedidos del delivery propio? R: si, está en el enunciado 2.- P: que diferencia haces entre servicio y despachador? 3.- P: idem anterior 4.- Cuando se hace un despacho se deberán elegir despachadores del área

2 y 3: El servicio despachador forma parte de la empresa despachadora y posee empleados despachadores para entregar los pedidos,

**Comment by ypne** [comment]
cual es la diferencia entre servicio despachador y despachador?

**Comment by Washaaaan** [comment]
> cual es la diferencia entre servicio despachador y despachador?

La diferencia es que claro, el servicio despachador forma parte de la empresa despachadora y envía a despachadores de la empresa a entregar los pedidos, en cambio, despachador es solo un trabajador, que según estaba pensando, ahora no necesariamente tiene que formar parte de esa empresa. 
Todo esto suponiendo que estamos haciendo cambios al diagrama de la entrega anterior y manteniendo entidades tales como Empresa despachadora y Servicio despachador.

**Comment by ypne** [comment]
veamoslo en un zoom, envíenme los correos y hora

**Comment by Washaaaan** [comment]
Muchas gracias!! ¿Puede ser a las 17:00? mi correo es ltpalangornall@gmail.com y el uc es argornall@uc.cl

**Comment by ypne** [comment]
hola, hoy no puedo despues de las 17, mañana am?

**Comment by Washaaaan** [comment]
Mañana a las 11 am podría? :3

**Comment by ypne** [comment]
agendado
