### ISSUE TITLE
Consulta zoom 

### ISSUE THREAD

**Issue by IsidoraGuinez** [IIC2413/Syllabus-2024-1#185]
Hola , con mi grupo nos gustaría agendar una hora con el profesor Eduardo para el día de hoy tipo 16:00 o 17:00 , o mañana tipo 9:00 o 10:00
Correos :
isiguinez@uc.cl
amalia.fritz@uc.cl
emilio.fuenzalida@uc.cl

**Comment by ypne** [comment]
agendado
