### ISSUE TITLE
Consulta zoom

### ISSUE THREAD

**Issue by elruko** [IIC2413/Syllabus-2024-1#189]
Quisiera agendar una reunion para hoydia antes de las 17:00 porfavor
irarrazavalp@uc.cl

**Comment by elruko** [comment]
si ya es muy tarde para hoy, entonces mañana a las 9:00

**Comment by ypne** [comment]
mañana a las 9 agendado

**Comment by elruko** [comment]
Buenisimo

Obtener Outlook para iOS<https://aka.ms/o0ukef>
________________________________
De: Eduardo. Bustos ***@***.***>
Enviado: Thursday, May 23, 2024 5:16:18 PM
Para: IIC2413/Syllabus-2024-1 ***@***.***>
Cc: José Pedro Irarrázaval Greene ***@***.***>; Author ***@***.***>
Asunto: Re: [IIC2413/Syllabus-2024-1] Consulta zoom (Issue #189)


mañana a las 9 agendado
