### ISSUE TITLE
Acciones administrador y estado del pedido

### ISSUE THREAD

**Issue by bea-or** [IIC2413/Syllabus-2024-1#19]
Hola! 

Tengo una pregunta. Cuando dice que el estado del pedido solo tiene 4 estados posibles (pendiente, en preparación, entregado a despachador, entregado a cliente), eso me afecta de alguna manera en como debo hacer mi modelo E-R? Lo mismo con los administradores, afecta en algo que el administrador pueda agregar, eliminar, modificar y ajustar sus parámetros? Cuando digo "afecta," me refiero a si cambia en algo el diagrama E-R.

También, en las instrucciones habla de un esquema con la base de datos con sus relaciones. Eso se refiere al modelo relacional, correcto?

Gracias!

**Comment by isufan** [comment]
Hola! Respecto a la primera pregunta, ten presente que los diagramas E-R incluyen los atributos de cada entidad, pero los posibles valores que pueden tener los atributos son irrelevantes. Respecto al admin, queda totalmente a criterio tuyo, depende de cómo diseñes tu modelo. 

Y ojo que el diagrama E-R y el esquema relacional son cosas diferentes. Primero debes crear el diagrama y a partir de eso creas el esquema incluyendo las relaciones y llaves, un procedimiento muy similar al que hicieron para el taller evaluado 1.

Saludos!
