### ISSUE TITLE
Ejecución del programa

### ISSUE THREAD

**Issue by AleSierra26** [IIC2413/Syllabus-2024-1#190]
Hola, una consulta. Cual es la manera correcta para acceder a nuestro programa? es decir, como se va a ejecutar nuestro programa? Accediendo directamente al link (https://pavlov.ing.puc.cl/home/grupo28/index.html)? Desde la terminal? Corriendo el archivo.py? No entiendo muy bien como se ejecuta😔

**Comment by ypne** [comment]
Deben generar un archivo python con la estructura del archivo ejemplo.py
[ejemplo.zip](https://github.com/IIC2413/Syllabus-2024-1/files/15422803/ejemplo.zip)

Dentro de la carpeta donde está el sitio web, deben crear una carpeta llamada cgi-bin

En la carpeta cgi-bin deben copiar el archivo ejemplo.py

Deben otorgarle permisos de ejecución al archivo ejemplo.py (chmod a+x ejemplo.py)

El servidor se debe iniciar con el siguiente comando python3 -m http.server --cgi 8XXX

Luego visitar la url del sitio http://pavlov.ing.puc.cl:8XXX/

**Comment by GithubSPerez** [comment]
Ahora que el periodo de las issues se acabaron y puedo hacer una pregunta inconsecuente ¿en que parte salía esta información? osea no lo encuentro en niuna otra parte además de esta issue y no habríamos podido avanzar de no ser por esto
