### ISSUE TITLE
Máximo de platos

### ISSUE THREAD

**Issue by Monti7475** [IIC2413/Syllabus-2024-1#192]
Existe algún máximo de platos para la columna de plato en pedidos.csv?
Es con el fin de separarlo en columnas en una nueva entidad, pero para poder separarlo tendría que tener un tope (De este modo en caso de tener menos, las columnas vacias quedarian como NULL y no pasaría que me falten)

**Comment by ypne** [comment]
no, ¿qué se les ocurre hacer?
lo que si tiene limite es el largo del string que leen del archivo

**Comment by Monti7475** [comment]
Como decia, era para hacer una nueva entidad que contenga los platos de un pedido en columnas individuales. Si no hay máximo tendremos que ver otra forma de abordar pedidos
