### ISSUE TITLE
Problema con postgres

### ISSUE THREAD

**Issue by PelayoF** [IIC2413/Syllabus-2024-1#193]
Al intentar crear una base de datos me pide una contraseña, uso la contraseña que puse cuando instalé postgres y me dice que no es correcta. ¿Alguien sabe que contraseña debería usar ahí? Abro la terminal y uso este codigo:  createdb <nombre base datos>

**Comment by ypne** [comment]
que grupo?
a que te refieres con "cuando instalé postgres "?
me puedes enviar un screen shot?

**Comment by PelayoF** [comment]
Estoy con otro problema ahora, perdón que te cambie el tema.
Donde puedo ver mi base de datos "grupo111e2"?

**Comment by PelayoF** [comment]
Me conecto a la base de datos con python y cree una tabla, pero ahora no se como visualizarla, ns si se puede o solo hay que confiar que esta bien.
Y tampoco se que debo subir al servidor, ¿el archivo python?

**Comment by PelayoF** [comment]
Soy del grupo111
![image](https://github.com/IIC2413/Syllabus-2024-1/assets/110933868/64900d98-6a1c-45cc-813b-dd013f18bf39)

Cuando sigo el ejemplo Probando PostgreSQL de la wiki no puedo correr el codigo createdb exampleDB

**Comment by ypne** [comment]
estás trabajando en windows, no en el server. Ahí no puedo ayudarlos

**Comment by PelayoF** [comment]
Y como trabajo en el server

**Comment by ypne** [comment]
como se indicó en los avisos y en la ayudantía. La entrega se evaluará en el server
