### ISSUE TITLE
emails cliente

### ISSUE THREAD

**Issue by Liper1** [IIC2413/Syllabus-2024-1#195]
En la tabla suscripciones hay registros con emails que actúan como llaves foráneas a la columna email de la tabla clientes, pero algunos de estos emails no están presentes en la tabla clientes. ¿Puedo suponer que estas filas deben ser ignoradas debido a que están usando un email que no existe en la tabla clientes?
![image](https://github.com/IIC2413/Syllabus-2024-1/assets/130397899/b24d058d-112c-4917-9f77-343bb8522b4d)

**Comment by ypne** [comment]
no

**Comment by Liper1** [comment]
¿Qué debería hacer? para evitar ese error borro esto  FOREIGN KEY(email) REFERENCES clientes(email) al crear la tabla?

**Comment by ypne** [comment]
Se aseguraron que tienen a todos los clientes cargados? hay clientes en mas de un archivo.
Si esto es así, como el cliente tiene email único hay una falta. Revisen las  clases donde vimos este tema (llaves) para tomar las acciones correspondientes.
