### ISSUE TITLE
Consultas via zoom

### ISSUE THREAD

**Issue by juanivegam** [IIC2413/Syllabus-2024-1#196]
Hola, soy del grupo 107. Quería preguntar si es que mañana sería posible tener una reunión para resolver dudas, en algún momento entre la 1 y las 4. Mi mail es jvegamaack@uc.cl

**Comment by ypne** [comment]
en ese horario ya no tengo disponibilidad, puede ser a las 17:15

**Comment by juanivegam** [comment]
Hola, si ningun problema. Muchas gracias!
________________________________
De: Eduardo. Bustos ***@***.***>
Enviado: jueves, 23 de mayo de 2024 21:24
Para: IIC2413/Syllabus-2024-1 ***@***.***>
Cc: Juan Ignacio Vega Maack ***@***.***>; Author ***@***.***>
Asunto: Re: [IIC2413/Syllabus-2024-1] Consultas via zoom (Issue #196)


en ese horario ya no tengo disponibilidad, puede ser a las 17:15
