### ISSUE TITLE
Lista de ingredientes

### ISSUE THREAD

**Issue by Monti7475** [IIC2413/Syllabus-2024-1#198]
La lista de ingredientes de Platos.csv, se considera una tupla? 
Dicho de otra manera, tendría que editarlo para mantener el 1NF?

**Comment by ypne** [comment]
Buena pregunta!
No se considera una tupla, puedes descomponerlo o no ya que no se opera con ella en JOIN, solo se consulta parcialmente

**Comment by Monti7475** [comment]
graciass
