### ISSUE TITLE
Duda de materia de álgebra relacional

### ISSUE THREAD

**Issue by gaspar-mr05** [IIC2413/Syllabus-2024-1#20]
Hola! Haciendo ejercicios de ayudantías de años anteriores sobre consultas con álgebra relaciónal, me di cuenta que la mayoría de veces lo que hacía yo no era igual a lo de la pauta, sin embargo yo creo que ambas formas de hacer las consultas están bien. Ante eso me surgió una duda sobre qué consultas son equivalentes y eso es lo que quiero preguntar, adjunto foto con 6 consultas que según yo hacen lo mismo. Quiero corroborarlo

![image](https://github.com/IIC2413/Syllabus-2024-1/assets/141950250/50cd8e94-30ca-4937-a73b-d260478a09c6)

**Comment by MartyMolina** [comment]
Hola, en álgebra relacional puede haber más de una manera de hacer las cosas. En los casos que mencionaste, el primero y el tercero son similares y corresponden a la igualdad, ya que realizar dos selecciones (σ) al mismo tiempo es tomar las tuplas que cumplen ambas condiciones simultáneamente, lo cual es equivalente a realizar una selección y luego otra. En el caso dos, es diferente colocar una condición para el Join que para la selección con sigma, ya que con sigma se realiza una operación de selección que actúa sobre una sola relación, mientras que la operación de Join combina dos relaciones basándose en una condición de igualdad entre columnas, y esta condición involucra columnas de ambas relaciones. Por lo tanto, la restricción de un Join no es lo mismo que una operación de selección.

**Comment by elbosco** [comment]
Hola, si es igual, pero como recomendación deberías poner siempre la condición del filtro del JOIN (que siempre suele ser una igualdad de ids, ejemplo R1.id=R2.id) al interior y luego poner una condición de selección afuera (ejemplo R1.id = 1), para un mejor orden.
Saludos,

**Comment by gaspar-mr05** [comment]
si si entiendo que no es la mismo hacer seleccion que hacer join. Pero en el caso de la segunda consulta que pasa si por ejemplo el producto cruz de R y A tiene las columnas a1 (de R) y a2 (de A), y la condicion 2 involucra a ambas columnas, no sería lo mismo que colocar esa misma condicion en un join de R y A? En verdad en las 6 consultas que escribi estoy refiriendome al caso el cual las condiciones involucran a columnas de ambas relaciones, no de una en especifico, porque entiendo que si la condicion involucra a la columna de una sola relacion, entonces no puedo ocupar el join.
