### ISSUE TITLE
Limite de caracteres de la lista de ingredientes

### ISSUE THREAD

**Issue by GithubSPerez** [IIC2413/Syllabus-2024-1#200]
Según el enunciado, la lista de ingredientes se debería considerar como un string de 30 caracteres.
![image](https://github.com/IIC2413/Syllabus-2024-1/assets/16352918/2889840e-05d8-4bdb-9ff0-36ea4dff0c19)

El problema es que la mayoría de los platos tienen una lista de ingredientes de mas de 30 caracteres. (con lista me refiero a un texto largo, no a un tipo distinto de datos)
Algunos ejemplos:
![image](https://github.com/IIC2413/Syllabus-2024-1/assets/16352918/7eed0a46-798f-4b1b-aa26-33bd663b38a2)
![image](https://github.com/IIC2413/Syllabus-2024-1/assets/16352918/2326fe05-e7d3-4cbb-83f1-54e23a649771)
![image](https://github.com/IIC2413/Syllabus-2024-1/assets/16352918/edcd1934-036a-4490-9cb8-171a0ab050e4)

Para cargar los datos a la base de datos, ¿deberíamos acortar la lista de todos esos platos para que sea un string de 30? ¿o deberíamos simplemente extender el tamaño del string (osea, no limitarlo a varchar(30) y extenderlo por ejemplo a varchar(100))?
El enunciado menciona que tenemos que tomar la acción mas "idónea" pero eso es demasiado ambiguo.

**Comment by cgodoy99** [comment]
Hola, tengo la misma duda con esto de los ingredientes. En la issue #94 se menciono que los ingredientes se pueden separar, esto significa que yo al leer el archivo csv y obtengo una tupla con los datos del archivo platos.csv voy a obtener los ingredientes, los cuales puedo separarlos usando un separados de string para ingresarlos individualmente a una tabla "Ingrediente" por dar un ejemplo, o estoy entendiendo mal? Esto porque en la misma issue se menciono que no hay necesidad de hacer un array para los ingredientes.

Esto mismo me genera otras dudas que son:

¿Los datos de una tupla obtenida de un csv se pueden ingresar en mas de una tabla?
¿Estos datos deben tratar de insertarse sin modificar ningun valor en un comienzo? O puedo hacer el split como es en el caso de los ingredientes para luego intentar insertar en mi tabla?

Que si se puede hacer el split de ingredientes ahi no me queda claro la restriccion de no modificar antes de insertar.
¿El split se consideraria pre procesamiento de los datos antes de insertar?

Segun entiendo la restriccion que tenemos es que se debe obtener la tupla de un csv e intentar insertar sin modificar el valor, luego de que salte el error se toma alguna accion. Por ejemplo, como decian en una issue hay emails con mas de 30 caracteres y lo que se menciono era aumentar los caracteres permitidos para el email, ¿Lo correcto seria esperar a que falle y luego aumentar y lo incorrecto hacer algo del estilo email[:29]?. Estoy entendiendo mal?

**Comment by ypne** [comment]
@GithubSPerez  respondido en https://github.com/IIC2413/Syllabus-2024-1/issues/124
@cgodoy99 se menciono que los ingredientes se pueden separar
R: si, se pueden separar o trabajar juntos
¿Los datos de una tupla obtenida de un csv se pueden ingresar en mas de una tabla?
R: Si
O puedo hacer el split como es en el caso de los ingredientes para luego intentar insertar en mi tabla?
R: Una vez leida la tupla del archivo puedes manipularla dentro del cargador como necesiten para su modelo
¿El split se consideraria pre procesamiento de los datos antes de insertar?
R: si el split es necesario y lo hacen dentro del cargador  no es preprocesamiento, se puede hacer
¿Lo correcto seria esperar a que falle y luego aumentar y lo incorrecto hacer algo del estilo email[:29]?
R: si

**Comment by cgodoy99** [comment]
Muchas gracias!! Con esto me queda mucho más claro! 

Un par de dudas más
1. Puedo transformar a lowercase el primer ingrediente? Para que queden todo en minisculas y el primer ingrediente de cada plato no quede con una letra en mayúscula
2. Al arreglar un problema de integridad, por ejemplo con los mails de los clientes, falla el primer cliente, se toma una solución, ¿Para los demás clientes ya no debe fallar por que se solucionó? ¿O debo guardar la tupla, esperar que todos fallen, solucionarlo y luego intentar volver a cargar esas tuplas?

**Comment by ypne** [comment]
Si lo haces con el cargador si
o puedes usar ILIKE
