### ISSUE TITLE
Nombre de despachador es único?

### ISSUE THREAD

**Issue by GitCross135** [IIC2413/Syllabus-2024-1#203]
Hola, en el archivo calificacion.csv nos dan el id del pedido, la calificación del delivery y despachador, y la calificación del cliente.

Ahora, en el archivo pedidos.csv, nos dan el id (es único) del pedido, el mail del cliente (los mails de los clientes son únicos según enunciado) de ese pedido y el NOMBRE del despachador, sin embargo, en ningún lado se especifica que los nombres de los despachadores son únicos, y la única forma que tenemos de distinguirlos hasta ahora es por el número telefónico (el enunciado dice que son únicos).

Por lo que nuestro problema es si podemos asumir que el nombre del despachador es un atributo único (2 despachadores distintos no pueden tener el mismo nombre-apellido) o no, para poder relacionar la calificación del despachador con el nombre entregado en pedidos.csv, gracias de antemano!

**Comment by ypne** [comment]
si
