### ISSUE TITLE
Consulta con Profesor

### ISSUE THREAD

**Issue by Cristian1754** [IIC2413/Syllabus-2024-1#205]
Hola profesor, ¿Habra algun horario disponible hoy (despues de las 15:00 hrs idealmente) para tener una sesión de consultas con usted? (somo grupo 105)

**Comment by ypne** [comment]
Hola se me acabaron las horas prefijadas así que atentos al telegram Bases de datos porque si me desocupo antes de otra lo publicaré ahí
