### ISSUE TITLE
Duda sobre consultas

### ISSUE THREAD

**Issue by ChupeteBecker** [IIC2413/Syllabus-2024-1#208]
en el enunciado dice (Funcionalidades a implementar) que hay que hacer dos tipos de consultas, la primera (punto 2) dice que son las consultas listadas (consultas sql a implementar), algunas de estas consultas dice que se deben hacer en base a un atributo especifico (ejemplo: Plato en la consulta 1) ingresado. Cuando dice que es ingresado se refiere  que el usuario debe ingresar el plato y luego la pagina hace la consulta o ese plato es arbitrario y elegido por nosotros? cosa que cada vez que se inicie la pagina se realice la consulta al servidor.

**Comment by ypne** [comment]
deben recibir el nombre como parámetro

**Comment by ChupeteBecker** [comment]
muchas gracias
