### ISSUE TITLE
Proyecto - Duda de Sistema

### ISSUE THREAD

**Issue by SrGarZito** [IIC2413/Syllabus-2024-1#21]
¡Buenas tardes!, mi grupo y yo tenemos un pequeño debate con respecto a un tema y es que, dentro del enunciado, se habla bastante de un "_sistema_", ¿Es referencia al funcionamiento de la aplicación y su almacenamiento de los datos?, y, por ende, ¿no se debe contar como una entidad como tal de la plataforma?

✨Esperamos la respuesta pacientemente, gracias de antemano. ✨

♠️♥️ ¡Un Saludo! ♦️♣️

**Comment by isufan** [comment]
Hola! En este caso, el sistema se refiere a la plataforma, la cual debe integrar todos los componentes que aparecen en el enunciado. Considerando esto, el modelo E-R lo que debe hacer es justamente representar estos componentes y la forma en que se relacionan entre sí, por lo que no sería necesario incluir una entidad "sistema".

Saludos!
