### ISSUE TITLE
Creación de tabla pedidos

### ISSUE THREAD

**Issue by Fopazov** [IIC2413/Syllabus-2024-1#211]
Esperando que estén bien, como equipo nos surgió una duda. Si bien no se pueden modificar los archivos csv, ¿se puede crear uno? Creamos una tabla que contiene como atributos (pedido, plato), y queremos que "plato" sea UN SOLO PLATO, lo que sería distinto con respecto al archivo de pedidos (que "plato" es una cadena de string que puede representar varios platos). Hemos tenido problemas para poblar esa tabla, ¿podríamos crear otro archivo csv para facilitar el proceso de carga de esta tabla? (es la única que nos falta)
Gracias de antemano

**Comment by ypne** [comment]
ok haganlo pero debe ser dentro del cargador o sea no separar el archivo a mano ya que en la corrección usaremos un archivo de idéntico formato a los entregados

**Comment by Fopazov** [comment]
Gracias!
