### ISSUE TITLE
Duda sobre consultas a implementar en EasyFood webpage [E2}

### ISSUE THREAD

**Issue by Ariimaw** [IIC2413/Syllabus-2024-1#212]
Hola! :3 tengo las siguientes dudas sobre las consultas en la pagina web:

1. En la página de consultas inestructuradas se espera que manejemos consultas que involucren JOINS de tablas? Es decir, que el usuario ingrese como input "T" múltiples tablas o la misma tabla repetida renombrándola con "AS"? Por ejemplo, consultar "SELECT clientes.email, pedidos.id FROM clientes, pedidos" o "SELECT cl1.email, cl2.email FROM clientes AS cl1, clientes AS cl2". Mismo caso para “FROM clientes JOIN pedidos”.

- Si el inciso (1) es cierto, está permitido incluir instrucciones para consultar por la página? Por ejemplo: Si se desea consultar por las tablas A, B, C… se instruye que estas deben ser ingresadas siendo separadas por comas y que se deben ingresar los atributos con tal formato, etc.
- Si el inciso (1) es cierto pero (1.2) no está permitido. Entonces no es recomendable intentar limpiar el input del usuario para hacer una consulta "correcta" desde la app? Por ejemplo: Una vez ingresado el form, desde el script de python tomar individualmente los atributos y tablas ingresadas y automatizar el formato que debería tener la consulta.

2. ¿Se espera que el usuario pueda ingresar consultas anidadas? Del tipo ingresar en FROM un string T de la forma SELECT.... (otra consulta)?

**Comment by ypne** [comment]
1.- no usaremos JOIN solo expresiones logicas, tampoco AS
1.1.- no se puede exigir formato,  se debe validar que el formato esté correcto
1.2.- eso si se puede hacer
2.- tampoco haremos eso

**Comment by Ariimaw** [comment]
Gracias! :3 una ultima cosa:

1.1- Ya que debemos validar que el formato este correcto, si mi programa "arregla" mal formato (por ejemplo ingresar atributos "nombre, email, , , clave") y es capaz de realizar la consulta de todas formas obteniendo los tres atributos obtenibles, se consideraria malo? Deberiamos indicarle al usuario que su input esta mal en vez de correr la consulta?

**Comment by ypne** [comment]
Estaría bien si es que el resultado de la limpieza es el correcto
