### ISSUE TITLE
Problemas con acceder a mi formulario

### ISSUE THREAD

**Issue by Ethan3v** [IIC2413/Syllabus-2024-1#213]
Tengo el problema que estuve siguiente los pasos de la issue 166 y al correr el server y entrando al link me sale todo en blanco y en la powershell me aparece.
![Captura de pantalla 2024-05-24 142641](https://github.com/IIC2413/Syllabus-2024-1/assets/170756012/22a70f0f-3f2e-43a5-9f42-92763fce8a6c)

**Comment by calvarezl-cl** [comment]
Estimados, el error se produce porque el archivo ejemplo.py estaba con formato DOS (Windows) y no en formato linux. Al corregir el formato ya no se produce el error.  Ya está corregido en su directorio

CAL

**Comment by Afibla** [comment]
Hola, tenemos ese mismo error somos el grupo 71

**Comment by calvarezl-cl** [comment]
Con el editor nano, creen en el servidor un archivo en blanco y copien el siguiente contenido:

#!/usr/bin/python3

# enable debugging
import cgitb
cgitb.enable()

print("Content-Type: text/plain;charset=utf-8")
print()

print("Hello World!")

**Comment by Afibla** [comment]
hice lo de nano y me sigue apareciendo así;
![image](https://github.com/IIC2413/Syllabus-2024-1/assets/127804822/95b27308-231e-4dfc-89f2-7b2ce6036f3b)

**Comment by calvarezl-cl** [comment]
> hice lo de nano y me sigue apareciendo así; ![image](https://private-user-images.githubusercontent.com/127804822/333761334-95b27308-231e-4dfc-89f2-7b2ce6036f3b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2NTg2NTQsIm5iZiI6MTcxNjY1ODM1NCwicGF0aCI6Ii8xMjc4MDQ4MjIvMzMzNzYxMzM0LTk1YjI3MzA4LTIzMWUtNGRmYy04OWYyLTdiMmNlNjAzNmYzYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNVQxNzMyMzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNjZkNTk0NjBjZjgyOGIwZWI2NDYzMzM2ZDkzOWVjMGY3YTYwNmM2NzFkMmRiNjQ2YjQ5OWM3NjBjY2Q5OTg2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._QUjbYO9yZME8wP7ulVucs0cQ1KWPJOW9CpI5QLe16c)

El archivo sigue estando en formato DOS

**Comment by calvarezl-cl** [comment]
<img width="661" alt="Screenshot 2024-05-25 at 1 41 25 PM" src="https://github.com/IIC2413/Syllabus-2024-1/assets/55099390/8a06a13b-57ee-4703-9199-7745176918e8">
