### ISSUE TITLE
E2: Delivery propio

### ISSUE THREAD

**Issue by Washaaaan** [IIC2413/Syllabus-2024-1#218]
Saludos,

Quería hacer una consulta respecto al delivery propio y a la empresa despachadora, ambas entidades poseen los atributos de delivery vigente, precio unitario despacjo, delivery nombre, delivery telefono, delivery tiempo, delivery precio mensual y delivery precio anual? En caso de que no sea así, qué atributos son los que posee el delivery propio?

**Comment by ypne** [comment]
ninguno

**Comment by Washaaaan** [comment]
Muchas gracias!!
