### ISSUE TITLE
E2: Formato de consultas

### ISSUE THREAD

**Issue by Cristian1754** [IIC2413/Syllabus-2024-1#221]
Hola, tengo entendido que el formato de consultas a travez de la pagina sera del estilo SELECT A FROM T WHERE C. Como se pide que las tablas esten en BCNF, no me queda claro si es que las tablas tienen que estar hechas de una manera tal que al que revise se le haga facil hacer las consultas pedidas? O se puede implementar algun tipo de consulta prehecha (las que se piden en el enunciado) en el que solamente se ingrese el input y se muestre el resultado deseado.

**Comment by ypne** [comment]
Las 10 consultas estructuradas son de esa forma. Para conocer los nombres de las tablas en la u estructurada usaremos el informe

**Comment by Cristian1754** [comment]
Entiendo, entonces en el informe podemos poner como hacer estas consultas? tipo:
Para hacer la consulta 1 se debe hacer de esta manera: (Formato SQL pedido en el enunciado)

**Comment by ypne** [comment]
A ver si hablamos lo mismo
En las consultas a implementar (10) hay algunas fijas y otras que reciben un parámetro de entrada. Esas solo deben sanitizer el input del parámetro, el resto es fijo.

En la consulta SFW o estructurada ustedes reciben 3 parámetros y para ella debemos conocer el nombre de las tablas que vienen en el esquema del informe.
El parámetro del select puede ser *, atributos de una tabla u otro que no esté. El parámetro del from son nombres de tablas y el where solo expresiones lógicas no operaciones. Aquí deben sanitizer el input también de modo que al pasárselo al sql no tenga efectos inesperados.

**Comment by Cristian1754** [comment]
Entiendo, a lo que me refiero es dejar en el informe una guia sobre como hacer estas consultas, por ejemplo:
Para la consulta 1: escoger estos T, y estas condiciones C

**Comment by ypne** [comment]
No es necesario porque la consulta 1 recibe un solo parámetro

**Comment by gaspar-mr05** [comment]
Hola! tengo la misma duda. Entonces van a haber consultas que solo recibiran un parametro (eso lo entiendo), pero además de esas, hay otras que reciben los tres parámetros (Tablas, Atributos, Condiciones)?
