### ISSUE TITLE
Duda respecto a tipos de datos existentes en modelo relacional

### ISSUE THREAD

**Issue by BenjaCarrill0** [IIC2413/Syllabus-2024-1#222]
Buenas tardes, me surgió la duda acerca de qué tipos de datos se pueden utilizar al crear un modelo relacional por ejemplo cuando uno quiere referirse a un dato que es un string pero es largo variable ¿debería indicarse como string o como un varchar?, también por ejemplo cuando se tiene un tipo de dato que sería un "date" en el modelo relacional ¿debería colocarse como string o date?

Espero su respuesta

**Comment by VicenteSanMartin** [comment]
Hola! Respecto a la primera pregunta, VARCHAR(N) es utilizado para indicar un string con largo variable, pero que tiene un largo máximo N, el cual es especificado como parámetro al momento de crearlo. En cambio, TEXT es simplemente un string que no tiene restricciones de largo. Por eso, te recomiendo usar VARCHAR si te interesa forzar una restricción de largo, y si no, usar TEXT.

Por otro lado, todos los datos que son fechas te recomiendo trabajarlos como dates en vez de strings. Para valores que solo son fechas (sin horario), te recomiendo usar DATE. De lo contrario, te recomiendo utilizar TIMESTAMP para el formato con fecha y hora.

**Comment by BenjaCarrill0** [comment]
Buenas tardes, me refería a lo que se debe hacer cuando se escribe el esquema de una tabla "en papel", lo que no tengo claro si es que al momento de indicar si un atributo será de cierto tipo se tendría que indicar de una forma parecida a SQL o no

**Comment by VicenteSanMartin** [comment]
Sí, la idea es que al escribir un esquema, el tipo de datos sean lo más parecido a SQL posible

**Comment by BenjaCarrill0** [comment]
Muchas gracias
