### ISSUE TITLE
SQL Injection en consulta inestructurada | E2

### ISSUE THREAD

**Issue by vichoassadi** [IIC2413/Syllabus-2024-1#223]
Hola profesor!

No sé si con el cambio de fecha siga respondiendo dudas, pero escribo igual por acá. Para la consulta 3 (inestructurada), cuál es el formato de las condiciones? Porque, si es realmente inestructurada, uno podría concatenar a la query todas las condiciones, pero queda abierto a que, en la celda de condiciones, el usuario ponga, por ejemplo, "1; DROP TABLE usuarios;".

Lo que se nos ocurrió hacer fue lo siguiente:

![image](https://github.com/IIC2413/Syllabus-2024-1/assets/133837937/d50f460a-0312-4855-a557-c89200eee0da)

Con, claro, las tablas y los atributos separados correctamente en una tabla. El problema es que, nuevamente, en las condiciones uno podría hacer un SQL Injection, y no es posible sanitizarlo debido a que estamos usando directamente con nombres de tablas o de atributos, no valores a comparar. Podemos "estructurar" un poco más las condiciones, de manera que sea `atributo` = `valor`? Así se ve actualmente en la página:

![image](https://github.com/IIC2413/Syllabus-2024-1/assets/133837937/bdb9c09c-2dbe-4b1b-ac6a-1e40f56355aa)

Muchas gracias

**Comment by vichoassadi** [comment]
O existe la posiblidad de verificar antes que no hayan palabras peligrosas, como DROP, por ejemplo?

**Comment by dvillas28** [comment]
con mi grupo estamos haciendo algo parecido, verificar keywords que puedan afectar a la BDD

**Comment by ypne** [comment]
Eso es lo correcto!!
En los parámetros solo probaremos  inyección de código y sanitización de Input
