### ISSUE TITLE
Consulta personalizada

### ISSUE THREAD

**Issue by AleSierra26** [IIC2413/Syllabus-2024-1#225]
Tengo una duda acerca de la Consulta personalizada (en la que el usuario elige el select, from y where). Solo sera un string en cada uno(1.) o pueden ser varios separados por coma(2.)? es decir:
1. Select X From Y Where Z
O puede tambien ser de la forma:
2. Select A, X From B, Y Where Z

**Comment by AleSierra26** [comment]
Incluso, puede ser que el input en select sea *?

**Comment by ypne** [comment]
Pueden ser ambas, lo importante en esta consulta es la sanitización del input o sea que no aparezcan ";" o " " en la separación de los parámetros.
