### ISSUE TITLE
[Entrega 1]  Confusión enunciado

### ISSUE THREAD

**Issue by Shoesuke** [IIC2413/Syllabus-2024-1#23]
Holaa, estoy confundido con los siguientes puntos del enunciado, a que se refiere exactamente cuando dice "seleccionar que servicio de despacho quiere usar" y "el despacho será realizado por una sola empresa pero con un servicio despachador por restaurant", adjunto la ss del enunciado para que puedan leerlo aquí mismo, gracias!!.

![image](https://github.com/IIC2413/Syllabus-2024-1/assets/130422187/e9264822-ccdc-4b93-87a7-5d8f31cb024e)

**Comment by isufan** [comment]
Hola! Te recomiendo revisar la issue #14, ahí se explica más en detalle.

Saludos!
