### ISSUE TITLE
Direcciones cliente csv sin tilde ni ñ

### ISSUE THREAD

**Issue by DaniSZ02** [IIC2413/Syllabus-2024-1#230]
Revisando los archivos csv me di cuenta que clientes.csv es el único que no tiene ni tildes ni ñ, mi pregunta es si esta situación debemos manejarla nosotros manualmente (cosa que veo difícil) y ponerlo en el informe o es un error del archivo? Ya que si luego quiero buscar direcciones con tildes en una tabla de direcciones con tildes no los encontraran aunque se la misma al tener esa leve diferencia (esto me refiero al hacer SELECT para hacer insert respecto a las asociaciones necesarias).

**Comment by DaniSZ02** [comment]
Pero en el caso de querer hacer la sanitización en python como sabríamos cuando hay que poner tilde o una ñ por ejemplo? Ya que en el archivo clientes.csv (el único de todos) esos datos no salen como inválidos sino mas bien que directamente no lo tienen y tienen palabras como "Nunoa" o "Colon", haciendo difícil implementar un codigo que les añade las ñ y tildes necesarios sin dañar otros datos.

**Comment by ypne** [comment]
Cada caracter fuera del rango aceptado tiene su código específico por lo que puedes hacerlo por inspección y eso depende de la plataforma en que lo hagas. otra alternativa es buscar en interner el caracter extraño y te va a entregar el equivalente.
Todas las Ñ ñ y letra con tilde o dieresis tienen un unico código en el archivo
