### ISSUE TITLE
duda sobre consulta 7, entrega 2

### ISSUE THREAD

**Issue by TomasRiquelme** [IIC2413/Syllabus-2024-1#231]
buenas tardes!

no entiendo muy bien a que se refiere con "no incluidas con en planes de suscripcion"
se refiere a clientes que hicieron pedidos con deliveries a los que no están suscritos? clientes sin plan de suscripcion?
no entiendo muy bien :c

gracias de antemano

**Comment by ypne** [comment]
Si habla de $ gastada quiere decir que hizo pedidos pero los pagó individuales porque no tiene plan de suscripción a ese delivery

**Comment by TomasRiquelme** [comment]
yaaaaaaa, seria usando el precio unitario; porque no está suscrito.
Perfect, muchas gracias :D
