### ISSUE TITLE
Arreglo de errores

### ISSUE THREAD

**Issue by sebamusea** [IIC2413/Syllabus-2024-1#232]
Hola!
Mi pregunta es si en el archivo de python en donde se cargan los datos y se arreglan los errores, tengo que si o si arreglar los errores después que ocurran? Para ser más claro, digamos que mi codigo sube las tuplas correctas pero no las que tienen algún fallo. Es necesario que se haga en ese orden (cargar, detectar fallos, arreglar, cargar las tuplas arregladas solamente) o puedo a medida que el archivo está cargando las tuplas, cuando detecte un error lo corrija de inmediato y así lo solucione altiro en vez de tener que hacer 2 cargas de datos?

Muchas gracias

**Comment by ypne** [comment]
La corrección se puede hacer en la sanitización de datos en el cargador aceptando solo caracteres válidos y reemplazando los inválidos. Otras correcciones como violación de un UNIQUE o FK requiere más proceso por lo que la segunda opción es mejor.
