### ISSUE TITLE
Consulta 3

### ISSUE THREAD

**Issue by michebordoni** [IIC2413/Syllabus-2024-1#236]
Hola! tengo una duda respecto a la consulta 3
En base a issues anteriores entiendo que a cada pedido le debo sumar el delivery y para eso hay que revisar las suscripciones de los clientes, si la forma de determinar si una suscripción esta vigente es revisar la fecha del ultimo pago, esta solo determina si esta vigente ese mes/año especifico entonces no tenemos data de los meses/año anterior, así deberíamos asumir que los meses anteriores a ese sí tenia suscripción o no? Dado que es muy probable que un cliente tenga suscripción un mes y que haya realizado pedidos en meses anteriores a ese

**Comment by ypne** [comment]
puedes asumirlo

**Comment by Ariimaw** [comment]
@ypne Hola! :3

Entonces estaria correcto tambien verificar que exista una suscripcion anual o mensual que "cubra" en su rango la fecha del pedido para determinar si este fue hecho con una suscripcion o no? Como existen entradas de suscripcion de un mismo cliente a la misma empresa de delivery en fechas distintas lo tomamos como un historial. Osea, basicamente nos quedamos con los pedidos donde exista alguna suscripcion entre el mismo cliente y empresa tal que la fecha de la suscripcion + 1month/year sea una fecha mayor a la del pedido, y que la fecha de la suscripcion sea menor a la del pedido. Esta forma de abordarlo esta bien tambien? (en relacion a parte de la consulta 7). 

Pregunto porque la respuesta a esta issue me da entender que es valido asumir que cualquier cliente dentro de los archivos de suscripcion estuvo suscrito en meses/años pasados, entonces que un cliente pertenezca al csv implica que automaticamente puede ser tratado como cliente suscrito en todos sus pedidos realizados? Sin necesidad de verificar la fecha?

Apreciaria mucho saber si ambas formas de interpretarlo son correctas o si alguna no lo es!!
