### ISSUE TITLE
Duda sobre la url de la app

### ISSUE THREAD

**Issue by martina-abello** [IIC2413/Syllabus-2024-1#237]
Entendí lo de cuál debería ser el puerto, pero hay condiciones sobre el host? Imagino que no será localhost si lo tienen que acceder los ayudantes, pero no estoy segura.

Cuando corro mi app.py usa 127.0.0.1 automáticamente, eso está bien? O debería ser otra cosa?

Gracias de antemano

**Comment by AntonioEscobar01** [comment]
Hola, capaz te sirve lo que encontramos como grupo para generar el link del proyecto. Mira la issue #239
