### ISSUE TITLE
Formato diagrama

### ISSUE THREAD

**Issue by Fopazov** [IIC2413/Syllabus-2024-1#24]
Hola, pregunta específica. ¿El diagrama se tiene que hacer en algún programa o puede entregarse "a mano" ?(lo hice en goodnotes) (asumiendo que está claro y el entregable estará en formato pdf). Si no se puede, ¿qué programa recomiendan?

**Comment by isufan** [comment]
Hola! Mientras esté claro y ordenado, no hay problema con hacerlo a mano en goodnotes. De todas maneras recomiendo mucho la página [draw.io](draw.io) para hacer diagramas.

Saludos!
