### ISSUE TITLE
Material de estudio para el taller de índices

### ISSUE THREAD

**Issue by JavierLarre** [IIC2413/Syllabus-2024-1#242]
Hola! ¿Hay algún material que recomiendan que estudiemos para el taller de índices además de las clases? ¿hay una evaluación de algún semestre pasado o una página web o sección del libro que nos recomienden ver para basar nuestros estudios? cualquier cosa que sirva para preparse y tener una idea de lo que se va a preguntar, saludos!

**Comment by MaxiPis** [comment]
Sii, porfass, sobre todo con la recomendación de algún libro para lo que resta del curso, siento que las slides no es material suficiente pipipi

**Comment by ypne** [comment]
1.- En la clase 11, último slide aparece la referencia al libro de la bibliografía 
[Database Management Systems, 3rd edition, de Raghu Ramakrishnan y Johannes Gehrke.](https://bmdigitales-bibliotecas-uc-cl.pucdechile.idm.oclc.org/html5/DATABASE%20MANAGEMENT%20SYSTEMS/) Part III
2.- En canvas sección 4 hay material complementario de todos los repo de github desde 2019 en adelante.

**Comment by MaxiPis** [comment]
Okaas, lo pude revisar, muchas gracias :)
