### ISSUE TITLE
Recorreción E1 

### ISSUE THREAD

**Issue by bzalaquett** [IIC2413/Syllabus-2024-1#245]
Hola,
Mandamos a corregir la entrega 1 del proyecto mediante el formulario de que se indicó. Todavía no hemos recibido ninguna respuesta ni hemos observado cambios en las notas. Nos gustaría saber para cuándo estarán las correcciones disponibles. Gracias

**Comment by franancic** [comment]
Hola se mandará anuncio hoy:)
