### ISSUE TITLE
Duda de SQL i1

### ISSUE THREAD

**Issue by gaspar-mr05** [IIC2413/Syllabus-2024-1#25]
Hola! Estaba revisando ayudantías y guías para estudiar SQL y lo único que encontré fueron archivos jupyter con ejercicios de consultas en SQL para programar. En qué me puedo basar para estudiar SQL? Las preguntas serán teóricas o tendremos que escribir consultas a mano? Ya que entiendo que la prueba no será con computador.

**Comment by MartyMolina** [comment]
Hola, mi mayor recomendación es hacer las guías que se subieron de SQL y abrirlas en Google Colab. Si ya las realizaste, sigue con las de otros semestres. La mejor manera de estudiar SQL es ejercitando y usando los PDF de clases para apoyarte. La prueba será de desarrollo. Probablemente las preguntas sean de ambos tipos, teórico y consultas. Estudiando las guías subidas, cómo realizar consultas correctamente y el funcionamiento de los códigos deberías estar bien
