### ISSUE TITLE
Participación Múltiple vs Jerarquía de Clases

### ISSUE THREAD

**Issue by jalonsoluc** [IIC2413/Syllabus-2024-1#26]
Hola! Cómo están?

En clases nos enseñaron que una entidad puede participar de diferentes formas en una relación:
![image](https://github.com/IIC2413/Syllabus-2024-1/assets/115756969/129ef12e-a559-444d-ae27-a39651b42f69)

Además, se puede definir una jerarquía de clases:
![image](https://github.com/IIC2413/Syllabus-2024-1/assets/115756969/aba46a8f-bf06-4129-aaee-82a6480d3be1)

En qué caso corresponde/conviene usar un método por sobre el otro? No sería lo correcto usar **siempre jerarquía de clases**?

Gracias!

**Comment by MartyMolina** [comment]
La jerarquía es lo correcto de utilizar en los casos en que se debe representar la herencia (como en el ejemplo mencionado) de manera jerárquica. Sin embargo, hay casos en los que no existe una jerarquía de ese tipo, por lo que se utiliza una relación para relacionar las entidades. Son distintos métodos que se utilizan en sus respectivos casos.
