### ISSUE TITLE
Entrega 1: Atributos que no son requisito del enunciado

### ISSUE THREAD

**Issue by sguridirt** [IIC2413/Syllabus-2024-1#28]
Hola! En nuestro diagrama tenemos entidades que son necesarias para modelar el problema del enunciado, algunas están explícitas en las instrucciones y otras las hemos definido por utilidad. Sin embargo, muchas de las explicitadas no contienen atributos por lo que no podemos definirles llaves. Nos ocurre lo mismo con las que definimos por utilidad.

**¿Es necesario para la entrega 1 crear atributos para utilizarlos como llaves en cada entidad?** Por ejemplo, el restaurante no tiene atributos explícitos, pero podría tener un id. ¿Debemos asignárselos nosotros o podemos ignorarlo?

Todo esto ignorando las llaves débiles, por supuesto.

**Comment by MartyMolina** [comment]
Esta constestada en la issue  #12
