### ISSUE TITLE
Proyecto: Duda Llave compuesta

### ISSUE THREAD

**Issue by FelipeGonzaUC** [IIC2413/Syllabus-2024-1#29]
Buenas
Tengo un duda respecto a lo que se refiere en la pregunta 3 del enunciado de la primera etapa del proyecto:
 "¿Que entidades tienen llaves compuestas?"

Mi problema es que no encuentro definición de llave compuesta dentro de los contenidos del curso vistos hasta el momento.

**Comment by elbosco** [comment]
La llave compuesta es una llave primaria, pero con la diferencia de que tiene más de un atributo. Suele ser útil cuando una sola columna (o atributo) no es suficiente para hacer única a cada fila. Por ejemplo, en una relación de Autos con atributos como Marca, Modelo, Año_modelo, color y stock, queremos que la llave compuesta sea el conjunto de atributos Marca, Modelo y Año_modelo, ya que tener solamente la Marca o el Modelo no garantiza la unicidad de cada fila. Si solo tuviéramos el atributo Marca como llave primaria, solo podríamos tener una fila para cada marca, por lo que solo habría una fila para Kia, una para BMW, y así sucesivamente.
