### ISSUE TITLE
Sobre "otros datos personales" del despachador

### ISSUE THREAD

**Issue by dvillas28** [IIC2413/Syllabus-2024-1#30]
¿que se supone que deben ser atributos?

Podemos colocar atributos a nuestra seleccion (asumiendo que sean pertinentes al problema?)

![image](https://github.com/IIC2413/Syllabus-2024-1/assets/128737225/8242a14a-41e6-40c1-96cf-7df07a9e5230)

saludos y gracias de antemano 🤠

**Comment by elbosco** [comment]
Hola, sí, ese punto los invita a incluir los atributos de datos personales adicionales que consideren pertinentes para su proyecto, de cada despachador. Si tienes alguna otra duda, me comentas.
Saludos :D
