### ISSUE TITLE
Buzón Entrega 1

### ISSUE THREAD

**Issue by Pablo-Gonzalez-Calderon** [IIC2413/Syllabus-2024-1#31]
Buenas noches ✨

Con mi grupo estábamos buscando el buzón de Canvas para subir la entrega 1 del proyecto, pero no lo encontramos por ningún lado. Quería saber si van a crear el buzón el mismo día de entrega u otro día.

Gracias de antemano

**Comment by elbosco** [comment]
Hola, ahora lo crearemos.
Saludos,
