### ISSUE TITLE
Esquema E1

### ISSUE THREAD

**Issue by bea-or** [IIC2413/Syllabus-2024-1#33]
Hola,

Tengo varias dudas acerca de la entrega.
Primero, en el esquema, las relaciones se tienen que poner? Y si es que se deben poner, como se hace? Estaba revisando los ppts y no esta tan claro. 
Segundo, cual es la diferencia entre empresa despachadora y servicio despachador?
Tercero, para el administrador, habría que relacionarlo con todas las entidades que puede modificar o no es necesario?

Gracias de antemano.

**Comment by RICARDOOVIEDO** [comment]
Con respecto al esquema, tienen que seguir lo que se enseño en clases para hacerlo. 
Al final una es el delivery y otro es el servicio mismo que despacha, van relacionados. 

La tercera pregunta, Los administradores son los que realizan la configuración del sistema y determinan sus parámetros. En realidad no tienen relación con nadie.
