### ISSUE TITLE
E1: ¿Los administradores deben ir relacionados con otras entidades?

### ISSUE THREAD

**Issue by Washaaaan** [IIC2413/Syllabus-2024-1#34]
Buenas, me surgió la duda de si la entidad administradores deben ir relacionados a otras entidades tales como los restaurantes y las suscripciones, ya que el enunciado indica que éstos deben poder modificar información de esas entidades, pero habrá que relacionarlos para ello? O solamente es una entidad que hay que colocar y ya?

**Comment by RICARDOOVIEDO** [comment]
Esa respuesta la respondi en la issue #33.
