### ISSUE TITLE
E1 - restricciones de integridad y dominio

### ISSUE THREAD

**Issue by empanad4z** [IIC2413/Syllabus-2024-1#35]
Hola, leyendo la parte de entrega del proyecto se mencionan las restricciones de integridad y dominios. Podemos crear cualquier tipo de restriccion que estimemos conveniente? Y estas se ponen de manera general para todo el esquema como se hace en la pag. 71 del ppt de diseño de bases de datos 2? Es decir, si tenemos entidades que heredan de "persona" con el atributo edad, podemos simplemente especificar que la edad de las personas esta entre 0 y 150 años como se hace en el ppt? No me quedo muy claro eso sin usar SQL

**Comment by RICARDOOVIEDO** [comment]
En que parte del enunciado se mencionan estas restricciones? Que restricciones les interesa poner?

**Comment by empanad4z** [comment]
En la segunda página, en la parte de entrega: "Para esta entrega el grupo deberá entregar un informe en pdf con el diagrama entidad relaci´on, esquema
de la base de datos con sus relaciones, y la respuesta a cada una de las preguntas, atributos, dominios y restricciones de integridad." Entonces eso me confundio un poco
