### ISSUE TITLE
Hay telegram del curso?

### ISSUE THREAD

**Issue by martina-abello** [IIC2413/Syllabus-2024-1#37]
En la ayudantía de hoy dijeron que mandarían por ahí el código, pero no encuentro el link. ¿Me lo comparten, por fa?

**Comment by isufan** [comment]
Hola! Por lo que veo que ya te agregaron pero de todas maneras dejo el [link del grupo](https://t.me/joinchat/oqK1gH5mSjgwNDAx) por acá.

Saludos!

**Comment by martina-abello** [comment]
Muchas gracias!
