### ISSUE TITLE
Contenidos Taller 1

### ISSUE THREAD

**Issue by inecalvimontes** [IIC2413/Syllabus-2024-1#4]
Hola! Para el taller 1 entrará todo el PPT de E/R? En una sección la clase pasada alcanzamos a ver hasta relaciones múltiples no más. Quedo atenta a la respuesta, gracias!

**Comment by RICARDOOVIEDO** [comment]
Hola! Asuman que entra lo que vieron la clase pasada, más lo que alcancen a ver el primer módulo hoydia.

Saludos
