### ISSUE TITLE
Coevaluación entrega 1

### ISSUE THREAD

**Issue by benjareyesr** [IIC2413/Syllabus-2024-1#40]
Hola, buenas tardes. Quisiera saber cuándo habrá que llenar la evaluación de pares... aún no han enviado mensajes anunciándolo, ni aparece en Canvas. Eso, gracias de antemano :).

**Comment by franancic** [comment]
Hola! se subirá junto con el enunciado 2 y tendrán plazo hasta el día 10 de mayo para contestarla:)

**Comment by martina-abello** [comment]
dónde está? Q-Q
