### ISSUE TITLE
Problema a conectarse servidor filezilla

### ISSUE THREAD

**Issue by plourido** [IIC2413/Syllabus-2024-1#41]
Hola, buenos dias. Estoy tratando de conectarme al servidor visto en la ayudantia 3 y no me esta funcionando. Me podrian ayudar?
Muchas gracias

**Comment by valecarvajala** [comment]
tengo el mismo problema :((((((

**Comment by ypne** [comment]
filezilla no es parte del proyecto, esta pregunta general la pueden hacer al grupo de telegram
