### ISSUE TITLE
Habilidades y herramientas

### ISSUE THREAD

**Issue by santiago3c** [IIC2413/Syllabus-2024-1#42]
Hola, que hay varias habilidades que se van a requerir para la tarea 2 que no entiendo muy bien, en particular respecto a con lo que se vio en la ayudantía, si me podrían ayudar. De lo que tengo entendido, voy a poder acceder al servidor de mi grupo, que es como una carpeta en otro computador. Ahí voy a poder poner archivos csv, crear tablas sql y poner archivos python y html. Tengo entendido que esta "carpeta" tiene asociado un url. Pero no entiendo cómo hacer para que al poner en internet esta url, se vea un html. Tampoco entiendo como hacer para relacionar las queries que se hacen en python con los html, en la ayudantía se vio un ejemplo pero no me quedó claro. De dónde podría encontrar información de esto, he buscado en internet, pero no encuentro algo parecido a lo que se vio en la ayudantía.
Es decir, que no entiendo como funcionan las url, python y html, si me podrían orientar por favor.

**Comment by ypne** [comment]
Hola
Cada grupo tendrá una cuenta en el server donde  deberán crear una base de datos en postgresql y los programas python para manejarla.
Se van a disponibilizar archivos de datos en este repositorio que deberán ser cargados mediante programas python (diferentes a la aplicación).
Para ver como se usa sql desde python, aparte de la ayudantía está lo visto en clases. Buscaré más material para disponibilizarlo.
Saludos

**Comment by tremendapithon** [comment]
@ypne Hola buenas noches, no funciona la conexion al server con ssh grupoxx@codd.ing.puc.cl

**Comment by tremendapithon** [comment]
remplace el xx por el número de mi grupo, lo intente en windows y ubuntu. 
![image](https://github.com/IIC2413/Syllabus-2024-1/assets/119064623/a2cb6d19-5fc5-4c71-843e-41b480b13d8c)
![image](https://github.com/IIC2413/Syllabus-2024-1/assets/119064623/bf11582e-d0d6-451e-9f69-027df1859580)

**Comment by tremendapithon** [comment]
Pero si no esta disponible, con mayor razón deberían extender el plazo hasta el 20 de mayo (medio día), ya que no podemos comenzar a trabajar.

Saludos

**Comment by santiago3c** [comment]
gracias
