### ISSUE TITLE
Sobre la implementacion de la pagina web

### ISSUE THREAD

**Issue by dvillas28** [IIC2413/Syllabus-2024-1#43]
Entiendo que nuestro grupo es el que se encarga de implementar un sitio web para manejar las consultas y mostrar los resultados
¿Nos pasaran alguna plantilla html sobre la que hacer la pagina, o tenemos que hacerla desde cero?

Si es el caso en el que hay que hacerla de cero, ¿tenemos que hacerla usando algún framework/libreria (ej Django, flask etc)?

Saludos!

**Comment by ypne** [comment]
Solo se puede usar Python, no frameworks. No se evalúa la calidad de la página web así que pueden hacerla como deseen.

**Comment by dvillas28** [comment]
pero django y flask son frameworks de python 😢

**Comment by BenzoylMorexide** [comment]
> Solo se puede usar Python, no frameworks. No se evalúa la calidad de la página web así que pueden hacerla como deseen.

Aprovecho de consultar. En una Issue reciente se dijo que se permite Flask y Django, ¿cuál es el veredicto final?

**Comment by ypne** [comment]
aun no está decidido por los profesores hay  varias solicitudes  diversas en tal sentido

**Comment by ypne** [comment]
Se permitió el uso de algunas librerias, fua anunciado por canvas
