### ISSUE TITLE
Entrega n2

### ISSUE THREAD

**Issue by tremendapithon** [IIC2413/Syllabus-2024-1#44]
Hola buenas noches, quisiera hacer una queja respecto a la fecha de entrega, debido que se supone que subirían el enunciado del proyecto el 26 de abril (programa de curso), pero recién lo subieron hoy y no es justo que den menos plazos por el hecho de no subieron el enunciado antes. Por ende, solicito reconsiderar la fecha de entrega. 

Saludos

**Comment by tremendapithon** [comment]
Además, tampoco funciona la conexión con el servidor. 

Saludos

**Comment by elbosco** [comment]
Hola,

Con respecto al cambio de fecha, el trabajo se redujo de lo que era originalmente para ajustarse al nuevo plazo, por lo que no les debería tomar más de una semana trabajando tranquilamente entre tres personas.

Saludos,

**Comment by elbosco** [comment]
El servidor y los datos estarán disponibles en la brevedad

**Comment by tremendapithon** [comment]
Pero tengo una duda respecto a la fecha, consideran 2 semanas para entrega, pero no pueden contar el día lunes, ya que subieron el enunciado en la tarde noche y el servidor no estaba disponible.  Por lo que en la práctica son 13 días y no 14 días (2 semanas).

Saludos

**Comment by ypne** [comment]
La tarea tiene 2 semanas de plazo que fue lo comprometido a principio de semestre. el servidor recien estuvo hoy funcionando
