### ISSUE TITLE
Conexión al servidor

### ISSUE THREAD

**Issue by juanfra111** [IIC2413/Syllabus-2024-1#45]
Hola, estaba tratando de conectarme al servidor que el siguiente comando: ssh grupo86@codd.ing.puc.cl , pero no me funciona. Lo corrí en Ubuntu y en la teminal de windows. Por si alguien me pudiese ayudar.
Gracias!

**Comment by DaniloCordova13** [comment]
Me sucede lo mismo, creo que está caído porque al hacer ping en la terminal sólo se queda esperando hasta que simplemente para.

**Comment by franancic** [comment]
https://github.com/IIC2413/Syllabus-2024-1/wiki/Servidor

**Comment by juanfra111** [comment]
Intenté denuevo y me sale: ssh: connect to host pavlov.ing.puc.cl port 22: Connection timed out.
Qué error puede ser?
