### ISSUE TITLE
Hacer cosas tarea 2

### ISSUE THREAD

**Issue by santiago3c** [IIC2413/Syllabus-2024-1#46]
Hola, que para la tarea 2 entiendo cómo pasar tablas a BCNF y 3NF y que uno puede "pedir" datos al servidor por medio de archivos pytho, pero estoy completamente desorientado con el proceso de encriptación de datos, con las cosas relacionadas a las url y con lo de implementar la página de consultas, el html. De dónde puedo sacar toda esta información, que estoy perdido.

**Comment by franancic** [comment]
https://github.com/IIC2413/Syllabus-2024-1/blob/main/Ayudantia/Ayudantia%203%20-%20HTML%3ACursores/Ayudantía%203%20%20Web%20y%20SQL%20(4).pdf

https://github.com/IIC2413/Syllabus-2024-1/wiki/Servidor

**Comment by tremendapithon** [comment]
para pasar a BCNF o  3NF, los debo hacer en python o en psql? Lo que pensaba hacer es hacer todo el procesamiento con python y dsp ir pasandolos a psql.
