### ISSUE TITLE
Carga de datos Entrega 2

### ISSUE THREAD

**Issue by Mikson16** [IIC2413/Syllabus-2024-1#48]
Hola buenas, tengo una duda con respecto a la carga de los datos, estos deben ser realizados mediante Python ¿Esta acción puede ser realizada con librerías de Python, hay librerías prohibidas? ¿Se puede realizar la carga de los datos con la librería pandas, por ejemplo? En ese caso, la revisión de la integridad de los datos y su procesamiento ¿También puede ser realizada usando librerías de Python, hay alguna que esté prohibida, si es el caso en que se pueda?

**Comment by ypne** [comment]
Se respondió como anuncio en canvas
