### ISSUE TITLE
Framework entrega 2

### ISSUE THREAD

**Issue by noamsito** [IIC2413/Syllabus-2024-1#49]
Hola buenos días, me preguntaba si para la entrega 2 es necesario utilizar python para el desarrollo de la página o está la opción de usar otros lenguajes y/o frameworks como ruby on rails?

Porque hay una issue en la cual mencionan que tenemos que usar python junto con Django o Flask, pero que no podemos usar frameworks, sin embargo Djando y Flask son frameworks de python. 

:D

**Comment by tomas-jackson** [comment]
Hola! En efecto, deben utilizar Python, y la recomendacion es que ocupen Django y Flask. Rails no esta permitido :c, disculpa por la confusion generada :D.

**Comment by ypne** [comment]
se respondio por anuncio en canvas
