### ISSUE TITLE
[Entrega 1] Duda sobre diferencia entre servicio de entrega y empresa de entrega

### ISSUE THREAD

**Issue by eduesquivel** [IIC2413/Syllabus-2024-1#5]
Hola, con mi grupo tenemos una duda respecto a la relación entre el servicio de entrega y la empresa de entrega. Yo hubiera pensado que son lo mismo, sin embargo, el enunciado no lo expresa así.
En el enunciado dice que el cliente debe seleccionar un solo servicio de despacho, sin embargo, como cliente también puedo hacer un pedido que tenga platos de varios restaurantes, siendo que supuestamente cada restaurant tiene su propia empresa de despacho asociada.
Realmente, estamos un poco confundidos con el enunciado, y les agradecería si pudieran aclarar nuestra confusión

**Comment by RaiEscalona** [comment]
Empresas de despacho y restaurantes deberían ser diferentes y no necesariamente estar relacionados. Por lo que dice el enunciado, hay una lista de empresas de despachos distintas y de estas podríamos decir que cada una podría tener un distinto precio y tiempo. 
Por ejemplo, tenemos el pedido X, que pide comida a 3 restaurantes distintos y elegimos que solo un repartidor vaya a buscar toda esa comida, ya que seleccionamos esa empresa de despachos para el hecho. Pero también podríamos elegir tener una persona haciendo el delivery para cada una de las entregas. Es decisión del usuario elegir un único delivery para todo el pedido o varios de ellos.
Por último, recomiendo que se expliquen muy bien en el pdf.
