### ISSUE TITLE
Error al intentar conectarme al servidor

### ISSUE THREAD

**Issue by BenjaCastroo** [IIC2413/Syllabus-2024-1#51]
Hola,
Estoy haciendo la conexion mediante el uso de PowerShell pero al introducir el comando ssh pero me tira: ssh: connect to host pavlov.ing.puc.cl port 22: Connection timed out.

Como puedo evitar esto?

**Comment by TomasRiquelme** [comment]
olis. Es un problema de los servidores, creo que fue por la lluvia del martes.
Mi profe dijo que están tratando de arreglarlo, pero creo todos tenemos el mismo problema

**Comment by ypne** [comment]
está funcionando desde el  domingo pasado
