### ISSUE TITLE
Acerca del informe

### ISSUE THREAD

**Issue by martina-abello** [IIC2413/Syllabus-2024-1#53]
¿Hay algún formato o algo? ¿Y a qué se refiere con "instrucciones para la ejecución de Easyfood"?

**Comment by ypne** [comment]
el informa debe contener lo que se indica solamente

**Comment by martina-abello** [comment]
¿Y a qué se refiere con "instrucciones para la ejecución de Easyfood"?

**Comment by ypne** [comment]
Básicamente lo que haremos para la corrección  es 
1.- Probar los cargadores de datos
2.- Ejecutar easy food
por lo que en el informe se debe describir como ejecutar ambos programas
