### ISSUE TITLE
Dudas de carga e integridad de archivos.

### ISSUE THREAD

**Issue by JosefaInostroza7** [IIC2413/Syllabus-2024-1#54]
![Captura de pantalla 2024-05-10 134613](https://github.com/IIC2413/Syllabus-2024-1/assets/141850856/7648d1f6-9c3b-4f18-8b8b-bc2ed3945858)

Hola! Tengo dudas con la carga de archivos y la integridad de estos. En el enunciado existe el apartado de reglas de negocio, entre ellas está la de la foto. Esta regla en específico debe ser considerada al momento de hacer la carga de archivos a la base de datos?, ¿o solamente es necesario preocuparnos del formato?

Por otra parte, para arreglar el formato de aquellos datos que estén malos, esto se debe hacer luego de la carga de archivos al servidor, o cómo exactamente debiese ser este proceso de limpieza y carga de datos? ¿Esto tendríamos que hacerlo en el script de Python antes de subir los datos al servidor?

**Comment by ypne** [comment]
1.- Las reglas del negocio deben tomarse en cuenta para el modelo E/R
2.- La carga detecta los errores de IC, luego de eso se hace la limpieza

**Comment by BenzoylMorexide** [comment]
O sea, se realiza la carga de datos hacia el servidor en primera instancia como se explica en la wiki, ¿y luego de eso se hace la limpieza? Y esta limpieza sería a través de scripts de python ejecutados... ¿dónde? estoy un poco confundido con el flujo de trabajo. Gracias!
