### ISSUE TITLE
Permiso denegado al ingresar al cliente ssh

### ISSUE THREAD

**Issue by HaliaxWRYY** [IIC2413/Syllabus-2024-1#55]
Hola,
Junto con mi grupo no estamos pudiendo entrar al servidor, cuando intentamos colocar la contraseña nos dice permiso denegado.

Ninguno cambio la contraseña y es la primera vez que intentamos.

¿Que podemos hacer?

**Comment by tremendapithon** [comment]
Mi grupo también tiene el mismo problema, cambie la contraseña antes de que se cayera el server (martes).

**Comment by ypne** [comment]
el server está up a partir de hoy
