### ISSUE TITLE
Acerca de los datos

### ISSUE THREAD

**Issue by martina-abello** [IIC2413/Syllabus-2024-1#56]
Vi que al Syllabus se subió un diagrama E/R pauta, eso es que tenemos que utilizar ése en la entrega 2 en vez del que hicimos para la entrega 1, o hay que modificarlo también?

Si me pudieran explicar el diccionario de datos del enunciado también lo agradecería mucho.

**Comment by tomas-jackson** [comment]
Hola, copio lo que te respondi por telegram:
Ese fue el diagrama "pauta" de la entrega 1. Se puede ocupar como guía para hacer adecuaciones necesarias a su propio diagrama pero hay que tener en mente que no va a tener considerados nuevos requerimientos de la E2 y no necesariamente van a estar su entidades normalizadas.

Sobre el diccionario de datos, en el enunciado se explican varios atributos, ustedes tienen que crear las tablas para poder almacenarlos, el diccionario te dice que tipo de dato es cada atributo y sus restricciones.

**Comment by martina-abello** [comment]
Vale, pero son **todos** los datos necesarios, o hay que mezclarlos con los de la pauta o algo? Pasa que te juro estoy tratando de hacer yo el análisis pero el formato en el que están me marea, sorry.
Entiendo que una Sucursal es una entidad, pero según el diccionario es un string; hay un "preció mínimo reparto gratis", pero si es gratis entonces no es el precio siempre $0?; Direccion aparece como atributo pero al mismo tiempo dice que un cliente puede tener varias; los que no dicen explícito "no nulo" o "no nula" se puede asumir que _pueden_ ser nulos?; qué es el formato +PP en Teléfono Despachador y el +P en Telefono Delivery?; qué significa el símbolo ¡= en los precios por suscripción?
Etc.

**Comment by dvillas28** [comment]
El profe dijo que los "¡" eran errores del LaTeX, que dijo que iba a arreglar en algun momento y actualizar el documento (no se cuando 👍 )

**Comment by ypne** [comment]
hay muchas preguntas diferentes en esta issue
1.- eso es que tenemos que utilizar ése en la entrega 2 en vez del que hicimos para la entrega 1, o hay que modificarlo también?
r: no, deben usar su propio modelo adaptado

2.- Si me pudieran explicar el diccionario de datos del enunciado también lo agradecería mucho.
r: el DD indica erl atributo y sus IC

3.- Entiendo que una Sucursal es una entidad, pero según el diccionario es un string; 
r: una sucursal es un local del restaurant ubicado en una cierta área

4.- hay un "preció mínimo reparto gratis", pero si es gratis entonces no es el precio siempre $0?
r: no, porque se refiere al precio minimo del pedido
5.-  Direccion aparece como atributo pero al mismo tiempo dice que un cliente puede tener varias; los que no dicen explícito "no nulo" o "no nula" se puede asumir que pueden ser nulos?
r: no
6 qué es el formato +PP en Teléfono Despachador y el +P en Telefono Delivery?; qué significa el símbolo ¡= en los precios por suscripción?
r:  el formato PP+9 digitos (PP codigo de pais)
7.- El profe dijo que los "¡" eran errores del LaTeX, que dijo que iba a arreglar en algun momento y actualizar el documento (no se cuando 👍 )
r: si, es un typo, esta corregido en le v2

**Comment by martina-abello** [comment]
1. y cómo hacemos eso sin el feedback?
2. qué significa IC?
3. atributo entonces?
4. no entiendo. eso es, precio mínimo del pedido **para** que el reparto sea gratis? es eso?
5. eso eran dos consultas distintas. a) es una falla de 1nf? b) o sea que sólo pueden ser nulos los atributos que digan que nulo = algún significado?

Gracias.

**Comment by tremendapithon** [comment]
Las tablas que hacemos en sql deben estar normalizadas, sólo especifican la del modelo e/r

**Comment by ypne** [comment]
Hola, voy a precisar un poco los términos
El modelo define Entidades y relaciones. El modelo de la E2 es ligeramente diferente al de la E1 ya que tiene algunos otros atributos y tiene más reglas de negocio.
El  esquena relacional ahora debe estar normalizado
