### ISSUE TITLE
Acerca de Filezilla

### ISSUE THREAD

**Issue by martina-abello** [IIC2413/Syllabus-2024-1#57]
¿Cómo funciona? ¿Hay una cápsula o guía de instalación?
Estoy en filezilla-project.org, pero no sé cuál botón apretar:
![imagen](https://github.com/IIC2413/Syllabus-2024-1/assets/128489585/c627be3f-a6c3-4ce4-8297-46440de32352)
Gracias de antemano.

**Comment by tomas-jackson** [comment]
FileZilla client es lo que necesitas. El instalador es autoexplicativo y una vez termines te da la opcion de abrir la aplicacion, ya despues de ese punto puedes seguir viendo la wiki de este syllabus que te muestra como usarla. 
SI igual no te queda tan claro puedes ver este video sobre el proceso de instalacion

[https://www.youtube.com/watch?v=eqg30GU0Wo8](url)

**Comment by martina-abello** [comment]
El link me manda a esto:
![imagen](https://github.com/IIC2413/Syllabus-2024-1/assets/128489585/8cd4c304-ada5-48a7-abdd-b7b1f7c72430)

¿Cuál selecciono?
![imagen](https://github.com/IIC2413/Syllabus-2024-1/assets/128489585/9ad296ca-f97b-4d71-8710-ec8c374104d0)
