### ISSUE TITLE
Acerca de las reglas de negocio

### ISSUE THREAD

**Issue by martina-abello** [IIC2413/Syllabus-2024-1#58]
No entiendo la diferencia práctica entre Restaurante y Sucursal. ¿Sucursal es una subclase o una entidad débil? Si un restaurante tiene sucursales, ¿existe un restaurante prime que _no_ es sucursal? 
Cuando hablan de Restaurante/Sucursal teniendo Delivery propio, ¿eso es por Restaurante o por Sucursal? Dice que "Los Restaurantes/Sucursal pueden tener solo algunos Delivery", pero ¿cuál es el límite? Cuando dice "Los Restaurantes que tienen despacho...", ¿despacho es la entidad Delivery? 

Cuando dice "Cada Despachador solo puede atender máximo 2 pedidos del mismo Restaurant a la misma comuna.", eso es... en una misma ida/vuelta, o algo? ¿Qué es lo que se está restringiendo aquí, qué es lo que el despachador **no** puede hacer? Un Despachador puede trabajar para más de un Delivery? Porque en la pauta no aparece una relación entre Despachador y Empresa_despachadora, que me parece raro, aún cuando el Despachador tiene el id de la empresa.

Gracias de antemano.

**Comment by ypne** [comment]
1.- un restaurant tiene locales, cada local es una sucursal. 
2.- el delivery propio es por restaurant a eso se refiere que tiene despacho propio sin empresa de delivery
3.- si el despachador tiene id de empresa significa que tiene relacion
