### ISSUE TITLE
Duda dobre datos Cldeldes

### ISSUE THREAD

**Issue by HaliaxWRYY** [IIC2413/Syllabus-2024-1#59]
hola,
estaba viendo los archivos que contienen los datos, pero no puede entender que datos son los que del Archivo Cldeldes.
**¿Son los Clientes que tienen la suscripción con cada empresa de delivery?**  
**¿Porque tendría un despachador especifico, no se supone que cada empresa de delivery podría tener varios despachadores y también un despachador podría ir a mas de un delivery y viceversa, y lo mismo entre cliente y despachador?**
**¿Y porque tendríamos otro archivo de datos que tiene datos sobre clientes, solo que tiene la comuna agregada? Cual seria la diferencia entre los dos datos de clientes que nos están entregando?**
**¿También tendría que usar estos datos para tener los delivery que existen?**

Que atento y gracias.

**Comment by vmunozgarachena** [comment]
Tenemos las mismas dudas

**Comment by ypne** [comment]
¿Son los Clientes que tienen la suscripción con cada empresa de delivery?
r: con algunas
¿Porque tendría un despachador especifico, no se supone que cada empresa de delivery podría tener varios despachadores y también un despachador podría ir a mas de un delivery y viceversa, y lo mismo entre cliente y despachador?
r: si
¿Y porque tendríamos otro archivo de datos que tiene datos sobre clientes, solo que tiene la comuna agregada? Cual seria la diferencia entre los dos datos de clientes que nos están entregando?
r: es parte del trabajo
¿También tendría que usar estos datos para tener los delivery que existen?
r: si
