### ISSUE TITLE
Administradores

### ISSUE THREAD

**Issue by DaniloCordova13** [IIC2413/Syllabus-2024-1#6]
Hola! En el enunciado de la entrega 1 no se especifica qué atributos tienen los administradores. Esto queda a nuestro criterio para modelar?

Además, nos confunde el punto 6 del enunciado, en el cual se menciona que: 

"En un pedido se puede solicitar comida de distintos restaurantes y el despacho será realizado por una sola empresa pero con un servicio despachador por restaurant."

La verdad no entendemos muy bien a qué hace referencia esto, para que nos ayuden un poco por favor. 
Saludos :)

**Comment by Fopazov** [comment]
Relacionado con esto mismo, ¿el precio de despacho depende netamente de la suscripción del servicio de despacho? ¿O también del pedido que se realice? Esto no me queda claro porque si también influye el pedido en sí, no se le podría asignar un precio de servicio por despacho a cada empresa de despacho: "Los administradores de la aplicación deben poder administrar la lista de empresas de despacho y sus despachadores, los precios del servicio por cada despacho y los de suscripción mensual."

**Comment by Fopazov** [comment]
Se dice que el cliente escoge un servicio de despacho al realizar pedido, pero luego que por pedido, el despacho será realizado por una sola empresa, pero CON UN SERVICIO DESPACHADOR POR RESTAURANT.

**Comment by RaiEscalona** [comment]
Los administradores pueden tener permisos para poder editar distintas tablas y cosas por el estilo, pero es cierto que no se mencionan los atributos que deben tener. Pero pueden pensarlo como que son distintos usuarios, por lo que, si alguien está en esa otra tabla, puede ser capaz de hacer cambios dentro de las demás tablas. 
Respecto a lo de las empresas de despachadores, eso acaba de ser respondido en la issue #5 en detalle. Pero, en resumen, se puede contratar a una persona para toda la orden en distintos restaurantes o a una persona por cada orden de cada restaurante. 
Por último, respecto al precio, por mientras podrían verlo como algo más simple y cada empresa cobra X cantidad de dinero y explicar todo bien en sus informes. Pero, pensándolo en una forma más de negocio, dependiendo de cuanto se maneja o las distancias, el precio podría cambiar y podrían haber distintas tarifas en distintos "brackets" de tiempo, pero eso queda para ustedes para modelas y explicar en sus informes, en caso de que quieran hacerlo de esa forma. En otra entrega se les dará más datos y pueden cambiar un poco las cosas para la siguiente entrega pero principalmente piensen en la mejor forma de modelarlo y expliquen su lógica en el pdf.
