### ISSUE TITLE
Duda encriptación

### ISSUE THREAD

**Issue by estardacs** [IIC2413/Syllabus-2024-1#61]
Acá en el punto 4 a que se refieren con la encriptación, debemos seguir algún formato de encriptación o lo hacemos a nuestro criterio, como se espera que sea la encriptación?

![123](https://github.com/IIC2413/Syllabus-2024-1/assets/142100046/1fb1f643-ac8c-470f-bb77-4a8f5d7378bb)

**Comment by ypne** [comment]
ustedes eligen como encriptar, pueden usar la función crypt
