### ISSUE TITLE
Duda con respecto a las sucursales.

### ISSUE THREAD

**Issue by eayaach** [IIC2413/Syllabus-2024-1#63]
Ahora que los restaurantes pueden tener sucursales, ¿la disponibilidad de los platos pertenecerian al restaurante o a la sucursal en específico?. Lo otro, en cuanto a los **delivery** ¿estos son un nuevo tipo de despacho?. ¿Un delivery solo pertence al restaurante y no pertenece a ninguna empresa despachadora? . También, podrían explicar un poco más a que se refiere el dato de vigencia de delivery ¿A que hace referencia este?.

**Comment by ypne** [comment]
¿la disponibilidad de los platos pertenecerian al restaurante o a la sucursal en específico?. 
r: Los platos pertenecen al Restaurante
Lo otro, en cuanto a los delivery ¿estos son un nuevo tipo de despacho?. 
R: No. los delivery son las empresas o aplicaciones de despacho
¿Un delivery solo pertence al restaurante y no pertenece a ninguna empresa despachadora? 
R:Un delivery es una empresa despachadora
También, podrían explicar un poco más a que se refiere el dato de vigencia de delivery 
R: Un delivery puede cerrar sus servicios en forma voluntaria definitivamente (quiebra, venta de la operación, etc.)o temporalmente (lluvia torrencial)en un sector por lo que no estará vigente en ese momento.
