### ISSUE TITLE
Problema conexión al servidor

### ISSUE THREAD

**Issue by tremendapithon** [IIC2413/Syllabus-2024-1#66]
Hola buenas tardes, trato de conectarme al servidor, pero me sale permiso denegado. Cabe considerar que se hizo un cambio de contraseña.

Saludos

**Comment by TomasRiquelme** [comment]
a mi grupo. que todavía no ha cambiado la password, también le pasa lo mismo, y vi una issue que comentaba algo similar.
Me imagino que debe ser por el reinicio de los servers despues de la lluvia; si no han mandado un anuncio puede que todavía no esté listo todo.
Pero no han dicho nada todavía, toca esperar :c

**Comment by ypne** [comment]
el servidor comenzó a funcionar hoy
