### ISSUE TITLE
Duda sobre ServicioDespacho y EmpresaDespacho en E2 🌠.

### ISSUE THREAD

**Issue by SrGarZito** [IIC2413/Syllabus-2024-1#69]
¡Buenas tardes!, dentro de mi grupo se presento una duda que nos genera un poco de problema:

Tras incorporarse el "_Delivery_" y viendo el Diccionario de Datos propuesto en la E2, ¿Debemos fusionar el "_ServicioDespacho_" y "_EmpresaDespacho_" dentro de una misma entidad llamada "_Delivery_"?, porque si nos percatamos dentro del diccionario, prácticamente tienen los mismos atributos de estas dos.

♠️♥️ ¡Estaré atento a la respuesta, gracias de antemano! ♦️♣️

**Comment by ypne** [comment]
existen 2 entidades diferentes una es el delivery o empresa de despacho y la otra el despachador que la persona que reparte. No veo esos atributos en el diccionario de datos, donde están?

**Comment by SrGarZito** [comment]
Entiendo que "_Delivery_" sea la "_EmpresaDespacho_", lo que me refería es que el "_Delivery_" poseía tanto atributos de "_EmpresaDespacho_" (Entendible ahora que sé que es equivalente a este), pero también sería similar a "_ServicioDespacho_".

La duda mía es la siguiente: ¿El "_Delivery_" también sería equivalente a "_ServicioDespacho_"?, ¿Siendo este "_Delivery_" igual a "_EmpresaDespacho_"?

Dentro del Diccionario de Datos no se habla sobre este "_ServicioDespacho_" que si existía en la E1 y tampoco veo ningún alias que lo reemplace, aparte del "_Delivery_" claro.
Lo que me hace pensar en lo siguiente: "_Delivery_" = "_EmpresaDespacho_" = "_ServicioDespacho_".


Quisiera saber si es correcto esa interpretación, esperaré atentamente su respuesta.

♣️♦️ **¡Un saludo y que tenga bonito día!** ♥️♠️

**Comment by SrGarZito** [comment]
En la Pauta del **Diagrama E/R**, salen las entidades dichas en el Enunciado N°1: "_ServicioDespacho_" y "_EmpresaDespacho_"

![image](https://github.com/IIC2413/Syllabus-2024-1/assets/141846948/9512274e-cff7-49d1-a055-36023ad563d4)

Usted me me ha confirmado que "_Delivery_", en el enunciado 2, prácticamente es "_EmpresaDespacho_" con otro nombre. Lo que falta por revisar, es lo que sucede con "_ServicioDespacho_", ¿Esta también sería "_Delivery_"? ¿Queda como estaba en el Diagrama E/R propuesto sin ningún cambio?

La duda surgió porque el concepto de "_Delivery_" puede referirse tanto a una **Empresa**, como a un **Servicio** brindado. Es importante saber esto porque, en la E2, nos solicitan los cambios planteados en este mismo enunciado para el Modelo E/R modificado.

![image](https://github.com/IIC2413/Syllabus-2024-1/assets/141846948/bb130ac6-8a3b-454c-bf9e-3ca1dc895250)

Como "_ServicioDespacho_" no fue nombrado en ninguna parte del Diccionario de Datos ni en ninguna otra parte, desconozco si esta ahora es llamada por otro nombre (lo que sucedió con "_EmpresaDespacho_" que ahora se llama "_Delivery_"), si es también equivalente a "_Delivery_" o simplemente sigue siendo el **Servicio** en sí mismo, como se hizo en la E1 (si es que no hay ninguno cambio solicitado en el **Feedback**).

**_¡Espero se me entienda!_**


♥️♠️ **¡Esperaré pacientemente la resolución que me brinde, gracias de antemano!** ♣️♦️

**Comment by ypne** [comment]
Hola
yo tambien espero haberte entendido. Para la E2 se define como Delivery a la empresa de despacho y como despachador a la persona que hace el despacho, esas son las 2 entidades que incurren en esta parte.

**Comment by ypne** [comment]
Hola
Ajústense al enunciado de la E2
