### ISSUE TITLE
Duda materia de Algebra racional

### ISSUE THREAD

**Issue by javisantibanez** [IIC2413/Syllabus-2024-1#7]
<img width="707" alt="image" src="https://github.com/IIC2413/Syllabus-2024-1/assets/141786962/e9a7e272-b3b9-4d38-ad3f-5e4f9b777eb3">
Hola, tengo una duda con este ejemplo que se vio en clases. Lo que no entendí es por qué cuando se renombra la relación "peliculas_join" y hacen el join entre las relaciones Películas y Actores la condición es: actores.id = actuo_en.id_actor si Actuo_en.id_pelicula no pertenece a ninguna de las dos relaciones que se están juntando.

**Comment by MartyMolina** [comment]
Respecto a Actuo_en.id_pelicula, pertenece a la primera tabla que hace referencia a Actuo_en. Si en realidad querías preguntar sobre actuo_en.id_actor, este hace referencia al atributo que se tiene en  Actuo_en que estaba en el join anterior, ya que el segundo join se realiza entre Actores y el join anterior de Actuo_en y Peliculas.
