### ISSUE TITLE
Notación en Modelo Relacional

### ISSUE THREAD

**Issue by flcarvallo** [IIC2413/Syllabus-2024-1#72]
Hola, se puede usar la notación "nombre STRING(30)" o hay que usar "nombre VARCHAR(30)"?

**Comment by ypne** [comment]
Recomiendo que busquen los tipos de datos de Postgresql y utilicen esos para una más r´papida transformación de M E/R a Esquema Relacional. referencia 
https://www.postgresql.org/docs/14/index.html
