### ISSUE TITLE
Problema en Conexión psycopg2

### ISSUE THREAD

**Issue by dvillas28** [IIC2413/Syllabus-2024-1#73]
Estamos tratando de conectarnos a la bdd con psycopg2. Tenemos este script, que copiamos de la ayudantia

obs: la clave la blanqueamos para no filtrarla en la issue xd

```python
import psycopg2

NOMBRE = "grupo15e2"
USER = "grupo15"
HOST = "pavlov.ing.puc.cl"
PORT = 5432
PASSWORD = "****"

try:
    conn = psycopg2.connect(
        f'dbname={NOMBRE} user={USER} host={HOST} port={PORT} password={PASSWORD}')
    print("Connected!")
except Exception as e:
    print(e)
```
Pero nos lanza este error
![image](https://github.com/IIC2413/Syllabus-2024-1/assets/128737225/6e6f15d1-e7be-4832-a7b7-61131bd3b0d6)
¿Alguien sabe que puede ser?
Saludos!

**Comment by TomasRiquelme** [comment]
me pasa lo mismo! ni idea que pasa

**Comment by ypne** [comment]
Cuando probaron?

**Comment by dvillas28** [comment]
hace como 1 hora

**Comment by TomasRiquelme** [comment]
yo hace como 2 horas, cuando respondí en la issue

**Comment by ypne** [comment]
prueben de nuevo por favor

**Comment by dvillas28** [comment]
tira el mismo error D:

**Comment by TomasRiquelme** [comment]
Estoy probando ahora un script para crear una tabla; ahora cuando ejecuto el código "no pasa nada" en el sentido que no tira error pero se queda mucho tiempo sin retornar nada, como si el programa no acabara. Se demora más de 30 segundos, tengo que pararlo con control z para que pare :c

**Comment by tremendapithon** [comment]
A mi tampoco me funciona

**Comment by LMD18** [comment]
me sale el mismo error: 
port 5432 failed: Connection refused Is the server running on that host and accepting TCP/IP connections?

**Comment by TomasRiquelme** [comment]
gente buena, intenten de nuevo; ahora a mi me resultó hacer un SELECT desde un script python

**Comment by TomasRiquelme** [comment]
genteeeeee, prueben ahora!
hice una prueba random y ahora sí me dejo hacerlo!

**Comment by LMD18** [comment]
> genteeeeee, prueben ahora! hice una prueba random y ahora sí me dejo hacerlo!

Buenaaa ahora si me dejoo

**Comment by tremendapithon** [comment]
Tambien me funciono, pero como cambio la contraseña del psql?

**Comment by ypne** [comment]
cambia la clave del ubuntu con passwd

**Comment by dvillas28** [comment]
funciona!
