### ISSUE TITLE
Formato de datos .csv

### ISSUE THREAD

**Issue by cron53** [IIC2413/Syllabus-2024-1#75]
Hola, ¿Será posible que estandaricen el formato de los datos? Hay string que tienen cremillas ("xxx"), por ejemplo en comunas.csv y restaurantes.csv, pero otros archivos no. Además el separador en comunas.csv es una coma (,), mientras que en los otros archivos es punto y coma(;). No es que sea difícil hacer el código específico para cada archivo, pero quiero saber si lo cambian para no hacer código de más.

**Comment by cron53** [comment]
Además, el archivo pedidos.csv los tildes no los reconoce

**Comment by ypne** [comment]
los archivos de datos terminados en 2 están con los caracteres homologados y ; como separador
