### ISSUE TITLE
Ingreso fallido a base de datos

### ISSUE THREAD

**Issue by NachoRinda** [IIC2413/Syllabus-2024-1#79]
Una vez dentro del server no podemos entrar a la base de datos con el comando psql. Nos entrega el siguiente mensaje: psql: error: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: FATAL:  role "grupoX" does not exist, donde X es el # de nuestro grupo. Porfavor indicarnos si estamos accediendo de manera errónea. Gracias.

**Comment by Mikson16** [comment]
Sobre este mismo problema, cuando realizamos el cambio de contraseña para la base de datos, este cambio no se realiza, ya que la proxima vez que intentamos accede nos aparece este mismo error y debemos conectar con la contraseña antigua, @ypne

**Comment by ypne** [comment]
por favor envía los datos del grupo para ver el problema

**Comment by Mikson16** [comment]
> por favor envía los datos del grupo para ver el problema

Somos el grupo19, que informacion extra necesita?
@ypne

**Comment by ypne** [comment]
Hice la prueba y funciona

grupo19@pavlov:/var/log/sysstat$ cd
grupo19@pavlov:~$ psql
Password for user grupo19: 
psql (14.11 (Ubuntu 14.11-0ubuntu0.22.04.1))
Type "help" for help.

grupo19=> \dt
Did not find any relations.
grupo19=>
