### ISSUE TITLE
Duda administración y registro

### ISSUE THREAD

**Issue by vmunozgarachena** [IIC2413/Syllabus-2024-1#8]
Hola! Los últimos puntos de las características de la aplicación hablan más sobre la administración de esta y el registro de pagos, que sentimos que son puntos que servirán más en el futuro como haciéndolo en SQL y que no están tan relacionados con el modelo E/R. Es necesario que estos puntos se encuentren en el modelo?

**Comment by RaiEscalona** [comment]
Siguen siendo parte de la entrega y puede que no se usen ahora y se usen en un futuro. Pero de igual forma, habría que hacerlos y dependiendo de lo que se va pidiendo en las otras entregas, se deben refinando para que funcione bien la aplicación.
