### ISSUE TITLE
Duda normalizacion

### ISSUE THREAD

**Issue by tremendapithon** [IIC2413/Syllabus-2024-1#81]
Hola, dentro del enunciado mencionan que el modelo que hagamos debe estar en 3NF o BNFC, mi duda es que si aplica lo mismo para los datos que nos dan, es decir, que tengamos que normalizar los datos que nos entregan, ya que si nuestro modelo e/r y esquemas estan normalizados, no es tan claro si las tablas o relaciones en sql también deben estarlo?

Saludos

**Comment by tremendapithon** [comment]
Ahhh, pero los datos que subieron también? O solo debemos ajustarlos para que cumplan las restricciones dw dominio??

**Comment by ypne** [comment]
Hola, los datos no son tablas normalizadas

**Comment by tremendapithon** [comment]
entonces se normalizan o son para la e3?

**Comment by ypne** [comment]
se normalizan, ese es uno de los temas del enunciado
