### ISSUE TITLE
plato en pedidos.csv

### ISSUE THREAD

**Issue by cron53** [IIC2413/Syllabus-2024-1#82]
Hola, quisiera consultar sobre la columna de platos en pedidos.csv. ¿Los pedidos que tiene varios platos están separados por 2 espacios? Es decir, por ejemplo:

7;Nicolas.Zambrano@bbdduc.utopia;Delicia China;Maintenci—n;Balloon;Eli Howard;1  19  56  6;23-09-23;9:18:36;entregado a cliente

¿El pedido id 7 tiene los platos 1, 19, 56 y 6?

Además, ya no debemos considerar eso de que un pedido puede tener platos de varios restaurants, como decían en la entrega 1? Esto último, porque en el archivo de pedidos, cada id tiene asociado sólo un restaurant.

**Comment by ypne** [comment]
1.- El pedido tiene platos separados por blancos (no necesariamente 2)
2.- Los platos pueden ser de diferentes restaurantes
