### ISSUE TITLE
llave de despachador es su nombre?

### ISSUE THREAD

**Issue by cron53** [IIC2413/Syllabus-2024-1#83]
Hola, es posible que hayan 2 despachadores con el mismo nombre? Pregunto porque en los datos sólo tenemos el nombre y teléfono de los despachadores, que están en cldeldes.csv. Y la única forma de relacionarlos (hacer join) con los pedidos que han realizado sería su nombre, ya que es su única info que está en pedidos.csv

**Comment by ypne** [comment]
si, pueden usar el nombre o el teléfono
