### ISSUE TITLE
Dependencias en platos.csv

### ISSUE THREAD

**Issue by cron53** [IIC2413/Syllabus-2024-1#84]
En el enunciado se menciona que "Los Platos que se llaman igual pueden ser diferentes en cada Restaurant". Eso me queda claro, pero quisiera saber qué es único de cada plato. Por ej: "Pizza Margarita". Todos los platos "Pizza Margarita" tienen la misma descripcion, estilo, restriccion, ingredientes, porciones y tiempo?. Sé que pueden tener distinto precio, restaurant, repartomin, vigente, etc...

**Comment by ypne** [comment]
Un restaurant siempre tiene platos de un sólo estilo?
R: No
