### ISSUE TITLE
¿Cómo se sanitiza un salto de línea?

### ISSUE THREAD

**Issue by martina-abello** [IIC2413/Syllabus-2024-1#87]
En el archivo cldeldes.csv está este cliente:
![imagen](https://github.com/IIC2413/Syllabus-2024-1/assets/128489585/f717ef1d-985f-4e36-b534-14bbf55e3f27)
Es el único con ese formato, y al pasar los datos a la tabla queda igual, y hace que en consultas sql solo se pueda encontrar si se incluye el salto de línea. ¿Cómo se arreglaría eso?

Gracias de antemano.

**Comment by ypne** [comment]
Bastante bien Lucas.
en este caso el cargador debe 1.- sanitizar el input sacando los caracteres incorrectos o 2.- leer el input crudo esperar que el INSERT falle y luego encontrar todos los errores del mismo tipo, arreglarlos de la forma correcta (borrar la tupa o como en este caso corregir el input a mano) y volver a cargar solo los que quedaron fuera.
