### ISSUE TITLE
Suscripción y Precios

### ISSUE THREAD

**Issue by Lucas-Purcell** [IIC2413/Syllabus-2024-1#88]
Hola
Estoy confundido con respecto a las suscripciones, como no lo explican muy bien en el enunciado. Tengo dudas sobre como funciona la suscripción y cual es el precio que tiene que pagar una persona suscrita por sus pedidos. ¿Una persona suscrita no paga delivery en el periodo que dura la suscripción?
Gracias de antemano!

**Comment by ypne** [comment]
asi es
una persona, si está suscrita a un delivery paga solo la suscripción. OJO la suscripción tiene que estar VALIDA y una suscripción válida es cuando se cumple 1 o 2
1.- está activa
2.- está cancelada pero todavía quedan dias restantes para el proximo pago
