### ISSUE TITLE
Duda usuarios mensuales

### ISSUE THREAD

**Issue by emiliamarti** [IIC2413/Syllabus-2024-1#9]
Hola! Tengo una duda con la parte del enunciado que dice "Se tiene un registro de cada empresa despachadora conteniendo a los usuarios que pagan la suscripción mensual". En este caso usuario sería lo mismo que cliente y la empresa solo contendría a usuarios que pagan mensualmente y no anualmente?

**Comment by RaiEscalona** [comment]
Si, usuario sería lo mismo que cliente ya que son ellos los que están contratando el servicio. También podría contener a los usuarios que pagan anualmente y deberías en ese caso tener una forma de diferenciar los 2 tipos de suscripciones.
