### ISSUE TITLE
Sobre la entidad delivery y archivo cldeldes.csv

### ISSUE THREAD

**Issue by ManuelV03** [IIC2413/Syllabus-2024-1#90]
Hola, revisando los datos y haciendo el esquema relacional para la entrega 2, no entendí muy bien cómo es que se usa esta entidad a partir de los datos entregados.
Viendo los datos, solo hay dos archivos en los que se habla de algo relacionado con delivery, los cuales serían cldeldes.csv y pedidos.csv.
En el primero de estos me doy cuenta de que en cada fila se relacionan datos de un cliente con datos de un delivery y datos de un despachador. Podría entender que esta relacion se da cuando un cliente realiza un pedido mediante un delivery y el despachador sería el despachador asignado a ese pedido, pero en ese caso siento que faltaría un id del pedido para saber que pedido fue el que causo que esas 3 entidades llegaran a relacionarse en un principio.
Por otro lado, siento que faltan datos que digan que restaurantes tienen que deliverys disponibles y también que despachadores trabajan para cada delivery, debido a que sino no podriamos verificar si cuando estamos añadiendo un pedido es correcto asignarle cierto delivery o despachador, o si deberíamos eliminar la solicitud.

**Comment by ypne** [comment]
Hola
Si no hay mas datos para construir las mas tuplas en las tablas, saca de los datos disponibles. Que un restaurant tenga solo un delivery y un delivery solo un despachado cumple las IC.

**Comment by c4ebt** [comment]
No hay información suficiente para establecer relaciones directas entre instancias específicas de pedido y despachador solo basandose en el cliente y el delivery. Dados los datos de `cldeldes.csv`, perfectamente se podría dar la situación de que un mismo despachador esté atendiendo al mismo cliente mediante el mismo delivery para dos pedidos distintos, por lo que falta información.

Por otra parte, me parece que los datos, o están erróneos, o dan lugar a interpretaciones equívocas. Concretamente, por ejemplo, el despachador "Alexander Robinson" aparece en dos pedidos con dos delivery distintos y dos clientes distintos, pero en `cldeldes.csv` aparece solo una vez con uno de estos clientes+delivery, y el otro no aparece:
![image](https://github.com/IIC2413/Syllabus-2024-1/assets/50504998/a54001df-ae21-431c-8f5b-a0d94eda13ac)
¿Es esto un error? Si no, ¿cómo se explica esto en el contexto de los archivos dados? ¿Se debe hacer un chequeo comparando los archivos `cldeldes.csv` y `pedidos.csv` al cargarlos para verificar que cada tupla (cliente, delivery, despachador) no esté presente en uno y no en el otro?

**Comment by ypne** [comment]
No hay información suficiente para establecer relaciones directas entre instancias específicas de pedido y despachador solo basandose en el cliente y el delivery. Dados los datos de cldeldes.csv, perfectamente se podría dar la situación de que un mismo despachador esté atendiendo al mismo cliente mediante el mismo delivery para dos pedidos distintos, por lo que falta información.
R: Puedes explicar más el problema?

Por otra parte, me parece que los datos, o están erróneos, o dan lugar a interpretaciones equívocas. Concretamente, por ejemplo, el despachador "Alexander Robinson" aparece en dos pedidos con dos delivery distintos y dos clientes distintos, pero en cldeldes.csv aparece solo una vez con uno de estos clientes+delivery, y el otro no aparece:
image
¿Es esto un error? Si no, ¿cómo se explica esto en el contexto de los archivos dados? ¿Se debe hacer un chequeo comparando los archivos cldeldes.csv y pedidos.csv al cargarlos para verificar que cada tupla (cliente, delivery, despachador) no esté presente en uno y no en el otro?
R:   Los datos no están  normalizados, es posible que el una tabla aparezca una vez y en otra mas ya que los datasets pueden tener datos que se superpongan o complementen.

**Comment by c4ebt** [comment]
> Puedes explicar más el problema?

El problema es que dada una tupla (clientenombre, deliverynombre, despachadornombre) perteneciente a `cldeldes.csv`, no es posible identificar a que pedido corresponde esta relación entre cliente y delivery-despachador, ya que en `cldeldes.csv` no hay ninguna referencia a pedido. Por ello, se podría dar que un mismo cliente haga dos pedidos que terminen con el mismo delivery-despachador, sin embargo, tengan características distintas, como deliverytiempo, y en este caso no se podría determinar cual es cual.

> Los datos no están normalizados, es posible que el una tabla aparezca una vez y en otra mas ya que los datasets pueden tener datos que se superpongan o complementen.

Mi pregunta no va hacia la normalización de los datos, sino a entender que significan en términos de negocio. En el ejemplo de arriba, ¿cómo se interpreta el hecho de que un mismo despachador esté relacionado a un cliente en `pedidos.csv` pero no en `cldeldes.csv`?

**Comment by HaliaxWRYY** [comment]
Tal vez podria ser que son fallos que tenemos que tener presentes para la creación de nuestra base de datos? 
Podria ser un caso de restriccion, o sea nuestra base de datos no permitiría que exista un pedido que no se correlacione con la tabla cldeldes.csv?

**Comment by ypne** [comment]
Cuando eso ocurra deben buscar una solución. Si su modelo permite que los datos están incompletos ok, si no lo permite deben solucionarlo.
