### ISSUE TITLE
Duda sobre tabla ServicioDespacho

### ISSUE THREAD

**Issue by juandurand** [IIC2413/Syllabus-2024-1#91]
Hola! Leyendo la pauta sobre la E1 del proyecto, no me queda del todo claro las tablas ServicioDespacho y Despacho. ¿Cómo se modelaría un pedido de dos restaurantes distintos los cuales tengan Empresas de despacho distintas? Debido a que en la pauta se relaciona en la entidad Despacho, la entidad Pedido con la Empresa de Despacho.

**Comment by ypne** [comment]
Debes regirte por las reglas de negocio de la E2. El enunciado de la E1 es extendido en esta entrega
