### ISSUE TITLE
Cargadores Python

### ISSUE THREAD

**Issue by Lucas-Purcell** [IIC2413/Syllabus-2024-1#92]
Hola
¿Los cargadores de datos python tienen que ser utilizados una sola vez para subir a la base de datos los csv entregados o tienen que admitir la posibilidad de volver a ser utilizados si se deseara insertar datos nuevos y distintos?
Gracias de antemano

**Comment by ypne** [comment]
Como tu indiques en el informe, pero si debe ser capaz de subir un subconjunto de los datos
