### ISSUE TITLE
error en restaurantes2.csv

### ISSUE THREAD

**Issue by martina-abello** [IIC2413/Syllabus-2024-1#93]
Creo que usaron integers en vez de strings para teléfono cuando modificaron restaurantes.csv, lo que resultó en esto:
![imagen](https://github.com/IIC2413/Syllabus-2024-1/assets/128489585/0bfc67e7-9fc1-47d6-b99b-46e55b0bcbbf)
og:
![imagen](https://github.com/IIC2413/Syllabus-2024-1/assets/128489585/3ede2e7e-842e-41ba-9c6e-66197cba3be1)
no sé si ahora es algo que tenemos que sanitizar (que llevaría a muchas tuplas perdidas, no hay cómo adivinar los dígitos que faltan sin ver el restaurantes.csv original) o si lo van a arreglar.

Gracias de antemano.

**Comment by ypne** [comment]
esta arreglado
