### ISSUE TITLE
Duda sobre las comunas

### ISSUE THREAD

**Issue by c4ebt** [IIC2413/Syllabus-2024-1#95]
El archivo `clientes.csv` tiene una columna llamada comuna, que es el CUT de la comuna del cliente. Este dato está relacionado al archivo `comuna2.csv`, en donde el CUT se relaciona a la comuna, provincia y región correspondiente.  Por otra parte, todas las direcciones de clientes son una string de la forma "calle número, comuna", por lo que el archivo `comuna2.csv` es redundante de cierta forma. En base a esto:

¿Existe la posibilidad de que haya dos comunas distintas (distinto CUT) con el mismo nombre?
En el caso de que sí sea posible, ¿como se resuelve la ambigüedad del archivo `restaurantes2.csv`, en el que la columna área referencia simplemente a un nombre de comuna?
En el caso de que no sea posible, ¿cuál es la utilidad del archivo `comuna2.csv`, siendo que se pueden trabajar las comunas simplemente con las strings de dirección/área, ya que son únicas?

**Comment by ypne** [comment]
La tabla comunas sirve para referenciar el CUT solamente

**Comment by c4ebt** [comment]
Me parece que eso no responde muy bien a mi pregunta... Considerando que el CUT no es incorporado en la aplicación de ninguna manera, si la tabla de comunas sirve solo para referenciar el CUT, ¿entonces por que la usaríamos en la aplicación?

**Comment by ypne** [comment]
Porque la comuna del cliente tiene incorporado CUT

**Comment by c4ebt** [comment]
La dirección del cliente también tiene incorporada la comuna, por lo que el CUT solo serviría para referenciar provincia o región en la tabla `comuna2.csv`, datos que no son utilizados en la aplicación. ¿Por qué necesitaría referenciar el CUT?

**Comment by ypne** [comment]
Si tienes el dato duplicado (es parte del análisis) elige el que quieras usar
