### ISSUE TITLE
Dependencias

### ISSUE THREAD

**Issue by cron53** [IIC2413/Syllabus-2024-1#97]
Hola, he estado bastante tiempo viendo las dependencias de las tablas, pero no tengo cómo asegurarme de si mis suposiciones son correctas. Por ello considero que nos deberían decir, al menos en un párrafo parafraseado las dependencias.
Por ejemplo, en el archivo platos.csv pareciera que descripción, ingredientes y estilo dependen de nombre, lo que disminuiría la redundancia de la tabla, pero considero que deberían decir todas esas dependencias.

Lo mismo con comunas.csv: Pareciera que región está determinada por provincia.

Por último, en restaurantes.csv. Me gustaría saber si "vigente", "estilo", "repartomin" se determinan sólo por el nombre del restaurant (pareciera ser así), o se determinan por nombre del restaurant + sucursal.

Cómo última duda para cerrar: ¿repartomin en restaurantes.csv debería ser igual para un restaurant, que repartomin de un plato de ese mismo restaurant?

Honestamente creo que falta especificar bastante para poder asegurarse de hacer las tablas de forma correcta y normalizada.

**Comment by ypne** [comment]
Por ejemplo, en el archivo platos.csv pareciera que descripción, ingredientes y estilo dependen de nombre, lo que disminuiría la redundancia de la tabla, pero considero que deberían decir todas esas dependencias.
R: si un plato tiene una descripción e ingredientes

Lo mismo con comunas.csv: Pareciera que región está determinada por provincia.
R: si, en chile no hay dos provincias de igual nombre en la misma región, no así la comuna

Por último, en restaurantes.csv. Me gustaría saber si "vigente", "estilo", "repartomin" se determinan sólo por el nombre del restaurant (pareciera ser así), o se determinan por nombre del restaurant + sucursal.
R: si, un restaurant tiene nombre único, determina su estilo, pone precio a su reparto minimo y puede estar vigente o no

Cómo última duda para cerrar: ¿repartomin en restaurantes.csv debería ser igual para un restaurant, que repartomin de un plato de ese mismo restaurant?
R; no, un restaurant fija un precio de reparto minimo propio por monto del pedido a dicho restaurant, no el plato

Honestamente creo que falta especificar bastante para poder asegurarse de hacer las tablas de forma correcta y normalizada.

**Comment by c4ebt** [comment]
> "en chile no hay dos provincias de igual nombre en la misma región, no así la comuna"

Tanto en las tablas de datos entregadas como en la realidad de nuestro país, no existen dos comunas con el mismo nombre. ¿Es entonces la dependencia proveniente en primera instancia de comuna?

**Comment by ManuelV03** [comment]
> "si un plato tiene una descripción e ingredientes"

Con esto se refiere a que descripción ingredientes y estilo dependen del id del plato o que dependen de su nombre?

> "si, en chile no hay dos provincias de igual nombre en la misma región, no así la comuna"

Siento que esto no responde a la pregunta que iba más enfocada en: Pueden existir dos regiones distintas que tengan una provincia con el mismo nombre o en otras palabras. Se cumple que provincia -> region?

**Comment by ypne** [comment]
1.- Muy Buena tu pregunta porque el que analiza los datos debe conocer el negocio para modelar bien.
Te voy la respuesta como si estuvieras hablando con una persona del rubro de los restaurantes. Existen platos que son bastante estándar como por ejemplo Lasagna Bolognesa que es una pasta en láminas con salsa bolognesa. Pero hay variaciones en la preparación, la pasta puede ser de direrentes harinas (ingredientes) y la salsa puede tener algunos ingredientes diferentes. Por lo tanto el mismo plato "nombre" no necesariamente tiene los ingredientes. Por otra parte la descripción del plato la hace el restaurante por lo que puede diferir entre ellos. Espero que esto te aclare la duda.
2.- Yo pienso que la respuesta anterior si responde la pregunta y. Por último puedes ir a ver los datos que corresponden a la lista oficial de la división política del país.
