### ISSUE TITLE
Sobre las restricciones en dirección de sucursal

### ISSUE THREAD

**Issue by martina-abello** [IIC2413/Syllabus-2024-1#98]
Esta es la restricción según el diccionario del enunciado:
![imagen](https://github.com/IIC2413/Syllabus-2024-1/assets/128489585/6564b8fa-7a53-4977-9b3a-7d0ef7a1201e)
tengo 3 consultas. Primero, la direccion en restaurantes2.csv a veces incluye la provincia, cuando es Santiago. 
![imagen](https://github.com/IIC2413/Syllabus-2024-1/assets/128489585/87c59421-5b10-4a9f-9877-e429b989cd28)
¿Hay que sanitizar eso, o sea, eliminar el ", Santiago"?
Segundo, como se ve en la imagen de arriba, hay direcciones que incluso sin el ", Santiago" tienen más de 30 caracteres. ¿Esas tuplas son inválidas?
Tercero y último, que la restricción diga "calle número y comuna" significa que el atributo sí o sí tiene que incluir todo eso? ¿No podría yo, por ejemplo, quitarle la comuna y añadir el atributo "cut" a la sucursal?

Muchas gracias de antemano.

**Comment by ypne** [comment]
Esto ya está respondido en otra issue
Sanitizar: Si
Largo de dirección: La tupla ni es inválida, que solución pueden aplicar?
Formato dirección: si podrían hacerlo
