### ISSUE TITLE
Fecha próximo pago de suscripción

### ISSUE THREAD

**Issue by martina-abello** [IIC2413/Syllabus-2024-1#99]
Se pidió en la entrega 1, pero en esta no sé si ya no aplica, como el medio de pago, o si hay que sacarla con la fecha del último pago y el ciclo (ya que no está explícita en los archivos de datos).

Gracias de antemano.

**Comment by ypne** [comment]
no hay medio de pago en la E2

**Comment by martina-abello** [comment]
...i know. hice una issue de eso. ahora pregunto si con la fecha del próximo pago es lo mismo.

**Comment by ypne** [comment]
depende del ciclo, si es mensual es el mismo dia del siguiente mes Si es anual en la misma fecha del año soiguiente

**Comment by martina-abello** [comment]
pero entonces sí es un atributo que hay que tener en la tabla de suscripciones?

**Comment by ypne** [comment]
ese es un tema del modelo

**Comment by martina-abello** [comment]
ok thanks
